### ISSUE TITLE
Feature request: Conditional rules for security groups

### ISSUE THREAD

**Issue by lblackstone** [terraform-providers/terraform-provider-openstack#1]
### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
- openstack_compute_secgroup_v2

It would be useful to include a `count` parameter or similar on the security group rules so that a security group could be configured dynamically. Currently, conditional logic requires the creation of multiple security groups.

For example:
```tf
resource "openstack_compute_secgroup_v2" "foo_grp" {
  rule {
    count = "${var.foo ? 1 : 0}"
    from_port   = 42
    to_port     = 42
    ip_protocol = "tcp"
    cidr        = "0.0.0.0/0"
  }
```

---
Original post:
### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
- openstack_networking_secgroup_v2
- openstack_networking_secgroup_rule_v2

It would be useful to include a `count` parameter or similar on the security group rules so that a security group could be configured dynamically. Currently, conditional logic requires the creation of multiple security groups.

**Comment by jtopjian** [comment]
@lblackstone All resources support the `count` parameter. Can you give an example of how you see this working?

**Comment by lblackstone** [comment]
@jtopjian Oops, my mistake. I meant `openstack_compute_secgroup_v2`. It works as you describe for the `openstack_networking_secgroup_*` resources. Updated the description and included an example.

**Comment by lblackstone** [comment]
After discussing the issue with @jrperritt, we found that the underlying nova call is actually [deprecated](https://developer.openstack.org/api-ref/compute/#list-networks), so it's probably not worth adding any features to this resource type.

Closing out this issue and using `openstack_networking_secgroup_*` instead.

Example:
```tf
resource "openstack_networking_secgroup_v2" "foo-grp" {
  name = "FOO"
}

resource "openstack_networking_secgroup_rule_v2" "foo" {
  direction         = "ingress"
  ethertype         = "IPv4"
  security_group_id = "${openstack_networking_secgroup_v2.foo-grp.id}"
  count             = "${var.foo_enabled ? 1 : 0}"
  protocol          = "tcp"
  port_range_min    = 42
  port_range_max    = 42
  remote_ip_prefix  = "0.0.0.0/0"
}
```

**Comment by jtopjian** [comment]
Yep, that's exactly the reason the Compute secgroup resource has stayed this way. It's better for users to switch to the Network resources and let this one hang around for legacy use. :)
