### ISSUE TITLE
openstack_keymanager_container_v1 creation failed with http 400 error

### ISSUE THREAD

**Issue by lperrin-obs** [terraform-providers/terraform-provider-openstack#1005]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version
```
terraform -v
Terraform v0.12.24
+ provider.openstack v1.27.0
+ provider.tls v2.1.1
```

### Affected Resource(s)
- openstack_keymanager_container_v1

### Terraform Configuration Files
```hcl
resource "tls_private_key" "continuous_test_lb_private_key" {
  algorithm   = "RSA"
  rsa_bits    = "4096"
}

resource "tls_self_signed_cert" "continuous_test_lb_cert" {
  key_algorithm   = tls_private_key.continuous_test_lb_private_key.algorithm
  private_key_pem = tls_private_key.continuous_test_lb_private_key.private_key_pem

  subject {
    common_name  = "nginx.continuous-test.cloud-lab.620nm.net"
    organization = "OBS"
  }

  validity_period_hours = 1

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "openstack_keymanager_secret_v1" "continuous_test_lb_private_key_secret" {
  name                 = "continuous_test_lb_private_key"
  payload              = tls_private_key.continuous_test_lb_private_key.private_key_pem
  payload_content_type = "text/plain"
  secret_type          = "private"
}

resource "openstack_keymanager_secret_v1" "continuous_test_lb_cert_secret" {
  name                 = "continuous_test_lb_cert"
  payload              = tls_self_signed_cert.continuous_test_lb_cert.cert_pem
  payload_content_type = "text/plain"
  secret_type          = "certificate"
}

resource "openstack_keymanager_container_v1" "continuous_test_lb_tls_secret" {
  name = "continuous_test_lb_tls"
  type = "certificate"

  secret_refs {
    name       = "certificate"
    secret_ref = openstack_keymanager_secret_v1.continuous_test_lb_cert_secret.secret_ref
  }

  secret_refs {
    name       = "private_key"
    secret_ref = openstack_keymanager_secret_v1.continuous_test_lb_private_key_secret.secret_ref
  }
}
```

### Debug Output
https://gist.github.com/lperrin-obs/3b109c7d4b4c87308abb4a47f691010b

### Expected Behavior
Container should be created correctly

### Actual Behavior
The container is created but with no secret inside

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Openstack version is Queens

**Comment by kayrus** [comment]
@lperrin-obs what if you change the container type to `generic`?

**Comment by kayrus** [comment]
FYI: opened a bug report for Barbican https://storyboard.openstack.org/#!/story/2007629

**Comment by lperrin-obs** [comment]
Changing container type to `generic` make it work.

I'm checking if it can then used with an octavia loadbalancer for TLS termination as describded on the [openstack_keymanager_container_v1 resource documentation](https://www.terraform.io/docs/providers/openstack/r/keymanager_container_v1.html)

**Comment by ahkhystrix** [comment]
I tried to create a generic type container.
Create with it a listener TERMINATED_HTTPS did not work:
`
Error: expected protocol to be one of [TCP UDP HTTP HTTPS PROXY], got TERMINATED_HTTPS

  on .../main.tf line 56, in resource "openstack_lb_pool_v2" "pool":
  56: resource "openstack_lb_pool_v2" "pool" {`

**Comment by kayrus** [comment]
@ahkhystrix what if you set HTTPS?

**Comment by ahkhystrix** [comment]
@kayrus I tried to use HTTPS too:

Error: Error creating openstack_lb_listener_v2: Bad request with: [POST https://******/load-balancer/v2.0/lbaas/listeners], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Validation failure: Certificate container references are only allowed on TERMINATED_HTTPS protocol listeners."}

**Comment by kayrus** [comment]
@ahkhystrix can you run terraform with debug log?

```
TF_LOG=DEBUG OS_DEBUG=true terraform apply
```

and upload debug code to https://gist.github.com/?

**Comment by ahkhystrix** [comment]
> 
> 
> @ahkhystrix can you run terraform with debug log?
> 
> ```
> TF_LOG=DEBUG OS_DEBUG=true terraform apply
> ```
> 
> and upload debug code to https://gist.github.com/?

What exactly is needed?

1. config type certificate?

2. config type generic & terminated_https?

**Comment by kayrus** [comment]
@ahkhystrix most probably your openstack provider doesn't support `TERMINATED_HTTPS`. Therefore I'd like to clarify this from the terraform debug output.

**Comment by ahkhystrix** [comment]
> 
> 
> @ahkhystrix most probably your openstack provider doesn't support `TERMINATED_HTTPS`. Therefore I'd like to clarify this from the terraform debug output.

<script src="https://gist.github.com/ahkhystrix/6abdf94227df54f1d233074578984fd2.js"></script>

**Comment by kayrus** [comment]
@ozerovandrei looks like selectel doesn't support `TERMINATED_HTTPS`. Could you please confirm?

**Comment by ozerovandrei** [comment]
It works on Selectel if you create a container manually via CLI and then create a listener after searching for that container via data source:

```sh
openstack secret create
openstack secret container create --name='SECRET_CONTAINER' --type='certificate' --secret="certificate=" --secret="private_key=" --secret="intermediates="
```

```hcl
data "openstack_keymanager_container_v1" "example" {
  name = "SECRET_CONTAINER"
}

resource "openstack_lb_listener_v2" "listener_1" {
  name                      = "https"
  protocol                  = "TERMINATED_HTTPS"
  protocol_port             = 443
  loadbalancer_id           = openstack_lb_loadbalancer_v2.lb_1.id
  default_tls_container_ref = data.openstack_keymanager_container_v1.example.container_ref
}
```

**Comment by dylanmtaylor** [comment]
Hello, I am hitting this issue on VMWare Integrated Openstack with Terraform 0.13.0 and the latest provider, v1.30.0. The resources can be created manually using the OpenStack CLI, including using TERMINATED_HTTPS but it doesn't look like the Terraform provider is calling the API in the way that OpenStack expects in order to add the secrets to the certificate container. By changing the container type to generic, the container is created, but the generic container can not be used with a load balancer in order to terminate HTTPS, only a certificate container can. If I create a certificate container manually outside of OpenStack and then get the container_ref using a data resource, it does in face work and create the listener, but this is not an acceptable solution, as the whole point of Terraform is to replace the need to use the CLI and handle all of our infrastructure as code.

**Comment by kayrus** [comment]
I submitted #1046. I think that permissive default ACLs is an acceptable security risk for a container resource.

**Comment by dylanmtaylor** [comment]
Thank you for the quick pull request, I will happily test that out.
