### ISSUE TITLE
Terraform openstack giving error for "openstack_networking_secgroup_rule_v2" for adding port -1

### ISSUE THREAD

**Issue by aratik711** [terraform-providers/terraform-provider-openstack#101]
Terraform openstack is throwing "Invalid syntax" error when we add "-1" as  port_range_min and  port_range_max for ICMP.

### Terraform Version
terraform version
Terraform v0.10.0

### Affected Resource(s)

openstack_networking_secgroup_rule_v2

### Terraform Configuration Files

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_test" {

  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = "-1"
  port_range_max    = "-1"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_compute_secgroup_v2.default_secgroup.id}"
}

Debug Output

terraform init

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.

### terraform apply

module.compute.instance.openstack_compute_floatingip_associate_v2.floating_ip_assoc: Creation complete (ID: 10.43.14.187/0e48f51d-6dc0-479d-9481-358e5f739dac/)
Error applying plan:

1 error(s) occurred:

* module.network.module.sg.openstack_networking_secgroup_rule_v2.secgroup_rule_test: 1 error(s) occurred:

* openstack_networking_secgroup_rule_v2.secgroup_rule_test: Invalid request due to incorrect syntax or missing required parameters.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior

The security rule should be added

### Actual Behavior

Terraform throws an error  Invalid request due to incorrect syntax or missing required parameters.

**Comment by fatmcgav** [comment]
@aratik711 If you're attempting to allow ICMP, then the correct rule is:

```
resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_test" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol = "icmp"
  port_range_min = "0"
  port_range_max = "0"
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_compute_secgroup_v2.default_secgroup.id}"
}
``` 

Alternatively if you want to allow 'all' ports, then it's `port_range_min = 1` & `port_range_max = 65535`.

Cheers

**Comment by aratik711** [comment]
@fatmcgav thanks let me give that a try.

**Comment by aratik711** [comment]
Another question though if I do something like this
resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_test" {

  count = "${length(compact(split(",", "")))}"
  direction         = "ingress"
  ethertype         = "IPv6"
  protocol          = "ipv6_icmp"
  remote_ip_prefix  = "::/0"
  security_group_id = "${openstack_compute_secgroup_v2.default_secgroup.id}"
}

Why does this open all traffic in openstack?

**Comment by fatmcgav** [comment]
@aratik711 Looking at the code, `port_range_min` and `port_range_max` are optional, so I suspect your OS cloud is enabling all ports if no restrictions are applied... 

Should be able to correlate by looking at the security group and security group rule in the Openstack CLI.

**Comment by aratik711** [comment]
So mentioning the protocol = "ipv6_icmp" does not make any difference, terraform would open all traffic even if I mention tcp/udp in protocol.

**Comment by fatmcgav** [comment]
@aratik711 TBH, I'm not sure on that one, as I've not played with IPv6 in Openstack yet... 

@jtopjian thoughts?

**Comment by jtopjian** [comment]
@aratik711 What do you mean by "all traffic"? Even TCP and UDP traffic?

Does this same behavior happen when you use the `openstack` or `neutron` command-line tool?

**Comment by jtopjian** [comment]
@aratik711 I apologize - I just re-read your message. "all traffic" was in reference to adding additional protocols.

When making ICMP rules for IPv6, you can still use the `icmp` protocol. `ipv6_icmp` is for the IPv6-specific ICMP types (like router advertisements and such). `icmp` still does ping and such. Using values of `0` for both min and max will allow all ICMP types. This is like `-1` for the `openstack_compute_secgroup_v2` resource. The Compute API and Networking API have some differences like this.

I've confirmed that the following example works:

```hcl
resource "openstack_networking_secgroup_v2" "test" {                  
  name = "test"                                                       
}                                                                     
                                                                      
resource "openstack_networking_secgroup_rule_v2" "test" {             
  direction = "ingress"                                               
  ethertype = "IPv6"                                                  
  protocol = "icmp"                                                   
  port_range_min = "0"                                                
  port_range_max = "0"                                                
  remote_ip_prefix = "::/0"                                           
  security_group_id = "${openstack_networking_secgroup_v2.test.id}"   
}                                                                     
                                                                      
resource "openstack_compute_instance_v2" "test" {                     
  name = "test"                                                       
  image_name = "Ubuntu 16.04"                                         
  flavor_name = "m1.small"                                            
  security_groups = ["${openstack_networking_secgroup_v2.test.name}"]                                                                    
}                                                                     
```

Let me know if this helps or if you're still seeing issues.

**Comment by jtopjian** [comment]
@aratik711 I'm going to close this issue as using `0` for the port range should solve this problem. However, if you're still seeing a problem, let us know and we can re-open this to discuss.
