### ISSUE TITLE
Support retrieving EC2 credentials

### ISSUE THREAD

**Issue by ninja-** [terraform-providers/terraform-provider-openstack#1016]
It would be nice to get support like when using CLI

```
openstack ec2 credentials create
```

This would allow to use S3-compatible API on Swift with proper credentials and inject the credentials into other parts of the project...

**Comment by kayrus** [comment]
@ninja- gophercloud supports ec2 credentials: https://pkg.go.dev/github.com/gophercloud/gophercloud@v0.11.0/openstack/identity/v3/extensions/ec2credentials?tab=doc
You can make a terraform resource following the application credentials resource code: https://github.com/terraform-providers/terraform-provider-openstack/blob/242ffd8f8b807092dbf8a53cff6b47f97cb0cc33/openstack/resource_openstack_identity_application_credential_v3.go

**Comment by ninja-** [comment]
Are you saying it's supported or just pointing me in direction on how to add support by modifying source code?

**Comment by kayrus** [comment]
@ninja- i'm pointing you to the direction to add the support following the similar code, which is already implemented.

**Comment by ninja-** [comment]
Alright, thanks

**Comment by kayrus** [comment]
@ninja- @ozerovandrei this issue can be closed

**Comment by ozerovandrei** [comment]
@ninja- `identity_ec2_credential` resource was added and it's available starting from the `1.31.0` release of the provider.
@pbasov thank you for implementing that.
