### ISSUE TITLE
openstack_networking_port_v2 not populating fixed_ip attribute

### ISSUE THREAD

**Issue by lblackstone** [terraform-providers/terraform-provider-openstack#103]
### Terraform Version
Terraform v0.10.4

### Affected Resource(s)
- openstack_networking_port_v2

### Terraform Configuration Files
```hcl
resource "openstack_compute_instance_v2" "foo" {
  name = "foo"
  image_name = "coreos-beta"
  flavor_name = "m1.small"
  network {
    port = "${openstack_networking_port_v2.foo-port.id}"
  }
}

resource "openstack_networking_network_v2" "foo-net" {
  name = "foo-net"
}

resource "openstack_networking_subnet_v2" "foo-subnet" {
  cidr = "192.168.0.0/24"
  network_id = "${openstack_networking_network_v2.foo-net.id}"
}

resource "openstack_networking_port_v2" "foo-port" {
  network_id = "${openstack_networking_network_v2.foo-net.id}"
  name = "foo-port"

  fixed_ip {
    subnet_id = "${openstack_networking_subnet_v2.foo-subnet.id}"
  }
}
```

### Debug Output
https://gist.github.com/lblackstone/8e77405d9de57a446cc47ea94f958073

### Expected Behavior
I expected the `fixed_ip.0.ip_address` attribute to be populated.

### Actual Behavior
Compare
```
"fixed_ip.#": "1",
"fixed_ip.0.ip_address": "",
```

with
```
"all_fixed_ips.#": "1",
"all_fixed_ips.0": "192.168.0.13",
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Source OpenStack credentials
2. Update image and flavor name to match test env values
3. `terraform apply`

**Comment by jtopjian** [comment]
@lblackstone Thanks for submitting this. It's a little confusing, but this is expected behavior. `fixed_ip` has some history to it:

https://github.com/hashicorp/terraform/pull/13056

`fixed_ip` is not computed and so it will only have values if you explicitly define them in the resource. If you specify static IPs, `fixed_ip` will reflect that.

Let me know if you have any questions or if you think something is incorrect here.

**Comment by lblackstone** [comment]
@jtopjian Thanks for clarifying. That behavior wasn't clear from the [docs](https://www.terraform.io/docs/providers/openstack/r/networking_port_v2.html#fixed_ip-1), so I wanted to check.

I opened a PR to clarify.
