### ISSUE TITLE
Deleting an ECS also deletes assoc ports which causes issues when destructive changes to an ECS are made

### ISSUE THREAD

**Issue by houst0n** [terraform-providers/terraform-provider-openstack#1030]
Hi there,

When making a change which requires a recreation of an ECS resource, if that ecs has an associated port then the port is deleted in a way that terraform is unaware of, and then when the ECS is recreated, tf tries to attach a port that no longer exists.

The only way to clean the state is to comment out the whole instance and do an apply, then uncomment. 

### Terraform Version
neilhouston:~/src/terraform/dev-devops$ terraform -v
Terraform v0.12.28
+ provider.opentelekomcloud v1.18.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_networking_port_v2
- opentelekomcloud_compute_instance_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_networking_port_v2" "net_ports" {
  for_each       = var.instances
  name           = each.value["name"]
  network_id     = each.value["network_id"]
  admin_state_up = "true"

  security_group_ids = [
    for sec in each.value["sec_groups"] :
    sec
  ]

  fixed_ip {
    subnet_id  = each.value["subnet_id"]
    ip_address = each.value["ip_address"]
  }
}

locals {
  port_map = {
    for port in opentelekomcloud_networking_port_v2.net_ports :
    port.name => port.id
  }
}

resource "opentelekomcloud_compute_instance_v2" "ecs_instances" {
  for_each          = var.instances
  name              = each.value["name"]
  key_pair          = each.value["keypair"]
  availability_zone = each.value["az"]

  flavor_name = each.value["flavour_name"]

  block_device {
    uuid                  = each.value["image_id"]
    source_type           = "image"
    volume_size           = each.value["sysdisk_size"]
    boot_index            = 0
    destination_type      = "volume"
    delete_on_termination = true
    volume_type           = each.value["voltype"]
  }

  network {
    port = local.port_map[each.value["name"]]
  }
  
}
```

### Expected Behavior
Deleting an ECS should have a flag (such as "delete_disks_on_termination" but maybe "delete_ports_on_termination") which allows us to choose if we want this to happen.

### Actual Behavior
Deleting an ECS always deletes these port objects. We don't care too much if they are deleted, however since terraform is unaware of the change it doesn't know to recreate them. So we constantly have to comment out instances, do an apply, and uncomment them...

**Comment by houst0n** [comment]
Doh. Wrong repo.. :/

**Comment by kayrus** [comment]
@houst0n just 2 cents from my side. Vanilla openstack nova doesn't remove the customized port, when a VM is removed. The issue you're talking about was fixed long time ago: https://bugs.launchpad.net/nova/+bug/1158684
