### ISSUE TITLE
When will you be making the 1.30.0 release?

### ISSUE THREAD

**Issue by neilfarmer** [terraform-providers/terraform-provider-openstack#1037]
Hi there,

I'm wondering when you will be releasing the next openstack provider release for 1.30.0?

The commit i am looking forward to is https://github.com/terraform-providers/terraform-provider-openstack/commit/6268fab6a30891481bb840eb70ffbce5aa07e3e8

This will be way more helpful than using local-exec to do it.

Thanks,

-Neil

**Comment by ozerovandrei** [comment]
Released!
