### ISSUE TITLE
Unexpected change of region in openstack_networking_router_v2

### ISSUE THREAD

**Issue by haxorof** [terraform-providers/terraform-provider-openstack#106]
### Terraform Version
0.10.4

### OpenStack Provider Version
0.2.1

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_router_v2

### Terraform Configuration Files
```hcl
data "openstack_networking_network_v2" "ext" {
  name = "ext-net"
}

resource "openstack_networking_router_v2" "edge_router" {
  name             = "edge-router"
  admin_state_up   = "true"
  external_gateway = "${data.openstack_networking_network_v2.ext.id}"
}
```
OpenStack provider information is only set in terraform, no environment OS prefixed variables are set.

### Expected Behavior
No changes. Infrastructure is up-to-date.

### Actual Behavior
Region change detected.
```
Terraform will perform the following actions:

-/+ openstack_networking_router_v2.edge_router (new resource required)
      id:               "aa395a08-e13b-4530-b2f2-b272aa6aa62b" => <computed>
      admin_state_up:   "true" => "true"
      distributed:      "false" => <computed>
      external_gateway: "3e4a9105-7b10-4186-a053-dc9373bba0f4" => "3e4a9105-7b10-4186-a053-dc9373bba0f4"
      name:             "edge-router" => "edge-router"
      region:           "Sto2" => ""
      tenant_id:        "184eb3766ac847aea2ad26f1a458e9f6" => <computed>


Plan: 1 to add, 0 to change, 1 to destroy.
``` 

### Steps to Reproduce
1. Execute `terraform apply`
2. Execute `terraform plan` and it will show you a change of the `region`, see output in "Actual Behavior" above.

### Possible fix
I have implemented a possible fix which I also tested towards an OpenStack cloud provider: 
- https://github.com/haxorof/terraform-provider-openstack/commit/dc3acb98f955c03ba844c42c2620937a4e1d4d08

**Comment by jtopjian** [comment]
wow - not sure how that one slipped by, but that's definitely the right fix. Feel free to open a PR :)

Thanks for catching this!

**Comment by haxorof** [comment]
No problem. Glad I could help 😄
