### ISSUE TITLE
Feature Request: Stop, don't destroy instance on user-data update

### ISSUE THREAD

**Issue by paulRbr** [terraform-providers/terraform-provider-openstack#123]
Hi there,

Similarly to the issue opened on the AWS provider (cf https://github.com/terraform-providers/terraform-provider-aws/issues/23) it would be nice to have a way to not destroy instances when changing `user_data`  content of a `openstack_compute_instance_v2` resource.

Indeed,  I see the use case where you would want to make a modification on future resources without impacting the currently running resources.

What do you folks think?

**Comment by jtopjian** [comment]
From reading the issue you linked, this sounds like a very debatable topic. Putting opinions aside, unless I'm mistaken, OpenStack does not allow user data to be updated after the instance has been created.

**Comment by paulRbr** [comment]
@jtopjian the fact that openstack doesn't allow user data to be updated is
a good point that I didn't check.

Maybe it would be nice to have a way (generally in terraform) to "mark"
some attributes of some resources to "notForceNew" on change.

Indeed it could make sense for some attributes that can influence only
"new" resources and not "old" ones.

WDYT?



Em 10/10/2017 18:57, "Joe Topjian" <notifications@github.com> escreveu:

From reading the issue you linked, this sounds like a very debatable topic.
Putting opinions aside, unless I'm mistaken, OpenStack does not allow user
data to be updated after the instance has been created.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/terraform-providers/terraform-provider-openstack/issues/123#issuecomment-335539744>,
or mute the thread

**Comment by jtopjian** [comment]
@paulRbr Yes, this should already be possible with the [`lifecycle`](https://www.terraform.io/docs/configuration/resources.html#lifecycle) parameter. Something like this should work:

```hcl
lifecycle {
  ignore_changes = ["user_data"]
}
```

But let me know if that either doesn't work or doesn't fit what you're looking for.

**Comment by fatmcgav** [comment]
@jtopjian Yeh, I was just going to suggest the same, as I've seen that referenced on here before.

Wish I'd seen it before I hand edited a state file to update md5 on several dozen hosts following a `user_data` change though...

**Comment by paulRbr** [comment]
@jtopjian thanks a lot for indication the `lifecycle` parameter! It's exactly what I needed.

I guess you answered this issue completely so I'll go ahead and close it.
