### ISSUE TITLE
openstack_networking_floatingip_v2 - Invalid input for field/attribute address

### ISSUE THREAD

**Issue by TinajaLabs** [terraform-providers/terraform-provider-openstack#133]
Terraform v0.10.7
terraform-provider-openstack_v0.2.2_x4

Seems I'm getting an error with the `address` value when I'm trying to define the association between a floating IP and an instance.

As part of a networking module I'm setting up the floating ip like this:
```
resource "openstack_networking_floatingip_v2" "floatip_main" {
  pool = "EXT_Corp" # existing pool
}
```

Then I create the association right after I create the instance like this:
```
resource "openstack_compute_floatingip_associate_v2" "floatip_main_assoc" {
  count       = "${var.floatip_address == "" ? 0 : 1}"   # create only if floatip_address is not empty
  floating_ip = "${var.floatip_address}"
  instance_id = "${openstack_compute_instance_v2.this.id}"
  fixed_ip    = "${openstack_compute_instance_v2.this.network.0.fixed_ip_v4}"
}
```

I define the `floatip_address` variable in the calling module like this:
```
floatip_address = "${module.networking.floatip_address}"
```

Finally, I'm creating `floatip_address` like this in the output of my network module:
```
output "floatip_address" {
  value = "openstack_networking_floatingip_v2.floatip_main.address"
}
```

Please see some of the debugging output below.

Thanks for any help,
Chris.

2017-10-25T00:27:40.045-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4:     "message": "Invalid input for field/attribute address. Value: openstack_networking_floatingip_v2.floatip_main.address. u'openstack_networking_floatingip_v2.floatip_main.address' is not valid under any of the given schemas"

2017-10-25T00:09:08.413-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4: 2017/10/25 00:09:08 [DEBUG] OpenStack Response Body: {
2017-10-25T00:09:08.413-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4:   "badRequest": {
2017-10-25T00:09:08.413-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4:     "code": 400,
2017-10-25T00:09:08.413-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4:     "message": "Invalid input for field/attribute address. Value: openstack_networking_floatingip_v2.floatip_main.address. u'openstack_networking_floatingip_v2.floatip_main.address' is not valid under any of the given schemas"
2017-10-25T00:09:08.413-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4:   }
2017-10-25T00:09:08.413-0700 [DEBUG] plugin.terraform-provider-openstack_v0.2.2_x4: }
2017/10/25 00:09:08 [ERROR] root.inst_go: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* openstack_compute_floatingip_associate_v2.floatip_main_assoc: Error associating Floating IP: Invalid request due to incorrect syntax or missing required parameters.
2017/10/25 00:09:08 [ERROR] root.inst_go: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

**Comment by jtopjian** [comment]
@TinajaLabs There are a few possible issues here.

The first is:

```
var.floatip_address
```

If I'm assuming correctly, you are explicitly defining a floating IP address. The problem is that when you do:

```hcl
resource "openstack_networking_floatingip_v2" "floatip_main" {
  pool = "EXT_Corp" # existing pool
}
```

You will most likely not get that same floating IP address. So if you have `var.floatip_address` set to "192.168.1.30" but `openstack_networking_floatingip_v2.floatip_main.address` ends up being "192.168.1.40", the association will fail.

In short: it is not possible to tell OpenStack _exactly_ what floating IP you want. You can define static _fixed_ IPs, but not floating IPs. Floating IPs are "here's a random IP, have a nice day".

Now, let's say by coincidence `var.floatip_address` coincidentally matched what `openstack_networking_floatingip_v2.floatip_main.address` was. Then technically the association should work, but here's where I think the second problem is coming in:

```hcl
resource "openstack_compute_floatingip_associate_v2" "floatip_main_assoc" {
  count       = "${var.floatip_address == "" ? 0 : 1}"   # create only if floatip_address is not empty
  floating_ip = "${var.floatip_address}"
  instance_id = "${openstack_compute_instance_v2.this.id}"
  fixed_ip    = "${openstack_compute_instance_v2.this.network.0.fixed_ip_v4}"
}
```

Notice how the above resource does not refer to `openstack_networking_floatingip_v2.floatip_main`. Because of this, Terraform will run _both_ `openstack_compute_floatingip_associate_v2` and `openstack_networking_floatingip_v2` in parallel. So the association is happening before the floating IP was even created.

You can do two things to resolve this:

```hcl
// explicit dependency
resource "openstack_compute_floatingip_associate_v2" "floatip_main_assoc" {
  floating_ip = "${var.floatip_address}"
  instance_id = "${openstack_compute_instance_v2.this.id}"
  fixed_ip    = "${openstack_compute_instance_v2.this.network.0.fixed_ip_v4}"

  depends_on = ["openstack_networking_floatingip_v2.floatip_main"]
}

// implicit dependency
resource "openstack_compute_floatingip_associate_v2" "floatip_main_assoc" {
  floating_ip = "${openstack_networking_floatingip_v2.floatip_main.address}"
  instance_id = "${openstack_compute_instance_v2.this.id}"
  fixed_ip    = "${openstack_compute_instance_v2.this.network.0.fixed_ip_v4}"
}
```

Let me know if this helps.

**Comment by TinajaLabs** [comment]
@jtopjian.

Thank you for the thoughtful response.

Part of what I may be working against is that I'm using "modules".  When I try to refer to `openstack_networking_floatingip_v2` in my instance module, it seems to have no idea how to reference it.

An overview of my structure (close enough and note plural and singular convention):
Root modules:
- `0-provisioning.tf`
- `1-networking.tf` (source = `../modules/network.tf`)
- `2-security-groups.tf` (source = `../modules/securitygroup.tf`)
- `3-instances.tf` (source = `../modules/instance.tf`)

Process:
- I create each individual instance in `../modules/instance.tf` - called from `instances.tf`
- I create the `floatip_main` resource in `../modules/network.tf ` - called from `networking.tf`
- I create the `floatip_main_assoc` right after I create each specific instance (in `../modules/instance.tf`) - BUT only if count > 0  (which, for now, only applies to one host)


Given that structure, I used an output from `../modules/network.tf ` to define a variable I could reference in `../modules/instance.tf` like this:
```
output "floatip_address" {
  value = "openstack_networking_floatingip_v2.floatip_main.address"
}
```

In my `instances.tf' module I create an attribute, floatip_address, which is passed into `../modules/instance.tf` for each instance definition like this:
```
floatip_address = "${module.networking.floatip_address}"
```

I will experiment with your suggestions, but I'll be surprised if I can reference, 'openstack_networking_floatingip_v2.floatip_main' from `../modules/instance.tf`.   I'm guessing you described as an example.

Again, thanks for your help,
Chris.

**Comment by jtopjian** [comment]
All of that makes sense. And you're correct, using an output is the way to go. I was assuming your original config was in a single tf file.

You can see some extra debug information by doing:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

Note the `OS_DEBUG` flag - that will cause the actual API traffic to print, which can usually help pinpoint where a problem is.

**Comment by TinajaLabs** [comment]
Yep.  That's how I generated the debug info in the first post.  It points to a problem with the attribute, `address`:
```
Invalid input for field/attribute address
openstack_networking_floatingip_v2.floatip_main.address' is not valid under any of the given schemas
```

Thanks,
Chris.

**Comment by TinajaLabs** [comment]
OK.  I have discovered the problem and the problem is me.  Here is the offending code:
```
output "floatip_address" {
  value = "openstack_networking_floatingip_v2.floatip_main.address"
}
```

`Terraform plan` output helped me see the error of my ways:
```
Terraform will perform the following actions:

  + module.inst_go.openstack_compute_floatingip_associate_v2.floatip_main_assoc
      id:          <computed>
      fixed_ip:    "192.168.144.12"
      floating_ip: "openstack_networking_floatingip_v2.floatip_main.address" <== should be an ip address, not the name of the resource attribute
      instance_id: "56521c6d-a956-4fed-ac84-e1bb9dbefaaf"
      region:      <computed>
```

I have forgotten to include the `${}` to define the resource as a **variable**.

The correct syntax should be:
```
output "floatip_address" {
  value = "${openstack_networking_floatingip_v2.floatip_main.address}"  # <---------
}
```

Apologies for wasting your time, Joe.

**Comment by jtopjian** [comment]
> Apologies for wasting your time, Joe.

haha - no waste at all. Glad you spotted the error! I looked over your code a few times and never saw it, either :smile:
