### ISSUE TITLE
trove support

### ISSUE THREAD

**Issue by eugenetaranov** [terraform-providers/terraform-provider-openstack#141]
Hello,

I would like to send a few pull requests adding support for trove, but got questions about acceptance tests: 
- is there a quick guid how to run it on devstack?
- would it be possible to run acceptance tests on your side?

Thanks you

**Comment by jtopjian** [comment]
@eugenetaranov Thank you for offering.

Do you have an existing Trove environment you can use? If so, you can run acceptance tests on that environment.

There's some basic documentation about acceptance tests at the bottom of this page:

https://www.terraform.io/docs/providers/openstack/index.html

There's some more information here:

https://github.com/gophercloud/gophercloud/tree/master/acceptance

I wrote the series of blog posts linked in the above page specifically for Gophercloud testing (which Terraform is compatible with).

To run the Terraform acceptance tests, make sure you have the required environment variables set and then run:

```shell
$ cd ~/go/src/github.com/terraform-providers/terraform-provider-openstack/
$ TF_LOG=DEBUG make testacc TEST=./openstack TESTARGS="-run=TestAccComputeV2Instance_basic"
```

Where `TestAccComputeV2Instance_basic` is a test defined in one of the `*_test.go` files.

The above test is safe to run in a production OpenStack cloud if you wanted to try it out.

If you have problems running the tests, I can certainly run them on my side, though the caveat is that development of the resources will take a little longer.

**Comment by eugenetaranov** [comment]
@jtopjian thank you for provided instructions, it helped a lot. I got acceptance tests running on production openstack but there was a minor hiccup: TestAccComputeV2Instance_basic fails with "Multiple possible networks found, use a Network ID to be more specific" error, I fixed by specifying network `network { uuid = "..." }`
But for some reason it worked okay with packstack (without network being specified). Do you think it is something that needs to be fixed? If so, I will send a PR.

**Comment by jtopjian** [comment]
@eugenetaranov There are usually two causes of this:

1. You're running the tests as the "admin" user. The tests should be run by the "demo" user. There are some tests which require the admin user -- they're just skipped for now.
2. Your demo user has multiple networks, possibly ones that existed before the testing or some which were not cleaned up after testing.

Let me know if this helps.

**Comment by eugenetaranov** [comment]
Hi @jtopjian , thanks for explanation, it was #2 in my case: got several networks in my account.

**Comment by jtopjian** [comment]
@eugenetaranov I wanted to touch base about this resource. Do you think you'll be able to finish the `openstack_db_instance_v1` resource in the next day or two? If not, that's OK and there is _no_ rush. We can have a new release made and the rest of the changes will be included in the next release.

**Comment by eugenetaranov** [comment]
@jtopjian let's proceed without them, will add new resources before next release

**Comment by eugenetaranov** [comment]
Closing
