### ISSUE TITLE
feature request: add a field to LB operations to allow use of Octavia

### ISSUE THREAD

**Issue by jrperritt** [terraform-providers/terraform-provider-openstack#147]
Currently, all the LB operations go through Neutron. This bug is for enabling the ability to optionally provide a value (I was thinking just a `use_octavia` key that took a `bool`) to the `*_openstack_lb_*_v2` resources that would, instead of creating a Neutron service client, create an Octavia service client to make the calls. If that sounds reasonable, I'll submit a PR for this.

cc @jtopjian

**Comment by jtopjian** [comment]
Sorry - I totally missed this one yesterday. At first read, this makes sense. I'll have some time to read this over soon.

**Comment by jrperritt** [comment]
No worries, I'm still fumbling over the implementation, which _should be_ simple.

**Comment by jtopjian** [comment]
Implemented in #149
