### ISSUE TITLE
openstack_compute_secgroup_v2 doesn't export ID

### ISSUE THREAD

**Issue by cintiadr** [terraform-providers/terraform-provider-openstack#158]
### Terraform Version
Terraform v0.11.0
terraform-provider-openstack_v1.0.0_x4

### Affected Resource(s)
openstack_compute_secgroup_v2 
openstack_networking_secgroup_v2  (data)

### Expected Behavior
openstack_compute_secgroup_v2 should export ID of newly created resource. 

### Actual Behavior
There's no ID or similar on that resource attributes

### Important Factoids
Maybe this is my openstack ignorance, but in my provider, when I do a <openstack security group list>, each security group has an internal ID. 

I only seem to be able to this internal ID in the 'from_group_id' rules arguments. Attempting to use names just return errors: 'Invalid request due to incorrect syntax or missing required parameters.'

As I'd want to generate both the remote and local groups using terraform, I'd like to be able to reference those IDs.

**Comment by jtopjian** [comment]
@cintiadr Every resource in terraform has an `id` field. For the `openstack_compute_secgroup_v2` resource, referencing `openstack_compute_secgroup_v2.resource_name.id` is probably what you're looking for.

Also, unless you're running on an older OpenStack environment, I recommend using the `openstack_networking_secgroup_v2` resource instead. Managing security groups through the Compute API has been deprecated in OpenStack.

If you're still having problems, can you provide the Terraform configuration you're using?

**Comment by cintiadr** [comment]
Well, I suppose that hindsight is 20/20 and I should have known that from the other resources :D

But I didn't realise there were two ways of creating security groups in openstack. Would it make sense to put a warning at the top of the documentation page in terraform?

**Comment by jtopjian** [comment]
> Would it make sense to put a warning at the top of the documentation page in terraform?

It sure would. :)

I've opened #159 to address this.

**Comment by cintiadr** [comment]
Thank you!!
