### ISSUE TITLE
Openstack flavor - metadata not supported

### ISSUE THREAD

**Issue by shurkaxaa** [terraform-providers/terraform-provider-openstack#165]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
ubuntu@controller:~/terraform$ ./terraform -v
Terraform v0.11.0
+ provider.openstack v1.0.0

### Affected Resource(s)
- openstack_compute_flavor_v2

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Expected Behavior
It should be possible to specify metadata for flavors. Similar to metadata tags for instance.

### Actual Behavior
It is not possible to specify metadata for flavor resources

### Important Factoids
Openstack Ocata is used on Ubuntu Xenial.

**Comment by jtopjian** [comment]
Correct - this is not supported at this time. Support for flavor extra specs (metadata) needs to first be added to Gophercloud. There's some information here about the progress:

https://github.com/gophercloud/gophercloud/issues/540
