### ISSUE TITLE
Some LB resource requests need a Neutron client

### ISSUE THREAD

**Issue by jrperritt** [terraform-providers/terraform-provider-openstack#171]
In the PR to allow the use of Octavia, the LB V2 resources were changed to use either the Octavia or Neutron service client for requests. However, some of the calls use the `ports` package, which should use the Neutron client regardless of the LB client. Example:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_lb_loadbalancer_v2.go#L178

I'll send a fix for this.

**Comment by jtopjian** [comment]
Fixed in #172
