### ISSUE TITLE
Provide router external gateway information as attribute

### ISSUE THREAD

**Issue by louis-gounot** [terraform-providers/terraform-provider-openstack#175]
Hello,

Currently, openstack_networking_router_v2 resource does not provide external gateway information back in attributes.
It is required to get this information if we want to setup a static route between 2 routers connected to an external network.

Would it be possible to implement this attribute ?

Regards

**Comment by fatmcgav** [comment]
@louis-gounot Currently it looks like the `external_gateway_info` attribute is [provided](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_router_v2.go#L54-L58), which gets set to the `network_id`. 

Are you after the `external_fixed_ips` details, as defined here: https://developer.openstack.org/api-ref/network/v2/index.html#routers-routers?

**Comment by louis-gounot** [comment]
@fatmcgav Yes, I would like to have access to the whole external_gateway_info object from OpenStack router API (`network_id`, `enable_snat` and `external_fixed_ips`). Actually, only `external_fixed_ips` is missing.

**Comment by fatmcgav** [comment]
@louis-gounot Yeh, so it looks like Gophercloud supports the entire `external_gateway_info` [block](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/layer3/routers/results.go#L10-L14).

So just need to come up with a sensible means of exposing that info from Terraform. 
`enable_snat` has been added as a top-level config item, however feels like we should possibly restructure to mirror the `external_gateway_info` struct?
@jtopjian thoughts?

**Comment by jtopjian** [comment]
The reason `openstack_networking_router_v2` seems out of sync is because `ExternalFixedIPs` and `EnableSNAT` were only added to Gophercloud in the past 2-3 months.

After looking this over, I think the best option is to create a new resource called `openstack_networking_router_gateway_v2`. The existing `enable_snat` and `external_gateway` (which is kind of named incorrectly) fields in the `openstack_networking_router_v2` resource would be deprecated and eventually removed.

comments / objections?

**Comment by jtopjian** [comment]
Actually, investigating this more, a `openstack_networking_router_gateway_v2` resource might be overkill. I think adding `external_fixed_ips` as a top-level argument might be the easiest way.

I'm also going to look at renaming `external_gateway` to `network_id`.

**Comment by jtopjian** [comment]
I've opened #178 to address this.

@louis-gounot If you're able to test this, do let us know if you have any problems or suggestions. :)

**Comment by louis-gounot** [comment]
@jtopjian Thanks a lot for this quick answer.
I need to setup a GO dev envrionment a build the provider. Should be able to do it by next week.
I'll come back to you as soon as I will have done it.

**Comment by louis-gounot** [comment]
Very simple test (just create a router connected to an external net, plan, apply, show, destroy).
It is working well.
If I keep `external_gateway` instead of `external_network_id`, I have a deprecation warning, but it is still working. Following example is using `external_network_id`

```
$ cat test.tf
provider "openstack" {
  insecure = true
}

resource "openstack_networking_router_v2" "test" {
  name = "test"
  external_network_id = "3170ce9b-1af7-4044-ab04-203f6ca357ec"
}
```

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + openstack_networking_router_v2.test
      id:                  <computed>
      admin_state_up:      <computed>
      distributed:         <computed>
      enable_snat:         <computed>
      external_fixed_ip.#: <computed>
      external_gateway:    <computed>
      external_network_id: "3170ce9b-1af7-4044-ab04-203f6ca357ec"
      name:                "test"
      region:              <computed>
      tenant_id:           <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + openstack_networking_router_v2.test
      id:                  <computed>
      admin_state_up:      <computed>
      distributed:         <computed>
      enable_snat:         <computed>
      external_fixed_ip.#: <computed>
      external_gateway:    <computed>
      external_network_id: "3170ce9b-1af7-4044-ab04-203f6ca357ec"
      name:                "test"
      region:              <computed>
      tenant_id:           <computed>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

openstack_networking_router_v2.test: Creating...
  admin_state_up:      "" => "<computed>"
  distributed:         "" => "<computed>"
  enable_snat:         "" => "<computed>"
  external_fixed_ip.#: "" => "<computed>"
  external_gateway:    "" => "<computed>"
  external_network_id: "" => "3170ce9b-1af7-4044-ab04-203f6ca357ec"
  name:                "" => "test"
  region:              "" => "<computed>"
  tenant_id:           "" => "<computed>"
openstack_networking_router_v2.test: Creation complete after 8s (ID: e7aa87c9-ebf8-48ce-88bf-0a54713deced)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

```
$ terraform show
openstack_networking_router_v2.test:
  id = e7aa87c9-ebf8-48ce-88bf-0a54713deced
  admin_state_up = true
  distributed = false
  enable_snat = true
  external_fixed_ip.# = 1
  external_fixed_ip.0.ip_address = 10.252.102.34
  external_fixed_ip.0.subnet_id = 0cac9700-13f8-4b84-80a4-170e2e70f3c7
  external_gateway = 3170ce9b-1af7-4044-ab04-203f6ca357ec
  external_network_id = 3170ce9b-1af7-4044-ab04-203f6ca357ec
  name = test
  region = regionOne
  tenant_id = 1ed7fee7ba9642bd9d5903d0ec55957d
```

```
$ terraform destroy
openstack_networking_router_v2.test: Refreshing state... (ID: e7aa87c9-ebf8-48ce-88bf-0a54713deced)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - openstack_networking_router_v2.test


Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

openstack_networking_router_v2.test: Destroying... (ID: e7aa87c9-ebf8-48ce-88bf-0a54713deced)
openstack_networking_router_v2.test: Still destroying... (ID: e7aa87c9-ebf8-48ce-88bf-0a54713deced, 10s elapsed)
openstack_networking_router_v2.test: Destruction complete after 11s

Destroy complete! Resources: 1 destroyed.
$ cat test.tf
provider "openstack" {
  insecure = true
}

resource "openstack_networking_router_v2" "test" {
  name = "test"
  external_network_id = "3170ce9b-1af7-4044-ab04-203f6ca357ec"
}
```

Thanks a lot, waiting the release (I have a weird workaround with an external data source to fecth the IP at the moment).

**Comment by louis-gounot** [comment]
By the way, I'm using OpenStack Newton release (if anyone has issues with previous releases).

**Comment by fatmcgav** [comment]
@louis-gounot Cheers for the quick test... 

The deprecation notice but still functional behaviour with `external_gateway` is to be expected. This allows any existing users of that field to update their code instead of just breaking shiz :)

**Comment by louis-gounot** [comment]
@fatmcgav Yes, this is great that it is not breaking anything. I mentionned it for you to be sure it is the case. If you need it, I can provide execution traces with the deprecation warning.

**Comment by fatmcgav** [comment]
@louis-gounot No, that's fine, just wanted to clarify :)

**Comment by jtopjian** [comment]
Closing as this has been implemented. Thank you both for your help with this.
