### ISSUE TITLE
connect to keystone failed

### ISSUE THREAD

**Issue by mlabarre** [terraform-providers/terraform-provider-openstack#184]
Hello
I works with devstack, tectonic and thus terraform.
During plan phase (terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/openstack/neutron, an attempt is done to keystone identidy.
OS_AUTH_URL and auth_url (in main.tf) are set to 'http://192.168.1.1:80/identity' (service is ok).
When I run the command `terraform plan -var-file=build/${CLUSTER}/terraform.tfvars platforms/openstack/neutron`
I have the error `'* provider.openstack: invalid character '<' looking for beginning of value'`
This is because terraform contact keystone with URL 'http://192.168.1.1/' and so the response is a 302 and then the login page of horizon dashboard.
How OS_AUTH_URL or auth_url are handled ? I changed auth_url from 'http://192.168.1.1:80/identity' to 'http://10.10.10.10:80/identity' and I have a connection failed (ok because 10.10.10.10 does not exists). So, the variable auth_url is used but it seems that URI is ignored (/identity)?
Can you help me.
Many thanks

**Comment by jtopjian** [comment]
@mlabarre I'm not familiar with Tectonic, but I think this might be related:

https://github.com/gophercloud/gophercloud/issues/609

**Comment by mlabarre** [comment]
Error is in the url by itself. vendor/github.com/gophercloud/gophercloud/openstack/client.go is very basic. It does not consider URL as a V2 by default as expected. So If I suffix url with '/v3' (or v2) it works.
Thank you
