### ISSUE TITLE
terraform provider openstack is ignoring NO_PROXY env variable

### ISSUE THREAD

**Issue by hurdigurdi** [terraform-providers/terraform-provider-openstack#202]
Hello,

the terraform openstack provider has been adjusted to make use of http(s)_proxy environment variables (see [GH-8735](https://github.com/hashicorp/terraform/issues/8735))

In our environment, we do rely on http_proxy in combination with an proxy exception list defined via NO_PROXY

(e.g. NO_PROXY='my-corp-auth.server')

Manually un-setting http(s)_proxy env vars for terraform calls and resetting them afterwards is a possible workaround.

Using the openstack client, connections are working perfectly fine using the proxy configuration explained above. openstack client seems to evaluate NO_PROXY

Could you please look into evaluating the NO_PROXY environment variable?

### Terraform Version
Terraform v0.11.1
provider.openstack v1.1.0

affects all calls to terraform using openstack which authenticate against the provider (*terraform.EvalConfigProvider)

### Debug Output
https://gist.github.com/hurdigurdi/5aa731969babfc4a11d88b20184bd116

### Expected Behavior
terraform plan output

### Actual Behavior
HTTP error 503 - Service Unavailable due to ignored NO_PROXY list in env variable

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. export http_proxy=myproxy:8080
2. export NO_PROXY=my-corp.auth.server
3. terraform init # succeeds
4. terraform plan

### References
- [GH-8735](https://github.com/hashicorp/terraform/issues/8735)

**Comment by jtopjian** [comment]
@hurdigurdi I apologize for the late reply about this.

As far as I can tell, the OpenStack provider is configured correctly to read the `NO_PROXY` environment variable. You can see here that it's using the `http.ProxyFromEnvironment` function:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L151

The `http.ProxyFromEnvironment` function calls `useProxy` here:

https://golang.org/src/net/http/transport.go?s=9950:10007#L280

And `useProxy` evaluates if `NO_PROXY` is set:

https://golang.org/src/net/http/transport.go?s=9950:10007#L1210

Is it possible this is a bug with Go when it's trying to parse the domain you have set in `NO_PROXY`?

**Comment by jtopjian** [comment]
I'm going to close this since there hasn't been further discussion, but I can re-open this if others report the same problem.

**Comment by lz006** [comment]
same issue here
