### ISSUE TITLE
openstack_networking_subnet_v2: dns nameservers order is not preserved

### ISSUE THREAD

**Issue by yanndegat** [terraform-providers/terraform-provider-openstack#225]
The order of the dns nameservers given as input is not preserved by the resource, thus
breaking the dns order consistency that user shall expect 
see: https://docs.openstack.org/neutron/pike/contributor/internals/dns_order.html

### Terraform Version
Terraform v0.11.1
+ provider.ignition v1.0.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.openstack v1.1.0
+ provider.ovh v0.2.0
+ provider.template v1.0.0
+ provider.tls v1.0.1

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_subnet_v2:

Schema type TypeSet is to be blamed:
"dns_nameservers": &schema.Schema{
				Type:     schema.TypeSet,
				Optional: true,
				ForceNew: false,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Set:      schema.HashString,
			},

hcl
```
 resource "openstack_networking_subnet_v2" "subnet" {

   name       = "testdns_order_subnet}"
   network_id = "${var.network_id}"
   cidr       = "${var.subnet_cidr}"
   ip_version = 4
   no_gateway = true

   dns_nameservers = ["10.0.16.4", "213.186.33.99"]
}
```

output:
neutron subnet-show b74ebf81-42fe-4add-bc7f-8ffdbbfd227a                                                                                             ✘ 1
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
+-------------------+------------------------------------------------------+
| Field             | Value                                                |
+-------------------+------------------------------------------------------+
| allocation_pools  | {"start": "10.0.48.2", "end": "10.0.63.254"}         |
| cidr              | 10.0.48.0/20                                         |
| created_at        | 2018-01-16T14:33:23Z                                 |
| description       |                                                      |
| dns_nameservers   | 213.186.33.99                                        |
|                   | 10.0.16.4                                            |
| enable_dhcp       | True                                                 |

Expected output
neutron subnet-show b74ebf81-42fe-4add-bc7f-8ffdbbfd227a                                                                                             ✘ 1
neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
+-------------------+------------------------------------------------------+
| Field             | Value                                                |
+-------------------+------------------------------------------------------+
| allocation_pools  | {"start": "10.0.48.2", "end": "10.0.63.254"}         |
| cidr              | 10.0.48.0/20                                         |
| created_at        | 2018-01-16T14:33:23Z                                 |
| description       |                                                      |
| dns_nameservers   | 10.0.16.4                                        |
|                   | 213.186.33.99                                            |
| enable_dhcp       | True                                                 |

**Comment by jtopjian** [comment]
Fixed by #226 

Thanks you, @yanndegat !
