### ISSUE TITLE
allowed_address_pairs misbehaving in v1.2.0

### ISSUE THREAD

**Issue by michalmedvecky** [terraform-providers/terraform-provider-openstack#232]
Since provider v1.2.0, terraform started to unnecessarily update allowed_address_pairs every `apply`.

### Terraform Version

any (0.10.8+)

### Openstack provider version

v1.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_port_v2

### Terraform Configuration Files
```hcl
resource "openstack_networking_port_v2" "port" {
  name = "addresspairtest${count.index}"
  count = "2"
  admin_state_up = "true"
  network_id = "${data.openstack_networking_network_v2.my-net.id}"
  allowed_address_pairs = {
    ip_address = "1.2.3.4"
  }
}

resource "openstack_compute_instance_v2" "instance" {
  count = "2"
  name = "addresspairstest${count.index}"
  image_id = "66ae409c-f2ea-4a8c-a25c-3859d79f9f33"
  flavor_name = "m1.tiny2"
  key_pair = "misko"
  availability_zone = "sec"

  network {
    port = "${openstack_networking_port_v2.port.*.id[count.index]}"
  }
}
```

### Expected Behavior
No change

### Actual Behavior

Every `apply`, these unnecessary changes are generated (and applied):

```
  ~ openstack_networking_port_v2.port[0]
      allowed_address_pairs.2856086191.ip_address:  "" => "1.2.3.4"
      allowed_address_pairs.2856086191.mac_address: "" => <computed>
      allowed_address_pairs.3695943865.ip_address:  "1.2.3.4" => ""

  ~ openstack_networking_port_v2.port[1]
      allowed_address_pairs.1638549129.ip_address:  "1.2.3.4" => ""
      allowed_address_pairs.2856086191.ip_address:  "" => "1.2.3.4"
      allowed_address_pairs.2856086191.mac_address: "" => <computed>
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create .tf files as shown above
2. `terraform apply`
3. `terraform apply` again

### Important factoids

Downgrading provider to v1.1.0 results in proper behavior.

**Comment by jtopjian** [comment]
Yep, confirmed bug which was introduced in #168. We'll have to see if there's another way to support the use-case that #168 tried to solve.
