### ISSUE TITLE
Conflict with environment variables in a data source

### ISSUE THREAD

**Issue by xocasdashdash** [terraform-providers/terraform-provider-openstack#253]
### Terraform Version
Terraform v0.11.3
+ provider.null v1.0.0
+ provider.openstack v1.2.0
+ provider.template v1.0.0

### Affected Resource(s)
data "openstack_networking_subnet_v2"

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "openstack_networking_subnet_v2" "public_subnet" {
  subnet_id = "AN_EXISTING_PUBLIC_SUBNET_OUTSIDE_TENANT"
}
output "p" {
  value = "${data.openstack_networking_subnet_v2.public_subnet.*.id}"
}

```

### Debug Output
-

### Expected Behavior
It shouldn't fail to find this existing subnet.
### Actual Behavior
Because i have setup OS_TENANT_ID it's getting added as a filter even tough i'm not specifying it in the tf configuration. I believe the issue would be fixed if the multi values here where removed https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/data_source_openstack_networking_subnet_v2.go#L48-L57

I think shouldn't be considered a breaking change because in no documentation this behaviour is specified as the expected one.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

**Comment by jtopjian** [comment]
@xocasdashdash Ah, good catch. I can see this as being an issue. I'll think about a solution to this, but I believe your suggestion is most likely the correct approach here.

Thank you for reporting this.

**Comment by xocasdashdash** [comment]
I just checked and the same thing is happening with https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/data_source_openstack_networking_network_v2.go#L42-L49

Are you open to me doing a PR about this? seems easy to do and I'll love to help

**Comment by jtopjian** [comment]
@xocasdashdash Sure, you can submit a PR for this. Thanks 😄
