### ISSUE TITLE
Prune the destroy graph

### ISSUE THREAD

**Issue by Lasering** [terraform-providers/terraform-provider-openstack#255]
I have a terraform recipe using `openstack_networking_secgroup_v2` and `openstack_networking_secgroup_rule_v2`. And I have a lot of rules (about 100 rules). Whenever I ask terraform to destroy my infrastructure it will dutifully destroy every rule, one by one, and then it will destroy the security group.

If the end result is to destroy the entire security group then its pointless to destroy each rule individually. Or in other words the following optimization could be made:

1. Inspect the destroy graph to see if it includes a node to destroy a security group.
2. Remove from the graph all the nodes that would destroy rules from that security group.

**Comment by jtopjian** [comment]
@Lasering Thank you for the thoughts.

Since this is more of a design request for the Terraform graph, I would recommend opening an issue at https://github.com/hashicorp/terraform/ or maybe starting a discussion on the mailing list.

**Comment by Lasering** [comment]
See the [comment I left on the terraform repo](https://github.com/hashicorp/terraform/issues/17505#issuecomment-436674984) for a possible workaround.

**Comment by jtopjian** [comment]
Since this has been opened and acknowledged at https://github.com/hashicorp/terraform/issues/17505, I'm going to close this here.
