### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by CamelCaseNotation** [terraform-providers/terraform-provider-openstack#263]
https://github.com/terraform-providers/terraform-provider-openstack/blob/e1d5b9f10baf0d913bda31b74e4d457d3d7e0e81/openstack/compute_instance_v2_networking.go#L432

This line is causing a simple Terraform configuration I have to deploy an instance to fail. Will the `InstanceNICs` field of the `instanceAddresses` struct always have one NIC? Or is it supposed to? What would happen if you checked to see if the len was 0 and set that parameter to something empty?

**Comment by fatmcgav** [comment]
@CamelCaseNotation Are you able to provide a log output with Openstack debugging enabled?
`TF_LOG=debug OS_DEBUG=1 terraform apply ...`

Be sure to remove any sensitive info...

**Comment by jtopjian** [comment]
@fatmcgav beat me to it - was in the process of commenting, too 😄 

@CamelCaseNotation I've never come across an OpenStack environment where the instance would not have a NIC. However, I'm sure it's possible.

What's strange about you hitting that line of code is that your instance has network information, or else it would have never reached here:

https://github.com/terraform-providers/terraform-provider-openstack/blob/e1d5b9f10baf0d913bda31b74e4d457d3d7e0e81/openstack/compute_instance_v2_networking.go#L427

As Gav mentioned, the `OS_DEBUG` info will really help us understand the crash here.

**Comment by CamelCaseNotation** [comment]
Here's a Gist! Let me know if I missed anything real important! https://gist.github.com/CamelCaseNotation/faad231f09808850140d778665fca717

**Comment by jtopjian** [comment]
@CamelCaseNotation Was the above generated with the `OS_DEBUG` environment variable set?

**Comment by CamelCaseNotation** [comment]
Oh I think this was with `OS_LOG=1` or whatever was on the documentation
page for openstack provider from Terraform's website. I'll run it again
with that env set but it'll be a while

**Comment by jtopjian** [comment]
@CamelCaseNotation No rush - take your time :)

Note that there are two environment variables needed:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

It's a little confusing - sorry about that.

**Comment by CamelCaseNotation** [comment]
I ran that and it gave me the same output, but would you like a larger picture of the logs?

**Comment by jtopjian** [comment]
We're looking for output like the following:

```
2018/03/12 15:15:50 [DEBUG] OpenStack Request URL: GET http://localhost:8774/v2/5aa69d9135524fddab887759f3b6c92d/servers/61133075-d584-4f0a-93d8-8a2f5bfa7ad9
2018/03/12 15:15:50 [DEBUG] OpenStack request Headers:
Accept: application/json
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
2018/03/12 15:15:51 [DEBUG] OpenStack Response Code: 200
2018/03/12 15:15:51 [DEBUG] OpenStack Response Headers:
Content-Length: 1572
Content-Type: application/json
Date: Mon, 12 Mar 2018 15:15:51 GMT
X-Compute-Request-Id: req-ec9b318d-4fce-46f4-a101-670aaa923448
X-Openstack-Request-Id: req-ec9b318d-4fce-46f4-a101-670aaa923448
2018/03/12 15:15:51 [DEBUG] OpenStack Response Body: {
  "server": {
    "OS-DCF:diskConfig": "MANUAL",
    "OS-EXT-AZ:availability_zone": "nova",
    "OS-EXT-STS:power_state": 1,
    "OS-EXT-STS:task_state": null,
    "OS-EXT-STS:vm_state": "active",
    "OS-SRV-USG:launched_at": "2018-03-12T15:15:49.000000",
    "OS-SRV-USG:terminated_at": null,
    "accessIPv4": "",
    "accessIPv6": "",
    "addresses": {
      "private": [
        {
          "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:cd:b6:11",
          "OS-EXT-IPS:type": "fixed",
          "addr": "10.0.0.8",
          "version": 4
        }
      ]
    },
...
```

The "server" output (truncated above) is most important here for the problem you're seeing.

Be sure to censor any sensitive information, though.

**Comment by jtopjian** [comment]
I believe the core cause of this was identified in https://github.com/terraform-providers/terraform-provider-openstack/pull/539.

I'm going to close this issue, but if this turns out to still be a problem, please let me know.
