### ISSUE TITLE
OS_DOMAIN_* values incorrectly used

### ISSUE THREAD

**Issue by Adrian-Turjak** [terraform-providers/terraform-provider-openstack#275]
This provider currently does not source the domain values in openstack correctly and then pass them along to gophercloud.

The values as they exists in the official libraries are:
```
# Who the user is:
OS_USERNAME
OS_USER_ID
# what domain the user is in:
OS_USER_DOMAIN_NAME
OS_USER_DOMAIN_ID

# what the project scope is:
OS_PROJECT_NAME
OS_PROJECT_ID
# what the domain for the project is
OS_PROJECT_DOMAIN_NAME
OS_PROJECT_DOMAIN_ID

# what the domain scope is (mutually exclusive with project scope)
OS_DOMAIN_NAME
OS_DOMAIN_ID
```

While on the other hand what this terraform provider does is boil all those different values down to just domain_id and domain_name (this is wrong):
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/provider.go#L82-L103

Gophercloud supports all these values correctly itself, the terraform provider just isn't correctly passing them along.

Domain scope isn't useful to terraform, so that's safe to ignore (OS_DOMAIN_ID, OS_DOMAIN_NAME).

### Expected Behavior
Terraform should be able to correctly handle domain values when talking to OpenStack and use them correctly through gophercloud.

### Actual Behavior
As per:
https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/provider.go#L82-L103
This provider is entirely ignoring the unique meaning of each domain value and simply grouping them all under domain_id and domain_name. Gophercloud sort of then handles this rather than assuming they are meant to domain scope it seems, but I'm not sure on exactly what happens there.

### Steps to Reproduce
I haven't tried to reproduce it, the code is clear as to what happens, but attempting to auth with a user in one domain, to a project in another domain is one way to test this (roles can be assigned for a user in a project that is in a different domain). Or even making sure multiple users of the same name in different domains are correctly used when domain values are provided.

### References
see discussion in: 
terraform-providers/terraform-provider-openstack#271

and continuation in:
gophercloud/gophercloud#252

**Comment by Adrian-Turjak** [comment]
@jtopjian We can potentially expand on this to maybe clean up some of the variable names. It's still mostly using tenant_id and such rather than project_id. Although potentially depending on the changes made to gophercloud we could add extra stuff to gophercloud utils for parsing in the envvars and just have this provider use that much like the clouds.yaml support.

**Comment by jtopjian** [comment]
@Adrian-Turjak Thanks for opening this and for providing the details.

We can certainly add auth attributes such as `os_user_domain_name`, `os_project_domain_name`, etc, but what I need to know is what takes precedence and what needs to be passed depending on what the user supplies.

I have a feeling that the `os_project_domain_*` attributes are purely for the scope part of authentication. Is that correct?

**Comment by jtopjian** [comment]
Quick update on this: I've started some upstream changes that will resolve this.

**Comment by Adrian-Turjak** [comment]
@jtopjian Cool. I was reading some of the responses to gophercloud/gophercloud#252 and kept meaning to respond.

I've also ended up chatting to a few SDK and auth related people and have started the ball rolling for some sort of official client library spec:
http://lists.openstack.org/pipermail/openstack-dev/2018-April/129123.html

As for your above question.

`os_project_domain_*` are for indeed for project scope (authz), while `os_user_domain_*` are for the authentication part (authn) when using username.

Currently this Terraform provider is mostly assuming domain values as used in the openstackclient with:
```
OS_DEFAULT_DOMAIN_ID
OS_DEFAULT_DOMAIN_NAME

# or which is basically OS_DEFAULT_DOMAIN_ID (although less commonly used)
OS_DEFAULT_DOMAIN
```
Where one value is used for both project and user.

Mostly it amounts to having these value (and the ones in the main issue post) correctly passed to gophercloud and work as expected.

Then the second issue to solve in gophercloud itself is rescoping with tokens, but that we'll deal with over there. :)

**Comment by jtopjian** [comment]
> I've also ended up chatting to a few SDK and auth related people and have started the ball rolling for some sort of official client library spec:

Thanks for starting that discussion.

> Mostly it amounts to having these value (and the ones in the main issue post) correctly passed to gophercloud and work as expected.

Indeed. Once Gophercloud is patched to handle easier scoping during client creation, this will be an easy issue to resolve.

**Comment by jtopjian** [comment]
@Adrian-Turjak I've submitted #290 which should resolve this issue as well as any other auth configuration issue.

Would you be able to test this patch by compiling a binary? If you don't know how or don't have the time but still want to test, I would be happy to compile a custom Linux binary for you.

**Comment by Adrian-Turjak** [comment]
@jtopjian I'll have a look at it tomorrow, and I think I can compile it myself. I don't use terraform but it can be a bit of an excuse to try something simple.

**Comment by jtopjian** [comment]
Sounds good! Here's a brief set of instructions:

First make sure you have Go installed. You'll need 1.9 or higher. I use [`gimme`](https://github.com/travis-ci/gimme) to install it.

```
$ go get github.com/terraform-providers/terraform-provider-openstack
$ cd ~/go/src/github.com/terraform-providers/terraform-provider-openstack
$ git remote add jtopjian https://github.com/jtopjian/terraform-provider-openstack
$ git fetch jtopjian
$ git checkout jtopjian/auth-update2
$ make build
$ sudo mv ~/go/bin/terraform-provider-openstack /path/to/dir/where/terraform/is
$ cd
$ mkdir demo
$ cd demo
$ terraform init
$ vi main.tf
```

The above are from my head, so there might be some typos. Let me know if you have any problems.

**Comment by jtopjian** [comment]
@Adrian-Turjak I'm going to go ahead and merge #290. If you run into any further auth problems, please let me know :)

Thank you for your help throughout this -- it's really appreciated.

**Comment by jtopjian** [comment]
@Adrian-Turjak No problem at all!

**Comment by jtopjian** [comment]
@Adrian-Turjak Version 1.4 was just released with these fixes included.
