### ISSUE TITLE
Problem with docs

### ISSUE THREAD

**Issue by xocasdashdash** [terraform-providers/terraform-provider-openstack#278]
I just had an issue with the [servergroups](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/website/docs/r/compute_servergroup_v2.html.markdown)  docs that i'm not sure if it's an issue.

As you can see there it doesn't look like the ID attribute is exported but it is!

Is this something that it's done in general on the resources?

Thanks!

**Comment by fatmcgav** [comment]
@xocasdashdash I believe as a general rule with Terraform resources, the `id` attribute is always exported. 

@jtopjian Does that sound sensible?

**Comment by jtopjian** [comment]
That's correct: all Terraform resources have an ID. For the OpenStack provider, the Terraform resource ID matches the OpenStack resource ID.

**Comment by xocasdashdash** [comment]
ok! Problem solved! Thanks :)
