### ISSUE TITLE
Subnet shouldn't require cidr when using a pool

### ISSUE THREAD

**Issue by jgeorgeson** [terraform-providers/terraform-provider-openstack#282]
The CLI allows creation of a subnet with the CIDR coming from a subnet pool rather than being explicitly declared, but CIDR is required in TF config even when a pool is specified. 

https://docs.openstack.org/ocata/networking-guide/config-subnet-pools.html

> openstack subnet create --subnet-pool demo-subnetpool4 --network demo-network1 demo-subnet1

### Terraform Version

```bash
$ terraform -v
Terraform v0.11.7
+ provider.openstack v1.3.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "openstack" {
  auth_url    = "${var.openstack_auth_url}"
  insecure    = "${var.openstack_insecure}"
  domain_name = "${var.project_domain_name}"
  tenant_name = "${var.project_name}"
}

data "openstack_networking_network_v2" "tenant_network" {
  name = "${var.tenant_network_name}"
}

data "openstack_networking_subnetpool_v2" "pool23" {
  name = "${var.openstack_subnet_pool}"
}

resource "openstack_networking_subnet_v2" "tenant_subnet" {
  name            = "tenant-subnet-${var.project_name}-01"
  tenant_id       = "${var.project_id}"
  network_id      = "${data.openstack_networking_network_v2.tenant_network.id}"
  subnetpool_id   = "${data.openstack_networking_subnetpool_v2.pool23.id}"
  ip_version = 4
}
```

variables.tf:

```hcl
variable "openstack_auth_url" {
  description = "The endpoint url to connect to OpenStack."
  default     = "https://openstack.example.com:5000/v3"
}

variable "openstack_insecure" {
  type        = "string"
  description = "Accept self signed SSL certificates?"
  default     = "true"
}

variable "tenant_network_name" {
  description = "Openstack Network Name"
  default     = "tenant-network-demo"
}

variable "openstack_subnet_pool" {
  description = "Name of the subnet pool"
  default     = "VIOINT_Tenant_pool23"
}

variable "project_domain" {
  description = "The domain of the Project."
  default     = "default"
}

variable "project_name" {
  description = "The name of the Project."
}

variable "project_id" {
  description = "The ID of the Project"
}
```

### Expected Behavior

Subnet should should be created with next available CIDR from the pool provided.

### Actual Behavior

```
Error: openstack_networking_subnet_v2.tenant_subnet: "cidr": required field is not set
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Running VMWare Integrated OpenStack (ViO) with Ocata OpenStack release.

**Comment by jtopjian** [comment]
@jgeorgeson confirmed.

This is an upstream bug that I will look at fixing.
