### ISSUE TITLE
Does terraform-provider-openstack support AutoScale?

### ISSUE THREAD

**Issue by JCHappytime** [terraform-providers/terraform-provider-openstack#293]
hello, does terraform-provider-openstack support AutoScale, please?

**Comment by jtopjian** [comment]
@JCHappytime Unfortunately autoscaling is currently not supported. In order to support it, there would need to be a good amount of work done to the upstream OpenStack Go library to add support for the OpenStack services which provide such support.

Certainly possible to _eventually_ support it, but just to be realistic, it will probably be some time.

**Comment by sebastien-prudhomme** [comment]
@jtopjian Is there someone working on Heat integration?

**Comment by jtopjian** [comment]
@sebastien-prudhomme Not at the moment. I'd be happy to provide support for anyone who wanted to work on it. 

Gophercloud has a good amount of Heat support already, but it's possible it needs some fixes. Again, I could provide support there, too.

**Comment by tianomonteiro** [comment]
@jtopjian?

**Comment by jtopjian** [comment]
@tianomonteiro This isn't on my roadmap to add support for. However, others can work on this and I can review.

**Comment by tianomonteiro** [comment]
@jtopjian Do you know who can help us with this feature?

**Comment by falencastro** [comment]
> @JCHappytime Unfortunately autoscaling is currently not supported. In order to support it, there would need to be a good amount of work done to the upstream OpenStack Go library to add support for the OpenStack services which provide such support.
> 
> Certainly possible to _eventually_ support it, but just to be realistic, it will probably be some time.

Apparently OpenStack Go library won't implement autoscaling through Heat/Autoscale, however it seems support for [Senlin](https://wiki.openstack.org/wiki/Senlin) is [already implemented](https://github.com/gophercloud/gophercloud/tree/master/openstack/clustering/v1), also [heat docs](https://wiki.openstack.org/wiki/Heat/AutoScaling#Note) suggests using Senlin instead for autoscaling.

**Comment by jtopjian** [comment]
> Apparently OpenStack Go library won't implement autoscaling through Heat/Autoscale,

This isn't exactly true. The OpenStack Go library _would_ implement them if they existed 😄 

The OpenStack Heat service never implemented the proposed autoscale features. More details can be seen here: https://github.com/gophercloud/gophercloud/issues/1446

> suggests using Senlin instead for autoscaling.

Yes. However, just to clarify again, Senlin is a separate OpenStack service. If Terraform resources for Senlin existed, the OpenStack cloud would have to host the Senlin service, too.

**Comment by zaneb** [comment]
> The OpenStack Heat service never implemented the proposed autoscale features. More details can be seen here: gophercloud/gophercloud#1446

To be clear, Heat has had autoscaling features since 2013, they're just accessed through Heat templates not a separate ReST API endpoint, so there's nothing for gophercloud to implement.

**Comment by jtopjian** [comment]
It's too bad this isn't clearly documented anywhere - it's confusing to piece together which OpenStack services/projects need to be running in the OpenStack deployment and how to consume those services to achieve autoscaling.

**Comment by ricolin** [comment]
@jtopjian that’s what we been trying to do in auto-scaling SIG [1]
And indeed we need to have a workshop guide for auto scaling in our docs. Before we put everything in an official guide. You can reference this workshop[2] and templates in[3], [4], [5], or in [6].

In the meanwhile, will push that documentation to happen ASAP.
 Also we could use a hand on that task too if anyone can help:)
[1] https://docs.openstack.org/auto-scaling-sig/latest/
[2] https://github.com/sjamgade/monasca-autoscaling (repository with autoscaling workshop from Denver)

[3] https://github.com/sjamgade/monasca-autoscaling/blob/master/final/autoscaling.yaml
[4] https://opendev.org/openstack/heat-templates/src/branch/master/hot/autoscaling.yaml
[5] https://opendev.org/openstack/heat-templates/src/branch/master/hot/senlin/autoscaled_loadbalancer_cluster.yaml (example to use Senlin in Heat)
[6] https://opendev.org/openstack/heat-templates/src/branch/master/hot/monasca/autoscaling.yaml

**Comment by jtopjian** [comment]
@ricolin Thanks so much for the information!
