### ISSUE TITLE
Unnecessary waiting prior to initial state checks

### ISSUE THREAD

**Issue by philsttr** [terraform-providers/terraform-provider-openstack#295]
When creating openstack_lb_member_v2 resources, terraform-provider-openstack will [do the following:](https://github.com/terraform-providers/terraform-provider-openstack/blob/ad0d5ed871c3f2209fd20abf75fc87931a44cc51/openstack/resource_openstack_lb_member_v2.go#L94-L149)

1. [Wait for the load balancer state to be ACTIVE](https://github.com/terraform-providers/terraform-provider-openstack/blob/ad0d5ed871c3f2209fd20abf75fc87931a44cc51/openstack/resource_openstack_lb_member_v2.go#L121)
2. [Create the pool member](https://github.com/terraform-providers/terraform-provider-openstack/blob/ad0d5ed871c3f2209fd20abf75fc87931a44cc51/openstack/resource_openstack_lb_member_v2.go#L129)
3. [Wait for the load balancer state to be ACTIVE, again](https://github.com/terraform-providers/terraform-provider-openstack/blob/ad0d5ed871c3f2209fd20abf75fc87931a44cc51/openstack/resource_openstack_lb_member_v2.go#L141)

This works fine, functionally.  However, there's one small improvement I would like to suggest.

Each call to `waitForLBV2viaPool` (to wait for the load balancer state to become ACTIVE) will [wait 5 seconds](https://github.com/terraform-providers/terraform-provider-openstack/blob/570573a5f080c97b09f8b21dbc849a6293db7847/openstack/lb_v2_shared.go#L185) before it checks the state for the first time. This is fine for step 3 since changes were just made in step 2, _but_ it wastes 5 seconds for step 1. For step 1, the load balancer is generally _already_ ACTIVE, since no changes have been performed on it yet.  So there's no reason to wait 5 seconds before the first state check in step 1

I would like to suggest changing the behavior so that it does NOT wait 5 seconds prior to the state check in step 1. To be clear, it still should wait for the load balancer state to be ACTIVE, it just should not wait 5 seconds before the first check. This change would allow pool member creation to be performed 5 seconds faster. While this might not seem like much, it definitely adds up over time when creating lots pool members. This will be particularly helpful for me, since I deal with an LBaaS provider that has some serious concurrency issues that we have to workaround by reducing the terraform parallelism when creating/updating/deleting pool members.

The same change could be made for updating/deleting pool members (and possibly other resources as well).

### Terraform Version

terraform 0.11.7
terraform-provider-openstack 1.3.0

### Affected Resource(s)

openstack_lb_member_v2

### Terraform Configuration Files
Any config with an openstack_lb_member_v2 resource.

### Debug Output
https://gist.github.com/philsttr/89124e17d68136de01b19ddd17e0d918

### Panic Output
none

### Expected Behavior
Don't wait 5 seconds before checking loadbalancer state before creating/updating/deleting pool members

### Actual Behavior
Waiting 5 seconds before checking loadbalancer state before creating/updating/deleting pool members

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
none, other than we're using a hardware LBaaS provider that has some problems handling lots of concurrent requests.
We therefore have to reduce terraform parallelism to 1 when creating/updating/deleting pool members.
This makes 5 additional seconds per pool member modification particularly painful.

### References
none

**Comment by jtopjian** [comment]
@philsttr Thanks for reporting this. I agree that the delay causes the time to completion to build up. However, the checks done in Step 1 were put in place because of situations when concurrent actions were running and the load balancer was not in an active state. However, I do agree that 5 seconds might be too conservative.

@xgerman sorry for pinging you, but you were the one who originally added the early checks. Do you know if lowering the delay to 1 or even 0 seconds would cause adverse effects in your environments? I don't want to lower the delay only to have reports that environments with concurrency are now seeing issues :)

**Comment by xgerman** [comment]
@jtopjian I added the early checks to make sure we are in a state where we can perform the operation. So not waiting 5s is certainly ok.

@philsttr unrelated, but if we could use single-create (see https://developer.openstack.org/api-ref/load-balancer/v2/#create-a-load-balancer - "Creating a Fully Populated Load Balancer") that should help you getting members added faster (if the LB provider you use supports that)

**Comment by jtopjian** [comment]
> I added the early checks to make sure we are in a state where we can perform the operation. So not waiting 5s is certainly ok.

Right, I figured the important part was the wait/poll itself and not necessarily the delay, but I wanted to make sure :)

Thank you for the quick confirmation!

**Comment by philsttr** [comment]
Thank you so much for improving this!

Any estimate on when 1.5.0 will be released?
