### ISSUE TITLE
provider.openstack 1.4.0 - data sources openstack_identity_*_v3 won't use correct endpoint

### ISSUE THREAD

**Issue by steadyjaw** [terraform-providers/terraform-provider-openstack#319]
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.openstack v1.4.0
```
### Affected Resource(s)
- openstack_identity_project_v3
- openstack_identity_role_v3
- openstack_identity_user_v3

This issue appears to affect all identity_v3 data sources, but it might also affect all identity resources as well. (haven't tested it)
It seems, there is an issue within the openstack.provider or the gophercloud, as it provides the functions for API-access.

### Terraform Configuration Files
```hcl
data "openstack_identity_user_v3" "user_1" {
  name = "user_1"
}
data "openstack_identity_role_v3" "admin" {
  name = "admin"
}
data "openstack_identity_project_v3" "project_1" {
  name = "demo"
}
```

### Debug Output
[https://gist.github.com/steadyjaw/995478de755a2f586391df9f6a8e5581](https://gist.github.com/steadyjaw/995478de755a2f586391df9f6a8e5581)

### Expected Behavior
provider uses correct URLs to access identity API: 
- https://url.was.removed:13000/v3/roles?name=admin
- https://url.was.removed:13000/v3/users?enabled=true&name=user_1
- https://url.was.removed:13000/v3/projects?enabled=true&is_domain=false&name

### Actual Behavior
openstack provider generates wrong path  -> gets reponse code 404
It extracts endpoints from os_auth-response and builds URL.
But it doesn't make sure, it uses the right API-path in URL.

### Steps to Reproduce
1. create configuration file with identity_v3 resources
2. `terraform init`
3. `terraform plan`

### Important Factoids
keystone v3 is configured and working well within our openstack platform , even if standard endpoint isn't set to v3.

```
$ openstack endpoint list --service keystone --interface public
+----------------------------------+-----------+--------------+--------------+---------+-----------+------------------------------------+
| ID                               | Region    | Service Name | Service Type | Enabled | Interface | URL                                |
+----------------------------------+-----------+--------------+--------------+---------+-----------+------------------------------------+
| 356d4f49cc0c42a89c59cee12e700f6f | regionOne | keystone     | identity     | True    | public    | https://url.was.removed:13000/v2.0 |
+----------------------------------+-----------+--------------+--------------+---------+-----------+------------------------------------+
$ env |grep OS_
OS_AUTH_URL=https://url.was.removed:13000/v3
OS_REGION_NAME=regionOne
OS_PROJECT_NAME=demo
OS_USER_DOMAIN_NAME=domainname
OS_IDENTITY_API_VERSION=3
OS_INTERFACE=public
OS_PASSWORD=really_Strong_p4ssword
OS_USERNAME=user_1
OS_PROJECT_ID=8458aecf03da4f139f34d03391c94310
```

**Comment by jtopjian** [comment]
@steadyjaw Thanks for reporting this issue.

The cause of the problem can be seen here:

```
https://url.was.removed:13000/v2.0/v3/roles?name=admin
```

Note how the URL has `/v2.0/v3`.

There's an existing issue for this here: https://github.com/terraform-providers/terraform-provider-openstack/issues/239

There's a pending upstream fix for this. I hope to have it merged soon.

If you can confirm this is the same issue, I propose closing this issue in favor of #239.

Please let me know if you have any questions.

**Comment by steadyjaw** [comment]
@jtopjian Thanks for the reply!

Yes, same issue, from my point of view.
I tried to find a similar Issue ... guess I haven't had a good look in to the list of issues. :)

Closing it in favor of #239
