### ISSUE TITLE
Domain ID not used when creating a project

### ISSUE THREAD

**Issue by chewdevs** [terraform-providers/terraform-provider-openstack#328]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.11.7
+ provider.openstack v1.5.0
```

### Affected Resource(s)
- openstack_identity_project_v3

### Terraform Configuration Files
```hcl
data "openstack_identity_project_v3" "ad-subs" {
  name = "my_domain"
  is_domain = true
}

resource "openstack_identity_project_v3" "admin_project" {
    name = "admin"
    domain_id = "${data.openstack_identity_project_v3.ad-subs.domain_id}"
    description = "Admin project for ad-subs"
}
```

### Debug Output
[Debug outpout ](https://gist.github.com/chewdevs/9f57bdbdf061077ffca88bd1c56c50ee#file-gistfile1-txt)

### Expected Behavior
The project should be created in the correct domain.

### Actual Behavior
The domain_id seems to not be used and the domain is created in the default domain.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jtopjian** [comment]
@chewdevs apologies for the delay - I'm a little behind on things. I'll take a look at this in the next few days.

**Comment by jtopjian** [comment]
@chewdevs as far as I can tell, this is expected behavior.

The data source is returning details about a project. The project's `domain_id` really is null, which is causing the project resource's `domain_id` to also be null.

Since the project is _also_ a domain, the following should work:

```hcl
resource "openstack_identity_project_v3" "admin_project" {
    name = "admin"
    #domain_id = "${data.openstack_identity_project_v3.ad-subs.domain_id}"
    domain_id = "${data.openstack_identity_project_v3.ad-subs.id}"
    description = "Admin project for ad-subs"
}
```

Notice how instead of `domain_id`, I'm using `id`.

Let me know if this helps. If this doesn't work for you, I think the best option would be for us to create a proper "domain" data source.

**Comment by chewdevs** [comment]
@jtopjian It works with the id. 

Thank you for your support !

**Comment by jtopjian** [comment]
@chewdevs Great! Thanks for the follow-up 😄 

I"m going to close this issue, but please let me know if you have any other questions.
