### ISSUE TITLE
min_disk_gb and min_ram_mb must be positive in openstack_images_image_v2

### ISSUE THREAD

**Issue by AndyEWang** [terraform-providers/terraform-provider-openstack#341]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_images_image_v2

### Terraform Configuration Files
resource "openstack_images_image_v2" "image" {
    name = "test"
    local_file_path = "/tmp/test.qcow2"
    disk_format = "qcow2"
    min_disk_gb = 0
    min_ram_mb = 0
}

### Debug Output
Error: module.glance_image_test_image.openstack_images_image_v2.image: "min_disk_gb" must be a positive integer
Error: module.glance_image_test_image.openstack_images_image_v2.image: "min_ram_mb" must be a positive integer

### Expected Behavior
    min_disk_gb = 0 and  min_ram_mb = 0 can work whether they are explicitly put in the configuration or not.

### Actual Behavior
terraform requires min_disk_gb > 0 and  min_ram_mb > 0 if they are explicitly put in the configuration.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. explicity put following parameters in resource openstack_images_image_v2
    min_disk_gb = 0
    min_ram_mb = 0
2. terraform init
3. terraform plan
4. `terraform apply`

**Comment by jtopjian** [comment]
@AndyEWang Thanks for opening this issue.

Just to clarify, do you really mean `container_format = 0` or `min_ram_mb = 0` ?

**Comment by AndyEWang** [comment]
Sorry, should be min_disk_gb = 0 or  min_ram_mb = 0 explicitly put in the configuration
