### ISSUE TITLE
Unexpect ProjectID attribute cause FWaaS Acc tests failed

### ISSUE THREAD

**Issue by kiwik** [terraform-providers/terraform-provider-openstack#342]
ACC tests failing in OpenLab testing, that cause by unexpect `ProjectID` attribute.
- TestAccFWRuleV1_basic
- TestAccFWRuleV1_anyProtocol
- TestAccFWRuleV1_updateName

```bash
Expected: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:""} 
Found: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:"c8e96ca4f3dd4c789b13955f73adc9a7"}
```
Log file defailt: http://logs.openlabtesting.org/logs/35/335/c51eb79051a39911dc05ea1891e29a01e1d48b5e/recheck-fwaas/terraform-provider-openstack-acceptance-test-fwaas/5d4692e/job-output.txt.gz

NOTE: there are other test failings in log, this issue trace test cases, include: 
- TestAccFWRuleV1_basic
- TestAccFWRuleV1_anyProtocol
- TestAccFWRuleV1_updateName

### Terraform Version
N/A

### Affected Resource(s)
- openstack_fw_rule_v1

### Terraform Configuration Files
N/A

### Debug Output
```bash
Expected: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:""} 
Found: 
&rules.Rule{ID:"b313ed8a-2019-4cf6-9992-06b7905c7cdb", Name:"rule_1", Description:"", Protocol:"udp", Action:"deny", IPVersion:4, SourceIPAddress:"", DestinationIPAddress:"", SourcePort:"", DestinationPort:"", Shared:false, Enabled:true, PolicyID:"", Position:0, TenantID:"", ProjectID:"c8e96ca4f3dd4c789b13955f73adc9a7"}
```
### Panic Output
N/A

### Expected Behavior
ACC tests pass
- TestAccFWRuleV1_basic
- TestAccFWRuleV1_anyProtocol
- TestAccFWRuleV1_updateName

### Actual Behavior
ACC tests failed

### Steps to Reproduce
Run FWaaS accpetance tests

### Important Factoids
N/A

### References
N/A

**Comment by jtopjian** [comment]
@kiwik FWaaS v1 used to pass. Are you sure this isn't an issue with the devstack configuration?

**Comment by jtopjian** [comment]
@kiwik Actually, I'm able to reproduce the error. This must have been a change introduced in FWaaS. Thanks for the heads up :)

**Comment by kiwik** [comment]
@jtopjian Yes, we did not change any FWaaS v1 config since tests last pass, seems FWaaS service side change cause `ProjectID` attribute return, it can not be controlled in config level.

**Comment by kiwik** [comment]
@jtopjian Some other issues still exist in FWaaS acceptance tests, we are still finding the root reason, PR #343 just fix ProjectID issue.
