### ISSUE TITLE
Does terraform-provider-openstack supports trunk ports?

### ISSUE THREAD

**Issue by jnunyez** [terraform-providers/terraform-provider-openstack#345]
Hi,
does terraform-provider-openstack supports the feature of adding/setting network trunk ports?

Thanks,
Jose

**Comment by jtopjian** [comment]
Hello,

Unfortunately the Neutron trunk extension is not supported at this time. I'm going to leave this issue open to track it as a feature request.

Please let me know if you have any questions :)

**Comment by celebdor** [comment]
@jtopjian I guess you can close it now

**Comment by jtopjian** [comment]
@celebdor Yes, good point :)

@jnunyez This has been implemented in #446 and will be available in the next release.
