### ISSUE TITLE
 feature requests: enable multiattach for cinder volumes

### ISSUE THREAD

**Issue by bogdansavu** [terraform-providers/terraform-provider-openstack#346]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
openstack_blockstorage_volume_v3

### Feature Request:
There is possible to enable multiattach for cinder volumes? Or there is any workaround to allow us to set multiattach property  for cinder volumes? 

Thank you.

**Comment by jtopjian** [comment]
Hello,

Unfortunately multiattach is not supported at this time. My understanding is that multiattach support is still very new (only available in cinder v3.50 and up) so it could take some time before it officially becomes supported here.

I'm going to keep this issue open to track this as a feature request.

Please let me know if you have any questions :)

**Comment by jtopjian** [comment]
Support for multiattach is now available in the `openstack_blockstorage_volume_v3` resource. However, successfully using multiattach is still very much dependent on the volume driver and version of Cinder.

**Comment by jamesmmccarthy** [comment]
Hello,

More work has been done in this area, and should be available in the upcoming terraform-provider-openstack release 1.11.0 - keep an eye out !

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/CHANGELOG.md
