### ISSUE TITLE
enhancement request: allow vm state change

### ISSUE THREAD

**Issue by bogdansavu** [terraform-providers/terraform-provider-openstack#349]
Hello,

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- resource_openstack_compute_instance_v2

### Expected Behavior
Have a property to allow us to change the vm state for an instance.

### Actual Behavior
There is not any option to modify the vm state.

### Solution
Implement a new property like vm_state to allow us to change the state to ACTIVE or SHUTOFF.

**Comment by bogdansavu** [comment]
I implemented the state property (optional) , that allow us to change the VM state.

**Comment by jtopjian** [comment]
Implemented in #350
