### ISSUE TITLE
Support barbican resources

### ISSUE THREAD

**Issue by megakoresh** [terraform-providers/terraform-provider-openstack#352]
It would be nice to support Barbican API in Terraform, so that SSL-terminating loadbalancers could be deployed fully via terraform.

### Terraform Version
0.11.7

### Affected Resource(s)
- openstack_lb_listener_v2

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I can add barbican secrets via terraform.

### Actual Behavior
I can't add barbican secrets via terraform.

### Steps to Reproduce
1. Try to set up SSL-terminating loadbalancer using Terraform
2. Be disappointed

### Important Factoids
This has come up already, but in a different context

### References
- https://github.com/terraform-providers/terraform-provider-openstack/issues/76

**Comment by jtopjian** [comment]
@megakoresh upstream support for the Barbican API was only added last week, which is why there has been a lack of Barbican support in Terraform. Depending on contributor availability, we should see support in Terraform in the future.

**Comment by simonre** [comment]
@jtopjian @megakoresh I'd like to implement this if nobody else is working on it already

**Comment by kayrus** [comment]
@simonre I'm ok with this.

**Comment by jtopjian** [comment]
@simonre That would be much appreciated.

We've been working our way through the code and doing a large cleanup. There's a basic style guide here (#456). An easy example of this can be seen with:

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/compute_flavor_v2.go
* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_flavor_v2.go

It would be great if you could follow these patterns for the new resources. If not, I can reformat them afterwards.

**Comment by kayrus** [comment]
@simonre I apologies for bothering you, but could you please share the current status? Do you need any help? We can split the task apart, if you wish.

**Comment by simonre** [comment]
@kayrus Sorry, I've been a bit busy the past weeks and only really started working on this this week. I've implemented and tested the 'secrets' resource and I'll open a PR today I think. I've also started work on the other resources. If the implementation is very urgent for you we could share the task, otherwise I'll hopefully be done in about three weeks :)

**Comment by kayrus** [comment]
@simonre thanks for the update, one month is ok. Take your time ;)

**Comment by MariaBiosciences** [comment]
@simonre this would be an awesome feature, any updates on this?

**Comment by simonre** [comment]
@MariaBiosciences I opened a Pull Request [here](https://github.com/terraform-providers/terraform-provider-openstack/pull/650) but it seems to have been forgotten (?) 
And since adding the secrets resource is kind of the base functionality, I haven't opened the other Pull Requests yet
