### ISSUE TITLE
Can't create external network with terraform 

### ISSUE THREAD

**Issue by HassanIstanbouli** [terraform-providers/terraform-provider-openstack#356]
### Terraform Version
11.0.7

### Affected Resource(s)

- openstack_networking_network_v2

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
it seems like ,terraform dose not support "**External Network** " in OpenStack Provider because i can't create it . in other words there isn't an "External Network" Attribute .
i can make it shared but i can't make it external :(

### Actual Behavior
no attribute to do that .

### Important Factoids
OpenStack "Newton" release .

### References
https://www.terraform.io/docs/providers/openstack/r/networking_network_v2.html

**Comment by jtopjian** [comment]
Implemented in #357
