### ISSUE TITLE
Need resource for neutron address scopes

### ISSUE THREAD

**Issue by kschroed** [terraform-providers/terraform-provider-openstack#364]
We are currently using Cisco ACI with the Neutron ACI Integration Module(AIM) and leveraging the https://github.com/kubernetes-incubator/kubespray for deploying K8S clusters on top of Openstack.  In order to stream line creating multiple K8S clusters under one Openstack project we would like to leverage the address-scope resource in neutron which currently does not have a terraform resource definition.  The terraform openstack_networking_subnetpool_v2 seems to accept address_scope_id as a valid argument but there is no resource avaialble by which to create address scopes. 

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.11.3
+ provider.null v1.0.0
+ provider.openstack v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking

**Comment by ozerovandrei** [comment]
Hello @kschroed.

Address-scopes resource was added in `1.15.0 (February 06, 2019)` release.
Data source will be included in the future `1.18.0` release.
