### ISSUE TITLE
Feature request : Add openstack_networking_port_associate_v2 resource

### ISSUE THREAD

**Issue by mcanevet** [terraform-providers/terraform-provider-openstack#370]
Currently the only way to associate a port to an instance is to use the instance's `network` attribute.
It would be great to be have an `openstack_networking_port_associate_v2` resource to perform the association.

**Comment by jtopjian** [comment]
@mcanevet would #325 work as well?

**Comment by mcanevet** [comment]
I didn't see the PR, I'll test it.

**Comment by jtopjian** [comment]
@mcanevet Just wanted to follow-up on this - do you still have a use-case for this resource?

**Comment by mcanevet** [comment]
@jtopjian no, we can close this. We are using `openstack_compute_attach_interface_v2`.
