### ISSUE TITLE
using terraform-provider-openstack v1.7.0 causes a panic while handling data source openstack_networking_network_v2

### ISSUE THREAD

**Issue by jrandall** [terraform-providers/terraform-provider-openstack#382]
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.openstack v1.7.0
```

### Affected Resource(s)
- data "openstack_networking_network_v2"

### Terraform Configuration Files
```hcl
provider "openstack" {
  version     = "~> 1.7.0"
}

data "openstack_networking_network_v2" "external_network" {
  name = "public"
}
```

### Debug Output
Sanitized debug output with `OS_DEBUG=1` when run with 1.7.0:
https://gist.github.com/jrandall/b009674038c434891386146beef8b6c5#file-tf_os_debug-1-7-0-log

Sanitized debug output with `OS_DEBUG=1` when run (successfully) with 1.6.0 (for comparison):
https://gist.github.com/jrandall/b009674038c434891386146beef8b6c5#file-tf_os_debug-1-6-0_working-log

### Panic Output
Sanitized `crash.log` written by `terraform plan` using terraform-openstack-provider 1.7.0:
https://gist.github.com/jrandall/b009674038c434891386146beef8b6c5#file-crash-log

### Expected Behavior
No changes were expected from this plan, and pinning terraform-provider-openstack version to v1.6.0 and re-running confirms everything still works fine with 1.6.0.

### Actual Behavior
Terraform panicked and exited with a crash.log

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
Red Hat OpenStack Platform 12 - based on the Pike release of OpenStack.

The panic results from Gophercloud `extractIntoPtr` function on line 93 of `results.go`: https://github.com/terraform-providers/terraform-provider-openstack/blob/v1.7.0/vendor/github.com/gophercloud/gophercloud/results.go#L93

This panics because for whatever reason `label` (i.e. "networks") is not present in `m` and so `m[label]` is nil which results in a panic when the type assertion is made that insists it must be a slice. 

The main difference between v1.7.0 and v.1.6.0 problem appears to be that for some reason v1.7.0 is setting `router:external=false` in the v2.0 networks request to the openstack API (see https://gist.github.com/jrandall/b009674038c434891386146beef8b6c5#file-tf_os_debug-1-7-0-log-L383), so it then returns no entries as the network in question is an external one (however, I would in that case still expect terraform to handle the empty list that is returned without panic). 

I surmise this is probably a result of the changes made in https://github.com/terraform-providers/terraform-provider-openstack/pull/358 to add an `external` attribute to data_source_openstack_networking_network_v2 - I will try adding `external: true` to the data source configuration to see if that resolves the issue, but note that this represents a breaking change for anyone who relies upon the previous functionality (which looked up all networks regardless of whether they were external or not). 

IMHO changes that can result in configurations becoming invalid (i.e. not backwards compatible in all cases) should result in major version bumps (i.e. I would have expected this to be `2.0.0` rather than `1.7.0`).

**Comment by jrandall** [comment]
I can confirm that changing the configuration to:
```hcl
provider "openstack" {
  version     = "~> 1.7.0"
}

data "openstack_networking_network_v2" "external_network" {
  name = "public"
  external = true
}
```

Does resolve the issue. However, without the `external = true` or with an explicit `external = false` the OpenStack networking API returns no networks which then causes terraform to crash. 

There are really two separate issues here:
1. the situation when no networks were returned for the data source should be handled gracefully rather than with a panic
2. the default behaviour when `external` is not specified should be unchanged from 1.6.0 - that is, the data source should match both external and non-external networks of the given name rather than defaulting to returning only non-external networks.

**Comment by jtopjian** [comment]
@jrandall Thank you for the report. We'll look into this.

**Comment by jtopjian** [comment]
@jrandall A new version was just released which resolves this issue. Please let me know if you're still encountering problems, though.

Thanks again for reporting this.
