### ISSUE TITLE
LBaaS Pool Member should allow a weight of 0

### ISSUE THREAD

**Issue by philsttr** [terraform-providers/terraform-provider-openstack#392]
The terraform openstack provider does not allow LBaaS pool members with a weight of 0.

A weight of 0 is a valid value and should be supported by the terraform openstack provider.

See the OpenStack documentation, which specifies that 0 is a valid value:
* [create member](https://developer.openstack.org/api-ref/load-balancer/v2/index.html#create-member)
* [update member](https://developer.openstack.org/api-ref/load-balancer/v2/index.html#update-a-member)

> The weight of a member determines the portion of requests or connections it services compared to the other members of the pool. For example, a member with a weight of 10 receives five times as many requests as a member with a weight of 2. _A value of 0 means the member does not receive new connections but continues to service existing connections_. A valid value is from 0 to 256. Default is 1.

> Setting the member weight to 0 means that the member will not receive new requests but will finish any existing connections. This “drains” the backend member of active connections.

### Terraform Version
terraform 0.11.7 
terraform-provider-openstack 1.7.0

### Affected Resource(s)
`openstack_lb_member_v2`

### Terraform Configuration Files

```
resource "openstack_lb_member_v2" "member" {
  pool_id       = "${var.pool_id}"
  subnet_id     = "${var.subnet_id}"
  address       = "${var.address}"
  protocol_port = "${var.port}"
  weight        = "0"
}
```

### Expected Behavior

The terraform openstack provider should allow setting a pool member's weight to 0

### Actual Behavior

The terraform openstack provider returns the following error:

```
Error: openstack_lb_member_v2.member: Only numbers greater than 0 are supported values for 'weight'
```

The error comes from [here](https://github.com/terraform-providers/terraform-provider-openstack/blob/5e6c44989b04278c1ee24c50fbadd044de9d8175/openstack/resource_openstack_lb_member_v2.go#L63-L70)

### Steps to Reproduce

Attempt to plan or apply a `openstack_lb_member_v2` resource with a weight of 0

**Comment by jtopjian** [comment]
Implemented in #451
