### ISSUE TITLE
Resource 'openstack_networking_port_v2.xxx' does not have attribute 'all_fixed_ips.0' for DNS records

### ISSUE THREAD

**Issue by michalmedvecky** [terraform-providers/terraform-provider-openstack#40]
### Terraform Version
0.9.8

### Affected Resource(s)
- openstack_networking_port_v2
- dns_a_record_set

### Terraform Configuration Files
```hcl
resource "openstack_networking_network_v2" "net-backend" {
  name = "sandbox"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "net-backend-subnet" {
  name = "sandbox"
  network_id = "${openstack_networking_network_v2.net-backend.id}"
  cidr = "100.127.172.0/24"
  dns_nameservers = [ "100.127.70.70" ]
  ip_version = 4
  depends_on = ["openstack_networking_network_v2.net-backend"]
}
provider "dns" {
  update {
    server        = "dns01.example.com"
    key_name      = "rndc-key."
    key_algorithm = "hmac-md5"
    key_secret    = "xxx-not-important=="
  }
}

# Create a DNS A record set
resource "dns_a_record_set" "www" {
  depends_on = ["openstack_networking_port_v2.test_node_port_backend"]
  count = "1"
  zone = "example.com."
  name = "test0${count.index+1}"
  addresses = ["${element(openstack_networking_port_v2.test_node_port_backend.*.all_fixed_ips.0, count.index)}"]
  ttl = 60
}

resource "openstack_networking_port_v2" "test_node_port_backend" {
  count = "1"
  name = "test0${count.index+1}.example.com."
  admin_state_up = "true"
  network_id = "${openstack_networking_network_v2.net-backend.id}"
}

}
```

### Debug Output

Output from `terraform plan`:

```
Error running plan: 1 error(s) occurred:

* dns_a_record_set.www: 1 error(s) occurred:

* dns_a_record_set.www: Resource 'openstack_networking_port_v2.test_node_port_backend' does not have attribute 'all_fixed_ips.0' for variable 'openstack_networking_port_v2.test_node_port_backend.*.all_fixed_ips.0'
```

### Expected Behavior
TF should not complain about `all_fixed_ips.0` and go ahead

### Actual Behavior
TF complains and fails

### Steps to Reproduce
0. create tf files (see above)
1. `terraform plan`

### Important Factoids

When using the same reference in `openstack_compute_instance_v2` resource, it works, e.g.

```hcl
resource "openstack_compute_instance_v2" "test" {

....

  metadata {
    keepalived_vip = "${openstack_networking_port_v2.test_node_port_backend.0.all_fixed_ips.0}"
  }

....
}
```

**Comment by michalmedvecky** [comment]
Sorry I am not really sure whether this should go to openstack provider, dns provider or terraform core :\

**Comment by fatmcgav** [comment]
@michalmedvecky The way you're referencing the value is different in `openstack_compute_instance_v2.test` vs `dns_a_record_set.www`.

You've got `.0` in the former and `.*` in the latter... 
Have you tried `dns_a_record_set.www` with `.0`?

**Comment by sebastien-prudhomme** [comment]
Same problem for me after updating from 0.9.5 to 0.9.11.
Need to replace `all_fixed_ips.0` by `all_fixed_ips[0]`

**Comment by jtopjian** [comment]
Looks like this has been resolved by updating the HCL syntax. I'm going to close this, but if this is still a problem, please let me know.
