### ISSUE TITLE
Problem with security groups with ports and instances

### ISSUE THREAD

**Issue by xocasdashdash** [terraform-providers/terraform-provider-openstack#408]
### Terraform Version
0.11.7
### Affected Resource(s)

- openstack_compute_instance_v2
- openstack_networking_port_v2

### Terraform Configuration Files
```hcl
provider "openstack" {}

resource "openstack_networking_secgroup_v2" "a_security_group" {
  name = "SG_NAME"
}

resource "openstack_networking_secgroup_rule_v2" "ingress_tcp" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = "80"
  port_range_max    = "80"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.a_security_group.id}"
}

resource "openstack_compute_keypair_v2" "test-keypair" {
  name       = "test-keypair"
  public_key = "${var.public_key}"
}

resource "openstack_compute_instance_v2" "webserver-vm" {
  name            = "test-vm"
  image_id        = "${var.frontend_image_id}"
  flavor_id       = "${var.frontend_flavor_id}"
  key_pair        = "test-keypair"
  security_groups = ["default"]

  network {
    port = "${openstack_networking_port_v2.a_port.id}"
  }
}

resource "openstack_networking_port_v2" "a_port" {
  name           = "test-port"
  network_id     = "${openstack_networking_network_v2.network.id}"
  admin_state_up = "true"

  security_group_ids = [
    "${ openstack_networking_secgroup_v2.a_security_group.id }",
  ]
}

resource "openstack_networking_subnet_v2" "subnet" {
  name        = "subnet"
  network_id  = "${openstack_networking_network_v2.network.id}"
  cidr        = "192.168.4.0/24"
  ip_version  = 4
  enable_dhcp = "true"
}

resource "openstack_networking_network_v2" "network" {
  name           = "network"
  admin_state_up = "true"
}

```

### Expected Behaviour
I added a security group to a port, and it got added to the instance (maybe it's openstack behaviour) so it works as expected. If i run terraform plan again, there should not be any detected changes.

### Actual Behaviour
If i run terraform plan again it detects that the instance has some groups attached that it should not have (the one from the port) so it tries to remove it.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out=tfplan`
2. `terraform apply tfplan`
3. `terraform plan -out=tfplan` => this one detects changes.

**Comment by jtopjian** [comment]
@xocasdashdash I believe the behavior you're seeing is described here:

https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#instances-and-ports

Have you tried creating the instance without specifying `security_groups`?

**Comment by xocasdashdash** [comment]
I'm about to, do you have any more info about the openstack bug mentioned there? I think that could be the key

**Comment by jtopjian** [comment]
I think this is the bug mentioned in the docs: https://bugs.launchpad.net/nova/+bug/1373774

Although it says "fixed", the patch was reverted. The discussion in the bug states that when using ports, it's best to configure security groups via neutron (port) rather than nova (instance).

There's always the chance I'm wrong - it's been a _long_ time since I looked over that information and maybe things have also changed - but the best practice of `security_groups` and `network.port` being mutually exclusive has held up quite well.

**Comment by jtopjian** [comment]
I'm going to close this issue since this behavior is noted in our documentation and it appears that this is how Neutron Ports and Nova Instances still continue to work together.

However, please let me know if you have any questions or would like to see this re-opened.
