### ISSUE TITLE
Enable Transparent VLAN mode

### ISSUE THREAD

**Issue by dustnic** [terraform-providers/terraform-provider-openstack#430]
This request is to support the network **transparent-vlan** option for the resource `openstack_networking_network_v2 `.

The transparent VLAN is a quite important feature especially in NFV use-cases.

https://specs.openstack.org/openstack/neutron-specs/specs/kilo/nfv-vlan-trunks.html
https://docs.openstack.org/python-openstackclient/pike/cli/command-objects/network.html

**Comment by ozerovandrei** [comment]
Support for the `vlan-transparent` extension should be added into Gophercloud first.
I've created an issue: [Gophercloud#1304](
https://github.com/gophercloud/gophercloud/issues/1304).

**Comment by ozerovandrei** [comment]
@dustnic Hello.
Support for the `transparent_vlan` argument/attribute was implemented and it will be available in the `v1.14.0` release.
