### ISSUE TITLE
Feature request: Update Openstack Provider multiattach functionality

### ISSUE THREAD

**Issue by jamesmmccarthy** [terraform-providers/terraform-provider-openstack#432]
The gophercloud sdk has been updated to facilitate multiattach enabled volumes in openstack.

- [x] New `multiattach` argument and attribute for the `openstack_blockstorage_volume_v3` resource #431 
- [x] improve work with attachment of multiattach-enabled volumes

**Comment by ozerovandrei** [comment]
Implemented in #431.

@jamesmmccarthy thank you!

**Comment by jamesmmccarthy** [comment]
@jtopjian @ozerovandrei Joe and myself have been chatting some more about this offline. While the work that has been done so far is fine in and of itself, there looks to be some more work needed around attaching/dealing with multiattach enabled volumes. Is it ok to re-open this issue, or should a new one be created ?

**Comment by jtopjian** [comment]
I think this is closable again - but we can re-open if there's still anything missing :)
