### ISSUE TITLE
openstack_networking_secgroup_rule_v2 v1.10 breaks (v1.9 did not)

### ISSUE THREAD

**Issue by sad-boy-uoa** [terraform-providers/terraform-provider-openstack#437]
Hi there,

When upgrading from the openstack provider v1.9 to v1.10, the terraform code for creating security groups starts breaking. This was working fine with v1.9

### Terraform Version
0.11.8

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_secgroup_rule_v2

### Terraform Configuration Files
```hcl
# Base Security Group
resource "openstack_networking_secgroup_v2" "base" {
  name        = "base"
  description = "Allow port 22 ingress and egress to/from the internet"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_ssh" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 22
  port_range_max    = 22
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.base.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_egress" {
  direction         = "egress"
  ethertype         = "IPv4"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.base.id}"
}

# App Server Security Group
resource "openstack_networking_secgroup_v2" "erp_app_server" {
  name        = "app-server"
  description = "Allow port 80 and 443 ingress"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_http" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 80
  port_range_max    = 80
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.erp_app_server.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_https" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 443
  port_range_max    = 443
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.erp_app_server.id}"
}

resource "openstack_networking_secgroup_rule_v2" "secgroup_rule_8080" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 8080
  port_range_max    = 8080
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.erp_app_server.id}"
}
```

### Debug Output
https://gist.github.com/sad-boy-uoa/34fd2c00313cab90dadea61d182bba47

### Expected Behavior
Create security groups

### Actual Behavior
Errors occur

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jtopjian** [comment]
@sad-boy-uoa Thank you for the report.

This is being caused by https://github.com/terraform-providers/terraform-provider-openstack/pull/416, though it's odd because I verified it worked on both Mitaka and Queens. 

Perhaps this is something specific to Catalyst? Would you be able to confirm?

There are workarounds we can do here, but I'm cautious when deviating from "vanilla" OpenStack.

**Comment by jtopjian** [comment]
Another thought: it might be caused by a specific Neutron driver, in which case it's something we could resolve upstream in Gophercloud rather than doing a Terraform-specific fix.

**Comment by sad-boy-uoa** [comment]
Hi there, thank you for the quick response. I'll try and investigate with Catalyst.

Could you give me some ideas as to what may be causing it on the Openstack side?

**Comment by jtopjian** [comment]
Actually, I can ping @Adrian-Turjak and @lingxiankong to make things simple :)

Hi folks, we seem to have an issue where security group rules aren't working with the "description" field. Prior tests showed this works in the Neutron linuxbridge and OVS driver across old and new releases. Do you know why it might be failing in Catalyst?

**Comment by lingxiankong** [comment]
@jtopjian @sad-boy-uoa hi, the reason is because Catalyst Cloud is still using an old version Neutron that doesn't support 'description' field for security group rule resource.

**Comment by jtopjian** [comment]
@lingxiankong Thank you for the quick reply! OK, sounds good. I can go ahead and patch Gophercloud to omit the `description` field if not specified.

**Comment by sad-boy-uoa** [comment]
@jtopjian would you be able to like the issue and respective PR back to this issue once you get onto it? Thank you!

**Comment by jtopjian** [comment]
@sad-boy-uoa Sure: #438

**Comment by jtopjian** [comment]
#438 has been merged and the fix will be available in the next release. Please let me know if you have any questions or are still running into problems.

**Comment by sad-boy-uoa** [comment]
Thank you very much!
