### ISSUE TITLE
externally deleted "deposed" resources cause error

### ISSUE THREAD

**Issue by jon-proulx** [terraform-providers/terraform-provider-openstack#44]
Hi,

### Rambling narrative

When rebuilding a set of openstack_compute_instance_v2 (which have create_before_destroy = true) some old resources errored on deletion and were put into "deposed" state.

I fixed the error and deleted the resources outside of terraform.  Now terraform state has a recored of the deposed instances but errors with:

* openstack_compute_instance_v2.VM.2 (deposed #0): 1 error(s) occurred:
* openstack_compute_instance_v2.VM.2 (deposed #0): Error deleting OpenStack server: Resource not found

for each deposed instance

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
# security, you can also encrypt the files using our GPG public key.
will provide *if* you really need 'em
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

As requested output of: 
openstack --debug server show <deposed_resource_uuid> 2>&1 
https://gist.github.com/jon-proulx/141b6bd9d9811a124069c2bc42ae7642

### Expected Behavior
terraform should notice deposed resources have been deleted and remove them from tfstate

### Actual Behavior
Error deleting OpenStack server: Resource not found

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` after resource update that requires instance recreation
2. magically construct error that prevents old instance being deleted
3. `openstack server delete <deposed_uuid>`
4. `terraform apply`

**Comment by fatmcgav** [comment]
This sounds like a bug to me, though I've never seen a 'deposed' state before... 

It looks like the error above is being thrown here: https://github.com/terraform-providers/terraform-provider-openstack/blob/be7c7c995a0ef35bd0ec1dfbdc4d75a10dd2dd0b/openstack/resource_openstack_compute_instance_v2.go#L917

@jtopjian Does it make sense to move this into the `StateChangeConf` in the same manner as the recent `LBaaS v2` cleanup stuff?

**Comment by jtopjian** [comment]
I don't think the instances are in a literal "deposed" state - I think Jon was just describing them :)

Doing a quick look, I think this is an easy solution: just do a `CheckDelete` there (and above as well).

**Comment by jon-proulx** [comment]
https://gist.github.com/jon-proulx/311e7691d1605835b5e4b6072368c09a

shows one of the active resources and it's "deposed" counterpart in the tfstate file that's why I used the term (but it's true I'm not really familiar with it's meaning)

**Comment by jtopjian** [comment]
Ugh. I totally botched this up. "deposed" is an actual Terraform state. I wasn't aware of that. I thought Jon was just describing the state of an instance. I apologize. Could have cleared this one up on the mailing list.

@jon-proulx It sounds like you can just remove this from state - either manually with an editor or using `terraform state rm` (thought I haven't tried that).

**Comment by jon-proulx** [comment]
No problem.

I did edit tfstate and push (not sure if state rm can reach deposed bits, I didn't try) and that did work.

Maybe this is more an RFE than a "bug", but seems in the general case if "deposed" state doesn't exist (which is the desired state) it should be quietly forgotten not require manual clean up.

**Comment by jtopjian** [comment]
I agree. My guess is that this is just an area where Terraform Core chose to retain information rather than automatically get rid of deposed resources. No doubt that'll be rehashed in the future.

Are you OK closing this issue?

**Comment by jon-proulx** [comment]
Sure, my situation is sorted if my remaining complaint lives in core (which is kind of what I thought) then nothing to do here.

**Comment by jtopjian** [comment]
okie dokie. Thanks for reporting this and sorry for the confusion.
