### ISSUE TITLE
Networking V2: separate allowed_address_pairs resource

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-providers/terraform-provider-openstack#458]
As discussed in #258, we need to move Networking V2 Port `allowed_address_pairs` into separated `openstack_networking_port_allowed_address_pair_v2` resource.

**Comment by ozerovandrei** [comment]
@jtopjian what do you think about this issue after discussing DHCP opts in #258?

I think it's better to move all of the code in [resource_openstack_networking_port_v2.go#L275](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_port_v2.go#L275) and [resource_openstack_networking_port_v2.go#L442](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_port_v2.go#L442) to a different `openstack/allowed_address_pairs_v2.go` and rewrite it to use `flatten/extend` terms for a new functions.

So we won't separate allowed address pairs to a different resource but will just clean the ports v2 resource code.

**Comment by jtopjian** [comment]
Agreed. But nit-picking on the file names, how about something like `openstack/networking_port_v2.go` which will contain both address pairs and dhcp code. Or `openstack/networking_port_address_pairs_v2.go` and `openstack/networking_port_dhcp_options.go`.

I think it's important to keep the filenames as specific as possible by including the `network` and `port` parts in the event that another resource would have dhcp or address pair (or something else) options.

**Comment by ozerovandrei** [comment]
Sounds right.

I like `openstack/networking_port_v2.go` because there is already so many files in the `openstack` directory.

Let's try to use the following files for each OpenStack object:

 - resource_openstack_service_NAME.go
 - resource_openstack_service_NAME_test.go
 - service_NAME.go (expand/flatten functions and some other helpers)
 - service_NAME_test.go (unit tests for helpers)
 - data_source_openstack_service_NAME.go
 - data_source_openstack_service_NAME_test.go
 - import_openstack_service_NAME_test.go

By the way, do you know if it will be possible to even separate those files to different directories (`networkingv2/resources`, `networkingv2/datasources`, `networkingv2/utils` or something like that)? 
Just look at this monster: [terraform-provider-aws/aws](https://github.com/terraform-providers/terraform-provider-aws/tree/master/aws). It looks scary 😅

**Comment by jtopjian** [comment]
All sounds good to me!

> By the way, do you know if it will be possible to even separate those files to different directories 

It's definitely possible in that Go will allow it, but I've never seen this done in other providers, so we should probably avoid it. The AWS repo is indeed a monster, though :)

**Comment by ozerovandrei** [comment]
Cleaned up in #505
