### ISSUE TITLE
[v0.12] Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by sjwl** [terraform-providers/terraform-provider-openstack#493]
This error is also seen in the debug lot output:
```panic: ConfigValueFromHCL2Block used with unknown value```

### Terraform Version
`Terraform v0.12.0-alpha2`

### Affected Resource(s)
All

I think it's an issue with the provider configuration block

### Terraform Configuration Files
```hcl
provider "OpenStack" {
  auth_url = "https://myopenstackurl:5000/v3/"
  user_domain_name = "foo"
  tenant_id = "bar"
  insecure = true
}

resource "openstack_networking_network_v2" "foo" {
  name = "bar"
}
```

### Debug Output
https://gist.github.com/sjwl/baad0e5dac69ba8e89aae65f8c5a01ff

### Expected Behavior
No errors

### Actual Behavior
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
I believe the problem is how the provider config default value for `bool` types. i.e. - `insecure`, `swath`, and `use_octavia`.  The default value should either be `true` or `false` but they default to either `nil` or empty ("").

**Comment by jtopjian** [comment]
@sjwl I'm going to close this issue since it's been fixed upstream, but I will still leave #494 open as a reminder to have the types of those provider arguments updated.
