### ISSUE TITLE
Support manila resources (shared file system)

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#502]
It would be nice to support Manila API in Terraform

### Terraform Version
0.11.10

### Affected Resource(s)
* openstack_sharedfilesystem_securityservice_v2
* openstack_sharedfilesystem_sharenetwork_v2
* openstack_sharedfilesystem_share_v2
* openstack_sharedfilesystem_share_access_v2

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
I can create shared file systems via terraform.

### Actual Behavior
I can't create shared file systems via terraform.

### Steps to Reproduce
1. Try to create shared file systems using Terraform. 
2. Be disappointed

### Important Factoids
There are gophercloud dependencies like: https://github.com/gophercloud/gophercloud/issues/1334

### References
* WIP is happening here: https://github.com/kayrus/terraform-provider-openstack/commit/5ce41a64fc5f05284c9b4d288173eaa286d0f334

**Comment by jtopjian** [comment]
> WIP is happening here: kayrus@5ce41a6

@kayrus Please submit one resource per PR at a time. Otherwise the PR will be too large to easily review. Thanks!

**Comment by jtopjian** [comment]
> I'll put first two into one PR, because tests will require both resources:

That should be fine, as long as the PR isn't massive. 

If a resource depends on another resource, then it's common to still have individual tests (and separate files) for each. As an example, `openstack_networking_network_v2` has a few tests which only test the single `openstack_networking_network_v2` resource, however, every other networking resource requires a network, so they also have networks in their test fixtures.

On the topic of tests, OpenLab has Manila enabled for Gophercloud, but I'm not sure about Terraform. If it is not enabled, we will want to disable the tests from being run by using an environment variable flag:

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/provider_test.go#L16
* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/provider_test.go#L108-L114
* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_db_database_v1_test.go#L20

At a very minimum, a `_basic` acceptance test is required for each new resource.

> What is the documentation procedure? Should it be inside the same PR? Can documentation be separated?

Documentation is required for new resources and needs to be in the same PR so we can ensure it isn't forgotten about.

Documentation goes in https://github.com/terraform-providers/terraform-provider-openstack/blob/master/website. "r" for resources and "d" for data sources. You can copy an existing file to use as a template. You'll also have to update the side bar [here](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/website/openstack.erb) which is a common thing we always forget :)

> Should data resources be included into the same PR? Are they required?

Data sources are never required. I've only been personally making data sources when they are requested. If you want to make them, by all means go for it. They would also be a separate PR.

Thank you for your work on this and let me know if you have any questions or need any help.
