### ISSUE TITLE
Error creating OpenStack LoadBalancer: Invalid request due to incorrect syntax or missing required parameters.

### ISSUE THREAD

**Issue by kcrouch** [terraform-providers/terraform-provider-openstack#51]
### Terraform Version
$ terraform -v
Terraform v0.9.11

### Affected Resource(s)
openstack_lb_loadbalancer_v2

If I create one without specifying vip_address, all is well.

$ terraform plan
Plan: 6 to add, 0 to change, 0 to destroy.

$ terraform apply
Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

If I attempt to specify a vip_address, the plan works, but the apply does not.

$ terraform plan
Plan: 1 to add, 1 to change, 1 to destroy.

$ terraform apply

Error applying plan:

1 error(s) occurred:

* openstack_lb_loadbalancer_v2.public: 1 error(s) occurred:

* openstack_lb_loadbalancer_v2.public: Error creating OpenStack LoadBalancer: Invalid request due to incorrect syntax or missing required parameters.

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "environment" {
  default = "github-issues"
}

variable "external_gateway" { 
  default = "a3946a55-ce3c-4233-90eb-b01edecda807"
}

variable "floatingip_pool_name" {
  default = "external"
}

variable "cidr_base" {
  default = "192.168.42.0/24"
}

variable "ip_version" {
  default = 4
}

variable "network_name" {
  default = "github-issues"
}

variable "dns_nameservers" {
  default = ["10.10.50.3"]
}

variable "admin_state_up" {
  default = 1
}

resource "openstack_networking_router_v2" "terraform" {
  name             = "Router for the ${var.environment} environment"
  admin_state_up   = "true"
  external_gateway = "${var.external_gateway}"
}

resource "openstack_networking_network_v2" "terraform" {
  name           = "${var.environment}-${var.network_name}"
  admin_state_up = "${var.admin_state_up}"
}

resource "openstack_networking_subnet_v2" "terraform" {
  name            = "${var.environment}-${var.network_name}"
  network_id      = "${openstack_networking_network_v2.terraform.id}"
  cidr            = "${var.cidr_base}"
  ip_version      = "${var.ip_version}"
  dns_nameservers = "${var.dns_nameservers}"
}

resource "openstack_networking_router_interface_v2" "terraform" {
  router_id = "${openstack_networking_router_v2.terraform.id}"
  subnet_id = "${openstack_networking_subnet_v2.terraform.id}"
}

resource "openstack_networking_floatingip_v2" "loadbalancer" {
  pool       = "${var.floatingip_pool_name}"
}

resource "openstack_lb_loadbalancer_v2" "public" {
  vip_subnet_id = "${openstack_networking_subnet_v2.terraform.id}"
#  vip_address   = "${openstack_networking_floatingip_v2.loadbalancer.address}"
  vip_address   = "10.70.0.62"
  name          = "${var.environment}-lbpublic"
  description   = "Public Load Balancer for the ${var.environment} environment"
}
```

With both "vip_address" lines commented out, all is well.  If I use either one of them, it fails.  The hardcoded IP address is the one that was generated by the initial apply.

### Debug Output
https://gist.github.com/kcrouch/e1299b4fe855ee9de18ef59c407adc7c

### Expected Behavior
I was expecting a load balancer with a floating IP to be created.

### Actual Behavior
1 error(s) occurred:

* openstack_lb_loadbalancer_v2.public: 1 error(s) occurred:

2017/07/15 17:18:03 [DEBUG] plugin: terraform: openstack-provider (internal) 2017/07/15 17:18:03 [DEBUG] plugin: waiting for all plugin processes to complete...
* openstack_lb_loadbalancer_v2.public: Error creating OpenStack LoadBalancer: Invalid request due to incorrect syntax or missing required parameters.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I created a fresh OpenStack tenant and made this standalone config for this issue.

**Comment by jtopjian** [comment]
@kcrouch Can you try running with `OS_DEBUG=1`? That might show a more detailed error message on why this is failing:

```shell
$ TF_LOG=DEBUG OS_DEBUG=1 terraform apply
```

Also, do you know which load balancer driver your OpenStack cloud is using?

**Comment by kcrouch** [comment]
I have added gistfile2.txt to https://gist.github.com/kcrouch/e1299b4fe855ee9de18ef59c407adc7c which has the full output as requested (with just the password and endpoint hostname REDACTED).

I do know that we have v2 Load Balancing, but I'm uncertain if it involves Octavia.  I will get with the team managing the OpenStack infrastructure for that information.

Thanks!

**Comment by kcrouch** [comment]
Sounds like garden variety HAProxy service.  I'm getting confirmation that we're not using Octavia.

Thanks!

**Comment by kcrouch** [comment]
Added gistfile3.txt.  If I don't specify the "vip_address", the load balancer gets created, and I can manually do a "neutron floatingip-associate".

**Comment by jtopjian** [comment]
@kcrouch Ah, I see. You're trying to apply a floating IP as the VIP. You should be able to assign a floating IP to the loadbalancer just by adding `port_id` to your floating IP resource:

```hcl
resource "openstack_networking_floatingip_v2" "loadbalancer" {
  pool = "public"
  port_id = "${openstack_lb_loadbalancer_v2.public.vip_port_id}"
}
```

Then omit the `vip_address` information from your loadbalancer resource.

Let me know if that helps.

**Comment by kcrouch** [comment]
YES!  That did the trick!

**Comment by jtopjian** [comment]
Awesome - glad to hear :)

**Comment by rahhali22** [comment]
Hello I have the same problem can you please add more details
