### ISSUE TITLE
Internal: fix Gophercloud empty strings in JSON marshalling 

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-providers/terraform-provider-openstack#514]
Gophercloud commit [3038305b](https://github.com/gophercloud/gophercloud/commit/3038305ba4ed00cfd4ea8403ae65588051f15bb8) breaks Terraform-provider-openstack because we need to use strings references now instead of plain strings.

We need to fix it prior updating Gophercloud in vendor.

Blocks #430

**Comment by jtopjian** [comment]
@ozerovandrei https://github.com/terraform-providers/terraform-provider-openstack/pull/509 should resolve this.

**Comment by ozerovandrei** [comment]
@jtopjian whoops, missed that. Closing this issue then 😄
