### ISSUE TITLE
Manila: add data sources for shares and snapshots

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#563]
* ACLs for already existing resources could be easily added using share data source (share ID): `openstack_sharedfilesystem_share_v2`
* New share resources could be created using share snapshot ID, resolved by share snapshot name: `openstack_sharedfilesystem_snapshot_v2`

gophercloud dependency: https://github.com/gophercloud/gophercloud/issues/1380

**Comment by kayrus** [comment]
@jtopjian is it necessary to have `ForceNew: true` for new data source resources?

**Comment by jtopjian** [comment]
@kayrus Nope, `ForceNew: true` is implied with data sources. It doesn't hurt to have it, though.

**Comment by kayrus** [comment]
@jtopjian ok, good to know.
