### ISSUE TITLE
Networking: ports are created with admin_state_up set to false

### ISSUE THREAD

**Issue by rfc1459** [terraform-providers/terraform-provider-openstack#588]
### Terraform Version
```
$ terraform -v
Terraform v0.11.11
+ provider.openstack v1.13.0
```

### Affected Resource(s)
- openstack_networking_port_v2

### Terraform Configuration Files
```hcl
terraform {
  backend "local" {}
}

provider "openstack" {
  version = "~> 1.13"
}

data "openstack_networking_secgroup_v2" "default_secgroup" {
  name = "default"
}

resource "openstack_networking_network_v2" "net1" {
  name = "net1"
}

resource "openstack_networking_subnet_v2" "subnet1" {
  name       = "subnet1"
  network_id = "${openstack_networking_network_v2.net1.id}"
  cidr       = "192.168.0.0/24"
  ip_version = 4
}

resource "openstack_networking_port_v2" "port1" {
  name       = "port1"
  network_id = "${openstack_networking_network_v2.net1.id}"

  fixed_ip {
    subnet_id = "${openstack_networking_subnet_v2.subnet1.id}"
  }

  security_group_ids = [
    "${data.openstack_networking_secgroup_v2.default_secgroup.id}"
  ]
}

output "port1_admin_state_up" {
  value = "${openstack_networking_port_v2.port1.admin_state_up}"
}
```

### Debug Output
https://gist.github.com/rfc1459/974b44498fcf39c772f66ed683fc3c59

### Expected Behavior
Port should have been created with `admin_state_up` set to `true`.

### Actual Behavior
Port is created with `admin_state_up` set to `false`.

### Steps to Reproduce
1. `terraform init`
2. `terraform apply -auto-approve`

### Important Factoids
In [`resourcePortAdminStateUpV2`](https://github.com/terraform-providers/terraform-provider-openstack/blob/7154fd2187e6c6b1e418fd17ca3fc63d3a2b1463/openstack/resource_openstack_networking_port_v2.go#L531) the default value for `admin_state_up` is `false` unless explicitly specified in the resource. This is a significant deviation from the default behaviour of the [Neutron Port API](https://developer.openstack.org/api-ref/network/v2/index.html?expanded=create-port-detail#create-port) which specifies the default value as `true` for newly created ports.

Also, the provider documentation lists the attribute as optional and does not state that its default value is different from the one of the Neutron API.

### References
None

**Comment by jtopjian** [comment]
@rfc1459 Thank you for reporting this.

This is indeed different behavior from the API. There is a legitimate internal reason about why this is happening, but we should be able to resolve this with modern Terraform internals.

**Comment by jtopjian** [comment]
@rfc1459 A fix for this has been merged and will be available in the next release.

If you're able to test from master, let us know if you run into any problems.

Thank you again for reporting this.
