### ISSUE TITLE
Bug in security groups

### ISSUE THREAD

**Issue by agorinenko** [terraform-providers/terraform-provider-openstack#60]
Hi there,

Provider has a bug on line 140

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_secgroup_v2.go#L140
You must write
updateOpts.Description = d.Get("description").(string)

**Comment by fatmcgav** [comment]
@agorinenko Ah, good spot... Feel free to raise a PR for the fix :)
