### ISSUE TITLE
openstack_lb_loadbalancer_v2.load_balancer creation fails with Resource not found (with vmware VIO 3.1)

### ISSUE THREAD

**Issue by nicfarges** [terraform-providers/terraform-provider-openstack#61]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.9.11 (logs shown below)
0.10.0 (fails with same error)
and VIO v3.1 (vmware integrated openstack)

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_lb_loadbalancer_v2.load_balancer

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "openstack_lb_loadbalancer_v2" "load_balancer" {
  name = "xyz"
  region = "nova"
  vip_subnet_id = "xxxxxxx"
}
```

### Debug Output
2017/08/04 17:08:33 [DEBUG] root: eval: *terraform.EvalIf
2017/08/04 17:08:33 [DEBUG] root: eval: *terraform.EvalWriteState
2017/08/04 17:08:33 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/08/04 17:08:33 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/08/04 17:08:33 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* openstack_lb_loadbalancer_v2.load_balancer: Error creating OpenStack LoadBalancer: Resource not found
2017/08/04 17:08:33 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* openstack_lb_loadbalancer_v2.load_balancer: Error creating OpenStack LoadBalancer: Resource not found
2017/08/04 17:08:33 [TRACE] [walkApply] Exiting eval tree: openstack_lb_loadbalancer_v2.load_balancer
2017/08/04 17:08:33 [DEBUG] dag/walk: upstream errored, not walking "provider.openstack (close)"
2017/08/04 17:08:33 [DEBUG] dag/walk: upstream errored, not walking "output.load_balancer_vip_address"
2017/08/04 17:08:33 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/08/04 17:08:33 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/08/04 17:08:33 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/08/04 17:08:33 [DEBUG] plugin: terraform.exe: terraform-provider (internal) 2017/08/04 17:08:33 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/08/04 17:08:33 [DEBUG] plugin: terraform.exe: openstack-provider (internal) 2017/08/04 17:08:33 [DEBUG] plugin: waiting for all plugin processes to complete...
Error applying plan:

1 error(s) occurred:

* openstack_lb_loadbalancer_2017/08/04 17:08:33 [DEBUG] plugin: C:\HashiCorp\Terraform\terraform.exe: plugin process exited
2017/08/04 17:08:33 [DEBUG] plugin: C:\HashiCorp\Terraform\terraform.exe: plugin process exited
v2.load_balancer: 1 error(s) occurred:

* openstack_lb_loadbalancer_v2.load_balancer: Error creating OpenStack LoadBalancer: Resource not found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
to create the load balancer

### Actual Behavior
it fails
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
terraform "plan" works well, but "apply" fails with assue above

**Comment by jtopjian** [comment]
@nicfarges Thank you for reporting this.

Is it possible that the cloud you are using does not support LBaaSv2? Are you able to create a load balancer using the `neutron` command-line tool?

If so, can you please provide the output of the following:

```shell
$ neutron --debug lbaas-loadbalancer-create ...
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

Also, just a heads up that VIO is not 100% compatible with OpenStack - the API works slightly differently. If this problem is an issue specific to VIO, it might be harder to resolve this issue.

**Comment by nicfarges** [comment]
hi...

thanks to the OS_DEBUG=1 in your last post, I actually realised what was the issue because the error message was more explicit, I was providing a network id instead of a subnet id as input for LB creation:

many thanks jtopjian ! :)

017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe: X-Openstack-Request-Id: req-6a99c19c-4fa4-49c4-a1ca-815dd76397be
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe: 2017/08/07 13:28:07 [DEBUG] OpenStack Response Body: {
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe:   "NeutronError": {
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe:     "detail": "",
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe:     "message": "Subnet 563cff96-dded-4dfb-968a-04897bab7287 could not be found.",
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe:     "type": "SubnetNotFound"
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe:   }
2017/08/07 13:28:07 [DEBUG] plugin: terraform-provider-openstack_v0.1.0_x4.exe: }
2017/08/07 13:28:07 [DEBUG] root: eval: *terraform.EvalWriteState
2017/08/07 13:28:07 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/08/07 13:28:07 [DEBUG] root: eval: *terraform.EvalIf
2017/08/07 13:28:07 [DEBUG] root: eval: *terraform.EvalWriteState
2017/08/07 13:28:07 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/08/07 13:28:07 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/08/07 13:28:07 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* openstack_lb_loadbalancer_v2.load_balancer: Error creating OpenStack LoadBalancer: Resource not found
2017/08/07 13:28:07 [ERROR] root: eval: *terraform.EvalSequence, Error applying plan:
