### ISSUE TITLE
Not possible to specify fixed_ip for openstack_networking_floatingip_associate_v2

### ISSUE THREAD

**Issue by OmegaSquad82** [terraform-providers/terraform-provider-openstack#646]
Hi there,

in certain configurations you'll need to use a workaround when trying to associate a pre-allocated Floating IP to a Networking port. Now OpenStack CLI (help output below shortened!) requires the statement of a fixed <ip-address> when a single Port has more than one of them. This currently is not supported by Terraform.

```bash
λ openstack floating ip set -h
usage: openstack floating ip set [-h] --port <port>
                                 [--fixed-ip-address <ip-address>]
                                 <floating-ip>

Set floating IP Properties

  <floating-ip>         Floating IP to associate (IP address or ID)
  --port <port>         Associate the floating IP with port (name or ID)
  --fixed-ip-address <ip-address>
                        Fixed IP of the port (required only if port has
                        multiple IPs)
```

### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
Please list the resources as a list, for example:
-  openstack_networking_floatingip_associate_v2

### Terraform Configuration Files
```hcl
# Bind Port to existing FIP but only use it if NO fixed_ip is being stated
resource "openstack_networking_floatingip_associate_v2" "association" {
  count = "${var.floating_ip != "" && var.fixed_ip == "" ? 1 : 0}"

  floating_ip = "${var.floating_ip}"
  #fixed_ip   = "${var.fixed_ip}" not supported, yet!
  port_id     = "${var.port_id}"
}
```

### Expected Behavior
Terraform should be enabled to support this feature of the OpenStack API.

### Actual Behavior
Can't create the resource and instead need to call as a workaround.

```bash
λ openstack floating ip set --port ${var.port_id} --fixed-ip-address ${var.fixed_ip} ${var.floating_ip}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This applies to OpenStack (Ocata) clouds using OpenContrail (v3.2!) with AVI Vantage (v17.2.12).

**Comment by jtopjian** [comment]
All sounds correct to me.

> In addition, the openstack_networking_floatingip_associate_v2 resource doesn't have an update method. Considering the new fixed_ip field, its worth adding it with further acceptance tests.

I think this will still work without an Update field. The behavior of the resource should match that of a floating IP being associated and disassociated: a single atomic action that shouldn't have to consider state during transitions.

**Comment by kayrus** [comment]
@jtopjian switching one fixed IP to another within the same port works, therefore we need to consider the update possibility.

**Comment by jtopjian** [comment]
Right - I get what you're saying, but it should be fine.

Ideally, this resource should behave like the `openstack_compute_floatingip_associate_v2` resource as much as possible, which includes recreating the resource upon any update.

`openstack_compute_floatingip_associate_v2` also has the same type of "create before destroy" issue you've described, but it's a legitimate situation when someone should _not_ create before destroy.

Let's stick with not having an Update function until there's a blocking situation that calls for Update.

**Comment by Id2ndR** [comment]
The `fixed_ip` field works, but there is no mention of it in [the corresponding documentation](https://www.terraform.io/docs/providers/openstack/r/networking_floatingip_associate_v2.html).
