### ISSUE TITLE
Unable to refresh the state of the nova compute

### ISSUE THREAD

**Issue by vikram-chandrakanth** [terraform-providers/terraform-provider-openstack#658]
Hi, 

Terraform is unable to refresh and pull the latest state of the compute resource, though the resource is successfully provisioned. It still destroys and re-creates on the next Run. 

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version
Terraform Version = 11.11.0
### Affected Resource(s)
 - openstack_compute_instance_v2 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "openstack_compute_instance_v2" "baremetal" {
  count = "${length(var.nodes)}"
  name  = "${lookup(var.nodes[count.index], "name")}"
  availability_zone = "::${lookup(var.nodes[count.index], "uuid")}"
  region    = "${var.region}"
  image_id  = "${var.image}"
  flavor_id = "${var.flavor}"
  key_pair  = "${var.key_pair}"
  security_groups = "${var.security_group}"

  network
  {
   uuid = "${var.access_network}"
   access_network = "true"
   fixed_ip_v4 = "${lookup(var.nodes[count.index], "fixed_ip")}"
  }
  
  
 network
{
  uuid = "${var.backup_network}"
}

  network
{
  uuid = "${var.storage_network}"
}

  network
{
  uuid = "${var.heart_beat_network}"
}


  lifecycle {
    prevent_destroy = true
  }


 timeouts {
    create = "45m"
    update = "30m"
    delete = "30m"
  }

}

### Debug Output ###

https://gist.github.com/vikram-chandrakanth/6b3535af5b16015726afc318ff1b6279 

### Panic Output

https://gist.github.com/vikram-chandrakanth/6b3535af5b16015726afc318ff1b6279

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by kayrus** [comment]
Hi @vikram-chandrakanth, it looks like you're using a [trick](https://docs.openstack.org/nova/rocky/admin/availability-zones.html) to provision the BM instance directly on the specific BM node UUID (`--availability-zone '::%node-UUID%'`). And once the BM instance is created, Openstack API returns the real availability zone (in your case `ap-ae-1a`), which terraform writes into the state file and then detects the conflict.

The problem could be resolved by improving the [suppressAvailabilityZoneDetailDiffs](https://github.com/terraform-providers/terraform-provider-openstack/blob/86a9650ec811d32c7b4388da3eaf2e974c11bc3d/openstack/resource_openstack_compute_instance_v2.go#L1258..L1269) function. I'll try to take a look on how it could be fixed.

**Comment by jtopjian** [comment]
Wouldn't the better approach be to modify the format of the availability zone? We already account for a format of `zone:host:node` or `zone:node` or `zone:host`: https://github.com/terraform-providers/terraform-provider-openstack/issues/288

According to https://docs.openstack.org/nova/rocky/admin/availability-zones.html, a format of `::node` doesn't seem to be a valid format. A zone should always be part of the specified AZ.

**Comment by kayrus** [comment]
@jtopjian indeed, the `::node` format is a hack, but it is used quite frequently for baremetal provisioning. 
According to the [nova code](https://github.com/openstack/nova/blob/bff3fd1cdbc441bf8d0bbe91099c2b2c57578b31/nova/compute/api.py#L457..L484), AZ is not a required parameter, and, if the node or host are specified, they are [preferable](https://github.com/openstack/nova/blob/bff3fd1cdbc441bf8d0bbe91099c2b2c57578b31/nova/compute/api.py#L1715..L1724) to AZ.
Therefore I'd prefer terraform to support this hack. If it hadn't been @vikram-chandrakanth, I'd have raised this problem anyway, since I have already started to work on baremetal use cases support.

**Comment by jtopjian** [comment]
That's a fair assessment and I understand the situation. This might be something better for #457.

`openstack_compute_instance_v2` is one step away from being marked legacy and deprecated, so I don't want to add any large changes to it.

Since specifying the AZ name in the `availability_zone` argument resolves this problem and considering the amount of changes required to make this hack work, I would prefer to just have users specify the AZ name.

**Comment by kayrus** [comment]
> and considering the amount of changes required to make this hack work

I understand that you don't want to add new features into the legacy code, but if you take a look on the updated PR I submitted, you'll see that I added only one field keeping the backward compatibility with older versions. I believe it doesn't add an extra complexity into the code.

**Comment by jtopjian** [comment]
Technically the implementation is simple - it's only a handful of lines. But the effect of that PR adds a distinct new feature which means new use-cases, missing use-cases, and possible bugs. 

Secondly, I need to be strict about not adding new functionality to `openstack_compute_instance_v2` for two reasons: it opens the door to further features ("you allowed that, but why not this?") and implies carry-over of additional features we need to include in the forthcoming `openstack_compute_server_v2` resource ("you recently added support for `availability_zone_hints` in `openstack_compute_instance_v2`, but it works differently in `openstack_compute_server_v2`. please fix this").

**Comment by ozerovandrei** [comment]
#985 was merged since we still haven't start any implementation of `openstack_compute_server_v2`.
