### ISSUE TITLE
Networking V2: add port bindings support

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#665]
This support would be appreciated for cases, when you need to create a custom port and attach it to the instance.

### Affected Resource(s)

- openstack_networking_port_v2 resource and data source

### References

https://github.com/gophercloud/gophercloud/tree/master/openstack/networking/v2/extensions/portsbinding

**Comment by pkqsun** [comment]
Thanks all.
Waiting for a new version of terraform-provider-openstack.
