### ISSUE TITLE
How to disable power_state checking?

### ISSUE THREAD

**Issue by vsb2007** [terraform-providers/terraform-provider-openstack#675]
Hi there,
### Terraform Version
```
Terraform v0.11.11
+ provider.openstack v1.15.1
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
```
Terraform will perform the following actions:

  ~ module.instance_dev_bitbucket.openstack_compute_instance_v2.instance-1
      power_state: "shutoff" => "active"
```
I don't want to check power state. How to disable?

**Comment by jtopjian** [comment]
@vsb2007 You can set the `power_state` option: https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#power_state

Alternatively, you can set `ignore_changes` in `lifecycle`: https://www.terraform.io/docs/configuration/resources.html#lifecycle

If either of these don't work, can you provide more information (such as the Terraform code) that is causing this problem?

**Comment by vsb2007** [comment]
```
  lifecycle {
    ignore_changes = [ "power_state" ]
  }
```
is working for me
Thx!

**Comment by jtopjian** [comment]
Perfect - thanks for confirming :)
