### ISSUE TITLE
Support LBaaS creation via network ID 

### ISSUE THREAD

**Issue by lukemgriffith** [terraform-providers/terraform-provider-openstack#683]
Since a recent commit I implemented into gophercloud, the octavia API now supports the creation of load balancers against a network id as well as a subnet id. 
 https://github.com/gophercloud/gophercloud/commit/b18d22ae2c8b9ef046c980e62422369b5aea953f

It would be great if support for this could be added into the openstack_lb_loadbalancer_v2 resource, at first glance I can see that an abstraction is used to select the client, due to the provider parameter to use octavia. 

https://github.com/terraform-providers/terraform-provider-openstack/blob/74dd02eaf72a36514f2179aa816a2365351ab841/openstack/resource_openstack_lb_loadbalancer_v2.go#L107

First time developing on this code base, any advise on best recommendations for how this could be done would be much appreciated.

**Comment by tdeckers** [comment]
Any work happened on this issue as far as you're aware?  Just checking before spending time. Thx!
