### ISSUE TITLE
Proposal: Split auth logic into its own module/repository

### ISSUE THREAD

**Issue by radeksimko** [terraform-providers/terraform-provider-openstack#686]
### Context

This provider (`terraform-providers/terraform-provider-openstack`) depends on `hashicorp/terraform` (like any other), because it consumes `helper/schema`. `hashicorp/terraform` also depends on `terraform-providers/terraform-provider-openstack` because it shares some auth logic in the Swift remote backend.

https://github.com/hashicorp/terraform/blob/master/backend/remote-state/swift/backend.go

This dependency cycle:

 - can cause confusion for anyone unaware (which is most people except handful of maintainers in these two repositories)
 - can cause version conflicts
    - all providers depend on `hashicorp/terraform` and therefore (as a result of the above) all providers depend on the openstack provider, so any version constraints of dependencies of this provider will constrain dependencies of other providers
 - accounts for unnecessary vendored dead code from transitive dependencies of the provider (basically everything that's unrelated to Swift) in both Terraform and all providers

### Shared auth logic

It is natural and right to have shared auth logic and not having to repeat the same code in two places. 👍 In fact we used to do the same thing with the AWS provider and S3 backend until very recently.
For the same reasons as described above though we decided to create a separate library:

https://github.com/hashicorp/aws-sdk-go-base
https://github.com/hashicorp/terraform/pull/20374 (that PR alone removed `1,3M` LOC)

### Proposal

We (_speaking on behalf of Terraform maintainers_) would love to see a similar library created for Swift/OpenStack-based auth, or any shared logic there is (and needs to be) between the Swift provider and OpenStack provider.

----

cc @jtopjian

**Comment by jtopjian** [comment]
@radeksimko I agree.

To expand on the details, the swift backend is consuming the `config` struct `LoadAndValidate` method: 

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L19
* https://github.com/hashicorp/terraform/blob/26174c814eaa38bef3de20795bb4bc24e0de16b6/backend/remote-state/swift/backend.go#L299
* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L57
* https://github.com/hashicorp/terraform/blob/26174c814eaa38bef3de20795bb4bc24e0de16b6/backend/remote-state/swift/backend.go#L326

In addition, there's already a decoupled package for handling OpenStack authentication here: https://github.com/gophercloud/utils/tree/master/openstack/clientconfig. The `LoadAndValidate` method is using this. The rest is just boilerplate.

Finally, it's worth noting that the Swift backend authentication is out of date. I submitted a PR for this (https://github.com/hashicorp/terraform/pull/18671) but I'm under the impression that v012 work is taking priority (which, to be clear, I'm fine with). Any work done here would supersede this previous work.

I can think of a few ways of handling this:

1. Reproduce the `config` struct for the Swift backend. I don't think this is the best long-term solution.
2. Create a decoupled package/repo _somewhere_. I can see about having a new repo created under the Gophercloud repo, but that might open the door to others wanting similar repos hosted under there. Given I'm the primary maintainer of Gophercloud but don't have full org permissions, it puts me in a sticky spot :)

    2a. I could create another package under `gophercloud/utils`. This has a slight chance of a dependency cycle, but I think it could work. It might seem odd that there's a Terraform-specific auth package in `gophercloud/utils`, but a utility is a utility... 🙂 

    2c. I could create a repo under my personal jtopjian github account.

    2d. Find some other appropriate org.

I'll look at doing 2a and see how far I get.

**Comment by radeksimko** [comment]
> Finally, it's worth noting that the Swift backend authentication is out of date. I submitted a PR for this ([hashicorp/terraform#18671](https://github.com/hashicorp/terraform/pull/18671)) but I'm under the impression that v012 work is taking priority (which, to be clear, I'm fine with). Any work done here would supersede this previous work.

I think the shared mood amongst most of us working on 0.12 is to avoid introducing more variables, unless absolutely necessary into that release, which already has many variables. That is why, despite bumping dependencies for some backends, we did not leverage any new functionality from these backends. The motivation there was merely to prevent conflicts in the dependency tree.

Is there any chance of bumping `terraform-provider/terraform-provider-openstack` (or potential future shared library we're talking about here) in `hashicorp/terraform` without also introducing more changes in the Swift backend?

I'm sure our users and everyone would be happy to see these updates in the Swift provider, but if we can separate that from dependency updates and delay that until after 0.12, that would be more than welcomed.

In regards to _where_ to put this library: I'd be fine with any of the suggested, your personal namespace included.

**Comment by jtopjian** [comment]
> Is there any chance of bumping `terraform-provider/terraform-provider-openstack` (or potential future shared library we're talking about here) in `hashicorp/terraform` without also introducing more changes in the Swift backend?

I think so. I'll see what I can do about making that work - maybe even just temporarily to help break the coupling.

**Comment by jtopjian** [comment]
@radeksimko I have an initial solution put together. gophercloud/utils#81 is pretty close to being a forklift of this provider's `config.go` file. There's probably room for refactoring, but that can be worked on separately. It might feel heavy-handed to move the entirety of `config.go`, but I figure it could also be used if anyone wanted to make additional OpenStack providers (for example, a public cloud based on OpenStack can use this as a foundation).

#688 implements this for this provider and it's working.

I modified the Swift backend to use this and it's also working: https://github.com/hashicorp/terraform/compare/master...jtopjian:backend-swift-auth

I didn't open a PR because I had some issues with the vendoring. For example, the etcd checksum was incorrect and I had to temporarily modify `go.sum` to fix the error. :man_shrugging: I'd be more than fine if someone from HC wanted to handle the vendoring side of things for this.

Thoughts about all?

**Comment by radeksimko** [comment]
@jtopjian This is looking pretty good. Thanks for all your effort. 👍 

etcd is on my list. It's one of the last dependencies that is still pinned to a version which isn't go-mod aware unfortunately and it brings a lot of dependencies of its own, which is most likely the reason for the mentioned version conflicts.

Unfortunately our tests for the etcd backend aren't passing currently, so we'll probably need to look into that first, before touching that dependency to make sure we don't break it even more. 😢

**Comment by jtopjian** [comment]
@radeksimko Sounds good. I can proceed with merging #688. Let me know when it would be appropriate to open a PR against core for the Swift backend side of things.
