### ISSUE TITLE
Instance assign to new created project

### ISSUE THREAD

**Issue by niuzhenguo** [terraform-providers/terraform-provider-openstack#698]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_identity_project_v3
- openstack_compute_instance

### Terraform Configuration Files
```hcl
provider.tf :

provider "openstack" {
  user_name = "${var.user_name}"
  tenant_name = "project1"
  password = "${var.password}"
  auth_url = "openstack cloud url";
  insecure = true
}

project.tf :

resource "openstack_identity_project_v3" "project" {
  name = "project2"
  description = "some description"
}

instance.tf :

resource "openstack_compute_instance_v2" "instance" {
 
  name           = "${var.instance_name}-tf"
  image_name     = "${var.image_name}"
  flavor_name   = "${var.flavor_name}"
  security_groups = ["default"]

  network {
    name = "${var.private_nw_name}"
  }
}
```

### Expected Behavior
Should have a way to assign the instance to the new created identity project.

### Actual Behavior
instance can only be create on the project that specified with the provider configuration. Is there any way to make a new provider configuration depends on the created project?

**Comment by kayrus** [comment]
Looks like it is not supported by an Openstack API. Openstack API extracts the [current user scope](https://github.com/openstack/nova/blob/727b942a88a812afb7368b4d7d3c314a4f8554ed/nova/api/openstack/compute/servers.py#L594..L597) to schedule an instance.

**Comment by jtopjian** [comment]
@kayrus It's not supported in the compute API. In the link you reference, `context` is most likely generated internally from the auth headers.

I'm about 99.9% sure the compute API does not support this. Unless I'm wrong about that, there is nothing we can do here.

**Comment by niuzhenguo** [comment]
@kayrus @jtopjian thanks for your quick response, the original discussion is here https://community.spiceworks.com/topic/2132677-terraform-openstack-instance-asign-to-created-project .
I'm just curious that is it possible to move project info and such to each resource like region?

**Comment by jtopjian** [comment]
@niuzhenguo Unfortunately that's not possible. Authentication is done in the overarching provider block:

```hcl
provider "openstack" {
  auth_url = ...
  user_name = ...
  tenant_name = ...
}
```

This creates what Gophercloud calls a Provider Client - meaning, a client that has authenticated to the cloud.

Each time Terraform manages a resource, it creates a Service Client. A service client is already authenticated to the cloud.

Project scope is done in the Provider Client. Region is done in the Service Client. This is why we can specify a region for each resource.

The only way for the Compute API to support creation of resources under another tenant is to copy what Neutron does and allow passing project ID information in each API request.

**Comment by niuzhenguo** [comment]
@jtopjian thanks for the explanation!

**Comment by jtopjian** [comment]
I'm going to close this issue, but please let me know if you'd like to discuss this further.
