### ISSUE TITLE
badRequest": {"message": "Invalid key_name provided.", "code": 400}}

### ISSUE THREAD

**Issue by mkhammar** [terraform-providers/terraform-provider-openstack#719]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.11
+ provider.openstack v1.16.0

### Affected Resource(s)
- Instance Key pair
error message: {"badRequest": {"message": "Invalid key_name provided.", "code": 400}}

I checked thousands of times and the name of my key pair in OpenStack and my terraform variable is matching. Can't understand...

Please help me.

Thanks

**Comment by jtopjian** [comment]
@mkhammar Thank you for opening the issue.

The error you're getting is from the OpenStack environment itself and not Terraform, but we can try to help.

Running in debug mode might help resolve the issue:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

And read through the JSON requests and responses.

If that doesn't help, please provide the full Terraform configuration that is triggering this error for you.

**Comment by mkhammar** [comment]
@jtopjian Thanks for the answer... I ran that command, but nothing obvious in the Debug logs...

deploy.tf:
`
resource "openstack_compute_instance_v2" "W7AOL10A" {
  count = "${var.Instance_count["W7AOL10A"]}"
  name = "${format("W7AOL10A-%02d", count.index+1)}"
  image_name = "${var.Instance_image["W7A"]}"
  flavor_name = "${var.Instance_flavor["2core"]}"
  key_pair = "${var.openstack_keypair["name"]}"
  security_groups = ["${var.tenant_securitygroup_SFO}"]
  network {
    name = "${var.tenant_network_SFO}"
  }
}
`

variables.tf:
`variable "openstack_user_name_SFO" {
  description = "The username for the Tenant."
  default  = "svc_test"
}

variable "openstack_tenant_name_SFO" {
  description = "The name of the Tenant."
  default  = "test"
}

variable "openstack_password" {
  description = "The password for the Tenant."
  default  = "xxxxxxxxx"
}

variable "openstack_auth_url" {
  description = "The endpoint url to connect to OpenStack."
  default  = "xxxxxxxx"
}

variable "openstack_keypair" {
  description = "The keypair to be used."
  default  = "RDKEY"
}

variable "tenant_network_SFO" {
  description = "The network to be used."
  default  = "xxxxxxxxxxxxxx"
}

variable "tenant_securitygroup_SFO" {
  description = "The security group to be used."
  default  = "xxxxxxxxxxxx"
}

variable "Instance_image" {
  description = "Image list"
  type = "map"
  default = {
    "W7A"     = "windows_7-2018.10.04"
    "W8A"     = "windows_8.1-2018.10.04"
    "W10A"    = "windows_10.1-2018.10.04"
    "W2K12R2" = "windows_server_2012r2-2018.10.04"
  }
}

variable "Instance_flavor" {
  description = "Flavor list"
  type = "map"
  default = {
    "1core"  = "ssku1H2017-1core"
    "2core"  = "ssku1H2017-2core"
    "4core"  = "ssku1H2017-4core"
    "8core"  = "ssku1H2017-8core"
    "16core" = "ssku1H2017-16core"
    "24core" = "ssku1H2017-24core"
    "32core" = "ssku1H2017-32core"
  }
}

variable "Instance_count" {
  description = "How many instances to create given their role"
  type = "map"
  default = {
    "W7AOL10A"	= "2"
    "W7AOL10B"	= "2"
    "W7AOL13A"	= "2"
    "W7AOL13B"	= "2"
    "W7AOL16A"	= "2"
    "W7AOL16B"	= "2"
    "W8AOL10A"	= "2"
    "W8AOL10B"	= "2"
    "W8AOL13A"	= "2"
    "W8AOL13B"	= "2"
    "W8AOL16A"	= "2"
    "W8AOL16B"	= "2"
    "W10AOL10A"	= "2"
    "W10AOL10B"	= "2"
    "W10AOL13A"	= "2"
    "W10AOL13B"	= "2"
    "W10AOL16A"	= "2"
    "W10AOL16B"	= "2"
    "W10AOL19A"	= "2"
    "W10AOL19B"	= "2"
    "W7BOL10B"	= "2"
    "W7BOL13B"	= "2"
    "W7BOL16B"	= "2"
    "W8BOL10B"	= "2"
    "W8BOL13B"	= "2"
    "W8BOL16B"	= "2"
    "W10BOL10B"	= "2"
    "W10BOL13B"	= "2"
    "W10BOL16B"	= "2"
    "W10BOL19B"	= "2"
  }
}
`

**Comment by jtopjian** [comment]
@mkhammar Can you try setting:

```hcl
key_pair = "${var.openstack_keypair}"
```

**Comment by mkhammar** [comment]
@jtopjian  Same error...

I modified as follow:
```
resource "openstack_compute_instance_v2" "W7AOL10A" {
  count = "${var.Instance_count["W7AOL10A"]}"
  name = "${format("W7AOL10A-%02d", count.index+1)}"
  image_name = "${var.Instance_image["W7A"]}"
  flavor_name = "${var.Instance_flavor["2core"]}"
  key_pair = "${var.openstack_keypair}"
  security_groups = ["${var.tenant_securitygroup_SFO}"]
  network {
    name = "${var.tenant_network_SFO}"
  }

```

Not better... :-/

**Comment by jtopjian** [comment]
@mkhammar Can you confirm that hard-coding the key name works? If so, then this is an issue with your HCL syntax and not a problem with the provider itself.

**Comment by jtopjian** [comment]
@mkhammar Also, please make sure the key actually exists in OpenStack.

**Comment by mkhammar** [comment]
@jtopjian  I did, several times... exact same name... 

Something weird, I tried with another project and another Key but on the same tenant, and it worked perfectly... so I suspected that the issue could be the key itself.

I tried to use the working key, create, recreate a new key, from my linux box or from OpenStack UI, but doesn't work better...

I'm getting confused and crazy... :-(

**Comment by mkhammar** [comment]
even when the Key_name is hard coded, I meet the same error...

**Comment by mkhammar** [comment]
if I'm creating instances with no Key_pairs, it works...

I can't understand...??!!

**Comment by jtopjian** [comment]
Please make sure you have created the key pair _before_ you are trying to launch an instance:

```shell
$ openstack keypair list
```

Or check the OpenStack Horizon dashboard.

**Comment by mkhammar** [comment]
I double checked, from the UI and OpenStack cli... the key is there, with the name used...

**Comment by jtopjian** [comment]
Please try running the following (and only the following):

```hcl
data "openstack_compute_keypair_v2" "kp" {
  name = "key-name"
}
```

If Terraform is not able to find a result, then you are authenticating to an area of your OpenStack cloud where the key does not exist -- perhaps a different region?

**Comment by mkhammar** [comment]
@jtopjian you drove me to right way !!! The key has been created with the admin user, while in terraform we were authenticated with a service user... so that's why the key was not accessible!
Stupid me!

Thanks for your time and your patience!
