### ISSUE TITLE
Remote-exec and Floating IP

### ISSUE THREAD

**Issue by VincenzoDo** [terraform-providers/terraform-provider-openstack#72]
Hello,

I've been using the direct floating IP association which is now in this latest version fully deprecated. So I'm modifying my template to use the new resource resource "openstack_networking_floatingip_v2" and "openstack_compute_floatingip_associate_v2".

The problem I'm having is that the Floating IP is associated only after the VM is created, so my  provisioner "remote-exec" which is inside the VM creation block can't be executed.

Furthermore, the examples provided in this repository are not up to date as they still use the deprecated resource.

### Terraform Version
terraform -v
Terraform v0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_networking_floatingip_v2
- openstack_compute_floatingip_associate_v2
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl

resource "openstack_networking_floatingip_v2" "float_ip" {
  region = "${var.region}"
  pool   = "${lookup(var.pub_net_id, var.region)}"
  count  = "${ var.nb_of_nodes }"
}

resource "openstack_compute_floatingip_associate_v2" "float_ip" {
  floating_ip = "${openstack_networking_floatingip_v2.float_ip.address}"
  instance_id = "${openstack_compute_instance_v2.terravm.id}"
}


resource "openstack_compute_instance_v2" "terravm" {
  name        = "${var.vmname}"
  count       = "${var.nb_of_nodes}"
  key_pair    = "${var.ssh_key_name}"
  region      = "${var.region}"
  flavor_name = "${var.flavor}"

  # image_id must be specified when destination_type=local
  image_id = "${ var.volume_enable==1 ? "" : lookup(var.image, var.region) }"

  # boot device on a volume 
  block_device {
    uuid                  = "${lookup(var.image, var.region)}"
    source_type           = "image"
    volume_size           = 16                                               
    boot_index            = 0
    destination_type      = "${ var.volume_enable==1 ? "volume" : "local" }"
    delete_on_termination = true
  }

  # if custom ports are needed, see TODO.md
  security_groups = "${var.security_groups}"

  metadata {
    owner       = "${var.owner}"
    description = "${var.description}"
  }

  network {
    name = "${var.network}"
  }

  connection {
    user    = "${var.user_login}"
    timeout = "1m"
    agent   = "${ var.ssh_agent_enable==1 ? true : false}"
  }

  # Provisioning
  provisioner "local-exec" {
    command = "ssh-keygen -R ${element(openstack_compute_floatingip_v2.float_ip.*.address,count.index)}"
  }
  provisioner "remote-exec" {
    inline = ["echo provisioned via terraform- ip ${element(openstack_compute_floatingip_v2.float_ip.*.address,count.index)} |sudo tee -a /etc/mm", "date"]
  }
  
  provisioner "file" {
    source      = "${var.custom_script}"
    destination = "/tmp/custom.sh"
  }

}
```

### Debug Output
VM gets created but no floating IP is associated since terraform is stuck in executing the remote-execs.

### Expected Behavior
Floating IP should be associated during VM creation.

### Actual Behavior
No Floating IP was associated to the VM

### Steps to Reproduce
 `terraform apply`

### Important Factoids
Running Openstack Mitaka

**Comment by jtopjian** [comment]
@VincenzoDo You'll want to move your remote-exec and other provisioning steps to either the `openstack_compute_floatingip_associate_v2` resource or a `null_resource`. The latter is preferable and is a common place to put provisioning steps in Terraform.

Thank you for the note about the outdated examples. We'll get these either updated.

**Comment by VincenzoDo** [comment]
@jtopjian Thank you for the fast reply! Ok will do that!
