### ISSUE TITLE
[v0.12] undefined: dynblock.ForEachVariablesHCLDec

### ISSUE THREAD

**Issue by dleske** [terraform-providers/terraform-provider-openstack#720]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Built v0.12.0-beta1 in $GOPATH, in order to build plugin according to instructions in #548.  Prior to this had downloaded release archive for same and was going to use that.

### Affected Resource(s), Terraform configs, Debug output, Panic output

None.  Build issue.

### Expected Behavior

Expected (hoped for) a successful `make build`.

### Actual Behavior

```
$ govendor fetch github.com/hashicorp/terraform/...@v0.12.0-beta1
$ govendor fetch github.com/hashicorp/hcl2/...
$ govendor fetch github.com/golang/protobuf/...@v1.2.0
$ govendor fetch github.com/zclconf/go-cty/...
$ govendor fetch github.com/hashicorp/go-plugin/...
$ govendor fetch github.com/hashicorp/go-version/...
$ make build
==> Checking that code complies with gofmt requirements...
go install
# github.com/terraform-providers/terraform-provider-openstack/vendor/github.com/hashicorp/terraform/lang
vendor/github.com/hashicorp/terraform/lang/eval.go:28:16: undefined: dynblock.ForEachVariablesHCLDec
make: *** [build] Error 2
```

### Steps to Reproduce

```
$ go version
go version go1.12.1 darwin/amd64
$ go env > /tmp/go.env
$ . /tmp/go.env
$ cd $GOPATH/src/github.com
$ mkdir hashicorp
$ cd hashicorp
$ git clone <terraform>
$ cd terraform
$ make tools
$ make
$ make dev
$ go get github.com/terraform-providers/terraform-provider-openstack
$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack
$ git checkout -b v012-testing-20190326
$ govendor fetch...
$ ...
$ make build

### Important Factoids

I'm a Go beginner and do not have a thorough understanding of Go build tools or environment. 

As I was submitted the update @topjian replied.

### References

#548 - followed these instructions, as best I could.

**Comment by jtopjian** [comment]
@dleske I think you're referring to the instructions in #548? If so, those were unfortunately outdated. I have just updated the issue with, what should be, the current commands.

**Comment by dleske** [comment]
@topjian Thanks, I will have a look.  I am actually still editing the issue, I edited the title and submitted by mistake--this issue might not actually make sense yet.  I'll look at your updated instructions! :)

**Comment by dleske** [comment]
That fixes this build issue.  Thanks @topjian, much appreciated.
