### ISSUE TITLE
Support for Heat Stacks

### ISSUE THREAD

**Issue by xinau** [terraform-providers/terraform-provider-openstack#731]
support for heat stacks in terraform, like the [aws cloudformation stack resource](https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html) or [data source](https://www.terraform.io/docs/providers/aws/d/cloudformation_stack.html)

**Comment by npu21** [comment]
+1
we need this feature too

**Comment by tookko** [comment]
+1 we need this as well

**Comment by ppcololo** [comment]
+1 I think everybody needs this feature

**Comment by styk-tv** [comment]
+1 for ability to launch heat templates through openstack providers AND ability to feed vars into heat templates through terraform and from existing terraform states and/or stack variables.

**Comment by rv0147** [comment]
+1 - this will be a good feature to support and launch heat templates same like cfn

**Comment by a101078** [comment]
+1 - we'd like to see this implementation.

**Comment by ozerovandrei** [comment]
`openstack_orchestration_stack_v1 ` was implemented in #944 and will be available in `1.25.0` release of the provider.
