### ISSUE TITLE
Terraform doesn't respect the fixed_ip argument

### ISSUE THREAD

**Issue by marsavela** [terraform-providers/terraform-provider-openstack#732]
Hi there,

Setting a `fixed_ip_v6` on the network of a `openstack_compute_instance_v2` doesn't work. The instance gets created with a totally different IP and then if you try to apply again, it will recreate the instance because it sees that it has a different IP. 

Maybe #646 is related.

### Terraform Version
Terraform v0.11.11
+ provider.openstack v1.17.0

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl
# Configure the OpenStack Provider
provider "openstack" {
    cloud = "openstack"
}

# Create a new instance resource
resource "openstack_compute_instance_v2" "smarsave_test" {
  name            = "smarsave_test"
  image_name      = "bionic-server-cloudimg-amd64"
  flavor_name     = "myflavor"
  key_pair        = "mykey"
  security_groups = ["default", "other_group"]
  
  network {
    name = "myIPv46network"
    fixed_ip_v6 = "[240b:c010:101:53e9:2501::30]" # Works with/without square brackets
  }
}
```

### Expected Behavior
VM should have the specified IPv6

### Actual Behavior
Terraform doesn't care about the specified IP and does'n take into consideration the `fixed_ip_v6` argument.

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by jtopjian** [comment]
Thank you for reporting this. 

I apologize, but it looks like we have an error in our documentation `fixed_ip_v6` is a "read-only" attribute. You cannot set a static IPv6 address directly on an instance - only an IPv4 address: https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/servers/requests.go#L99

I think the only way to set this is through an `openstack_networking_port_v2` resource.
