### ISSUE TITLE
Port binding support of PolicyNotAuthorized

### ISSUE THREAD

**Issue by pkqsun** [terraform-providers/terraform-provider-openstack#756]
Hi there,

Currently I encountered a port bonding issue with openstack_networking_port_v2.

### Terraform Version
Terraform v0.11.13
terraform-provider-openstack_v1.17.0_x4

### Affected Resource(s) and Terraform Configuration Files

resource "openstack_networking_port_v2" "port_net-02_v4" {
    name = "${var.name_prefix}-${var.hostname}"
    network_id = "${var.net-02_net_uuid}"
    admin_state_up = "true"

    binding = {
        vnic_type = "direct"
    }
    security_group_ids = [
  ]
    fixed_ip {
        "subnet_id" = "${var.net-02_v4_sub_uuid}"
    }
    count = "${var.count}"
}

### Debug Output

2019-05-22 01:34:20,216 DEBUG: * module.eason-worker-01.openstack_networking_port_v2.port_net-02_v4: 1 error(s) occurred:
2019-05-22 01:34:20,216 DEBUG: 
2019-05-22 01:34:20,217 DEBUG: * openstack_networking_port_v2.port_net-02_v4: Error creating openstack_networking_port_v2: Request forbidden: [POST https://10.4.166.166:13696/v2.0/ports], error message: {"NeutronError": {"message": "(((rule:create_port and rule:create_port:binding:profile) and rule:create_port:fixed_ips) and rule:create_port:binding:vnic_type) on {'binding:host_id': <neutron_lib.constants.Sentinel object at 0x345ffd0>, u'name': u'eason-worker-01', 'allowed_address_pairs': <neutron_lib.constants.Sentinel object at 0x345ffd0>, u'admin_state_up': True, u'network_id': u'**7113fc5d-a805-437c-ac2e-442acc6e7b82**', 'tenant_id': u'498c8a0646e34dccbe2fd598e9059f95', 'extra_dhcp_opts': None, 'mac_address': <neutron_lib.constants.Sentinel object at 0x345ffd0>, u'binding:vnic_type': u'direct', 'device_owner': '', 'qos_policy_id': None, 'device_id': '', 'port_security_enabled': <neutron_lib.constants.Sentinel object at 0x345ffd0>, u'binding:profile': {}, 'project_id': u'498c8a0646e34dccbe2fd598e9059f95', u'fixed_ips': [{u'subnet_id': u'**316c3c7a-fa99-45d0-ae00-fb31e1372734**'}], 'security_groups': <neutron_lib.constants.Sentinel object at 0x345ffd0>, 'description': ''} by {'domain': None, 'project_name': u'xxxx', 'tenant_name': u'xxxx', 'project_domain': None, 'timestamp': '2019-05-22 01:34:18.897611', 'auth_token': 'db015113f5a247989ca71d81e70203ab', 'resource_uuid': None, 'is_admin': False, 'user': u'7aea1ee662874a29b9d0a11ae2303df5', 'tenant': u'498c8a0646e34dccbe2fd598e9059f95', 'read_only': False, 'project_id': u'498c8a0646e34dccbe2fd598e9059f95', 'user_id': u'7aea1ee662874a29b9d0a11ae2303df5', 'show_deleted': False, 'roles': [u'_member_'], 'user_identity': u'7aea1ee662874a29b9d0a11ae2303df5 498c8a0646e34dccbe2fd598e9059f95 - - -', 'tenant_id': u'498c8a0646e34dccbe2fd598e9059f95', 'is_admin_project': True, 'request_id': 'req-73646982-9625-4f09-8796-6b63628e2bbb', 'user_domain': None, 'user_name': u'xxxx'} disallowed by policy", "type": "PolicyNotAuthorized", "detail": ""}}

2019-05-22 01:34:14,068 DEBUG: module.eason-worker-01.openstack_networking_port_v2.port_net-02_v4: Creating...
2019-05-22 01:34:14,068 DEBUG:   admin_state_up:           "" => "true"
2019-05-22 01:34:14,068 DEBUG:   all_fixed_ips.#:          "" => "<computed>"
2019-05-22 01:34:14,068 DEBUG:   all_security_group_ids.#: "" => "<computed>"
2019-05-22 01:34:14,068 DEBUG:   all_tags.#:               "" => "<computed>"
2019-05-22 01:34:14,069 DEBUG:   binding.#:                "" => "1"
2019-05-22 01:34:14,069 DEBUG:   binding.0.vif_details.%:  "" => "<computed>"
2019-05-22 01:34:14,069 DEBUG:   binding.0.vif_type:       "" => "<computed>"
2019-05-22 01:34:14,069 DEBUG:   binding.0.vnic_type:      "" => "direct"
2019-05-22 01:34:14,069 DEBUG:   device_id:                "" => "<computed>"
2019-05-22 01:34:14,069 DEBUG:   device_owner:             "" => "<computed>"
2019-05-22 01:34:14,069 DEBUG:   dns_assignment.#:         "" => "<computed>"
2019-05-22 01:34:14,070 DEBUG:   fixed_ip.#:               "" => "1"
2019-05-22 01:34:14,070 DEBUG:   fixed_ip.0.subnet_id:     "" => "316c3c7a-fa99-45d0-ae00-fb31e1372734"
2019-05-22 01:34:14,070 DEBUG:   mac_address:              "" => "<computed>"
2019-05-22 01:34:14,070 DEBUG:   name:                     "" => "eason-worker-01"
2019-05-22 01:34:14,070 DEBUG:   network_id:               "" => "7113fc5d-a805-437c-ac2e-442acc6e7b82"
2019-05-22 01:34:14,070 DEBUG:   port_security_enabled:    "" => "<computed>"
2019-05-22 01:34:14,070 DEBUG:   region:                   "" => "<computed>"
2019-05-22 01:34:14,070 DEBUG:   tenant_id:                "" => "<computed>"

However, when I use openstack CLI, it works:

[eason-dp:/opt/terraform/openstack/resources]# openstack port create --network 7113fc5d-a805-437c-ac2e-442acc6e7b82 --fixed-ip subnet=316c3c7a-fa99-45d0-ae00-fb31e1372734 --vnic-type direct  es-test-sriov-2 
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                   | Value                                                                                                                                                                                  |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| admin_state_up          | UP                                                                                                                                                                                     |
| allowed_address_pairs   |                                                                                                                                                                                        |
| binding_host_id         | None                                                                                                                                                                                   |
| binding_profile         | None                                                                                                                                                                                   |
| binding_vif_details     | None                                                                                                                                                                                   |
| binding_vif_type        | None                                                                                                                                                                                   |
| binding_vnic_type       | direct                                                                                                                                                                                 |
| created_at              | 2019-05-22T02:52:07Z                                                                                                                                                                   |
| data_plane_status       | None                                                                                                                                                                                   |
| description             |                                                                                                                                                                                        |
| device_id               |                                                                                                                                                                                        |
| device_owner            |                                                                                                                                                                                        |
| dns_assignment          | None                                                                                                                                                                                   |
| dns_domain              | None                                                                                                                                                                                   |
| dns_name                | None                                                                                                                                                                                   |
| extra_dhcp_opts         |                                                                                                                                                                                        |
| fixed_ips               | ip_address='10.76.98.75', subnet_id='316c3c7a-fa99-45d0-ae00-fb31e1372734'                                                                                                             |
| id                      | 410650b5-41b5-45c2-83ba-aff0c8519fbb                                                                                                                                                   |
| location                | Munch({'project': Munch({'domain_id': None, 'id': u'498c8a0646e34dccbe2fd598e9059f95', 'name': 'xxxx', 'domain_name': None}), 'cloud': '', 'region_name': '', 'zone': None}) |
| mac_address             | fa:16:3e:9f:dc:64                                                                                                                                                                      |
| name                    | es-test-sriov-2                                                                                                                                                                        |
| network_id              | 7113fc5d-a805-437c-ac2e-442acc6e7b82                                                                                                                                                   |
| port_security_enabled   | True                                                                                                                                                                                   |
| project_id              | 498c8a0646e34dccbe2fd598e9059f95                                                                                                                                                       |
| propagate_uplink_status | None                                                                                                                                                                                   |
| qos_policy_id           | None                                                                                                                                                                                   |
| resource_request        | None                                                                                                                                                                                   |
| revision_number         | 6                                                                                                                                                                                      |
| security_group_ids      | 228fa7f2-a097-413a-9633-085f5de80dce                                                                                                                                                   |
| status                  | DOWN                                                                                                                                                                                   |
| tags                    |                                                                                                                                                                                        |
| trunk_details           | None                                                                                                                                                                                   |
| updated_at              | 2019-05-22T02:52:07Z                                                                                                                                                                   |
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I just want to make sure it is OpenStack policy issue, then I could raise a ticket to change it by lab admin or my usage of terraform binding block  is incorrect?

Thanks in advance.

**Comment by kayrus** [comment]
could you please provide the detailed debug output as a github gist for both terraform and openstack output?
For terraform you can use `TF_LOG=DEBUG` and  `OS_DEBUG=true` environment variables.
For openstack cli you can use `--debug` flag.

**Comment by pkqsun** [comment]
Hello,
Here is the link of github gist. please help to check.
https://gist.github.com/pkqsun/e7a06b28f5776fca8db4f9c3f02b010d

**Comment by kayrus** [comment]
@pkqsun I have two notes:
* please remove the password from the debug log. I created a PR to mask v2 auth credentials.
* please show the `openstack port create ...` debug output, not the `openstack server add port`, it is a different API call.

**Comment by pkqsun** [comment]
@kayrus ,
Thanks for your reminder.
Added openstack port create logs.

**Comment by kayrus** [comment]
Here is the request sent by openstack CLI:

```json
{
  "port": {
    "network_id": "7113fc5d-a805-437c-ac2e-442acc6e7b82",
    "binding:vnic_type": "normal",
    "fixed_ips": [
      {
        "subnet_id": "316c3c7a-fa99-45d0-ae00-fb31e1372734"
      }
    ],
    "name": "es-sriov-port-5",
    "admin_state_up": true
  }
}
```

Here si the request sent by terraform:

```json
{
  "port": {
    "admin_state_up": true,
    "binding:profile": {},
    "binding:vnic_type": "direct",
    "fixed_ips": [
      {
        "subnet_id": "316c3c7a-fa99-45d0-ae00-fb31e1372734"
      }
    ],
    "name": "eason-worker-01",
    "network_id": "7113fc5d-a805-437c-ac2e-442acc6e7b82"
  }
}
```

The only difference I see is an empty `binding:profile` sent by terraform and the `binding:vnic_type` is different: `normal` vs `direct`. Nevertheless, try to compile this [branch](https://github.com/kayrus/terraform-provider-openstack/tree/omit-binding-profile) and let me know whether the issue still persists.

**Comment by pkqsun** [comment]
@kayrus ,

Maybe I found the root cause.
Since --binding-profile is optional, so  it seems that Terraform request need to remove this empty item.

I created a port "es-sriov-port-6" with "binding:vnic_type": "direct" and without specify the "binding:profile". (successfully finished)

openstack port create --network 7113fc5d-a805-437c-ac2e-442acc6e7b82 --fixed-ip subnet=316c3c7a-fa99-45d0-ae00-fb31e1372734 --vnic-type direct es-sriov-port-6 --debug

{
  "port": {
    "network_id": "7113fc5d-a805-437c-ac2e-442acc6e7b82",
    "binding:vnic_type": "direct",
    "fixed_ips": [
      {
        "subnet_id": "316c3c7a-fa99-45d0-ae00-fb31e1372734"
      }
    ],
    "name": "es-sriov-port-6",
    "admin_state_up": true
  }
}

Then I created a port "es-sriov-port-7" with "binding:vnic_type": "direct" and specify the "binding:profile" {}. This time it failed with the same error of terraform reported.

openstack port create --network 7113fc5d-a805-437c-ac2e-442acc6e7b82 --fixed-ip subnet=316c3c7a-fa99-45d0-ae00-fb31e1372734 --vnic-type direct --binding-profile {}  es-sriov-port-7  --debug

{
  "port": {
    "name": "es-sriov-port-7",
    "admin_state_up": true,
    "network_id": "7113fc5d-a805-437c-ac2e-442acc6e7b82",
    "binding:vnic_type": "direct",
    "binding:profile": {},
    "fixed_ips": [
      {
        "subnet_id": "316c3c7a-fa99-45d0-ae00-fb31e1372734"
      }
    ]
  }
}

Failed message:
{"NeutronError": {"message": "(((rule:create_port and rule:create_port:binding:profile) and rule:create_port:fixed_ips) and rule:create_port:binding:vnic_type), ... 
disallowed by policy", "type": "PolicyNotAuthorized", "detail": ""}}


Detailed logs is in gist named file port-create-direct.log  and  port-create-direct-with-profile.log .

**Comment by pkqsun** [comment]
@jtopjian , kindly ping.

**Comment by jtopjian** [comment]
@pkqsun ack

The solution to this is being discussed here (https://github.com/gophercloud/gophercloud/pull/1579). We'll get this resolved shortly. :slightly_smiling_face:

**Comment by pkqsun** [comment]
@jtopjian , Got it. 
Thanks and waiting for the fix.  🙂
