### ISSUE TITLE
how to configure openstack_lb_listener_v2 with an SSL certificate

### ISSUE THREAD

**Issue by nicfarges** [terraform-providers/terraform-provider-openstack#76]
Hi there,

I am trying to create a load balancer with VIO 3.1, with multiple listeners, each listening on SSL and routing traffic on members with SSL enabled also. I have managed to create a load balancer with a listener with protocol HTTPS, and it works. given that I did not specify any certificate, I get on my browser, when I type the VIP of the LB, the NET::ERR_CERT_AUTHORITY_INVALID message.. the certificate is probably auto generated.

my goal is to configure the LB listener with a SSL certificate I already have.

When I look the documentation of the openstack_lb_listener_v2, I see the parameter default_tls_container_ref but have no idea on how to use it, from the web documentation

my questions are: can we have more documentation and an example for 
1/ an openstack lb / listener TF config with an existing SSL certificate ? 
2/ an openstack lb / listener TF config with the terraform TLS provider (which shows a generation of certificate and an integration with the openstack lb)

thank you !
terraform is a great tool, thank you for all your work

### Terraform Version
0.9.11

### Affected Resource(s)
openstack_lb_loadbalancer_v2
openstack_lb_listener_v2

### Terraform Configuration Files
no specific config file

### Debug Output
no specific output

### Panic Output
n/a

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
n/a

### Important Factoids
running on VIO 3.1 with terraform openstack

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by nicfarges** [comment]
there is a parameter default_tls_container_ref on the openstack_lb_listener_v2 resource... I was confused at first because of lack of documentation on terraform web page, but found out that this is a reference to the secret in openstack secret repository (barbican: https://wiki.openstack.org/wiki/Barbican)... hence there is no issue in terraform per se, just a lack of documentation to my taste... 

for the resource property default_tls_container_ref, I would put a doc comment like "A reference to a container of TLS secrets, (typically a URL to the TLS secret, which is managed by the openstack secret repository, please refer to openstack secret manager for more info)"

**Comment by jtopjian** [comment]
@nicfarges Thanks for following-up. I had actually meant to get back to you about this later today or tomorrow.

Yep, you're right, the `default_tls_container_ref` is a reference to Barbican, which isn't supported in Terraform yet. If your OpenStack cloud has a Barbican service, you can configure the TLS stuff separately and then refer to it in the `default_tls_container_ref` setting.

One other item that I was looking into (hence the delay in getting back to you) was that the LBaaSv2 Horizon plugin has a section where you can paste a certificate. I just wanted to confirm that this won't actually work unless there's a Barbican service. I still need to look at this.

I agree that we need to document this a bit more. I'm going to re-open this issue and tag it as documentation just so we don't lose track of it.
