### ISSUE TITLE
QoS policies and rules support

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-providers/terraform-provider-openstack#760]
This provider should support OpenStack Networking V2 QoS policies, rules and `qos_policy_id` field in the network and port resources.

Upstream progress is tracked in [#1027](https://github.com/gophercloud/gophercloud/issues/1027).

**Comment by ozerovandrei** [comment]
@jtopjian I was thinking about design of those resources and I think that it is better to implement it in that way:
 - `qos_policy_id` field in the existing network and port resources/datasources;
 - `qos_policy` resource/datasource that won't contain any rules given that this field is too dynamic;
 - `qos_bandwidth_limit_rule` resource/datasource;
 - `qos_dscp_marking_rule` resource/datasource;
 - `qos_minimum_bandwidth_rule` resource/datasource.

What do you think?

**Comment by jtopjian** [comment]
@ozerovandrei Yep, that sounds good to me.

Just to confirm, though, the resource names will be something like `openstack_networking_qos_policy_v2`, `openstack_networking_qos_bandwidth_limit_rule_v2`, etc. I know some of these names will be quite long, but it'll be consistent with other names.

**Comment by ozerovandrei** [comment]
Yeah they will have exactly those names.
