### ISSUE TITLE
Removal of hashicorp/terraform/flatmap dependency

### ISSUE THREAD

**Issue by radeksimko** [terraform-providers/terraform-provider-openstack#767]
👋 

We're currently in first planning phases of decoupling `hashicorp/terraform`'s `helper` packages into what we'll soon call SDK. As part of preparation work for this decoupling I have analysed all active official providers and found OpenStack to be using one particular legacy package - `flatmap`.

https://github.com/terraform-providers/terraform-provider-openstack/search?q=flatmap&unscoped_q=flatmap

There's no particular deadline we set for sunsetting that package and removing it from Terraform's core, but there are some chances it might not make it to the initial decoupled version of SDK which will otherwise be more or less copy and compatible with the API currently exposed via `helper` packages in Terraform.

It seems that this package is only used for extraction of 1 field from the `map[string]string` state exposed to the test framework. The future SDK (not the initial one) is likely going to use [cty](https://github.com/zclconf/go-cty) to represent typed data from state/configuration. Terraform 0.12 already uses cty internally, but there's more work to do in regards to exposing this fact to providers.

Therefore there isn't any more elegant solution at this point other than hard-coding the test data as `[]interface{}` - this is what pretty much all other (official) providers do today.

**Comment by jtopjian** [comment]
This should be resolved in #772. As the comments in #772 states: I don't believe it's a full solution (we'll need to revisit with a more modern method of inspecting the state of test resources), but at least our dependency on flatmap is gone.
