### ISSUE TITLE
How to get details of current provider (in module)

### ISSUE THREAD

**Issue by jgeorgeson** [terraform-providers/terraform-provider-openstack#785]
I'm trying to write some modules for OpenStack resources, and the `openstack_compute_instance_v2` resource doesn't take a project/tenant argument. Instead it seems to only create the instance in the project authenticated to in the provider configuration.

Within the module, I would like to up at least the project that I'm authenticated against. While I _can_ pass the project name to each module use the data source by name, but I'd prefer if there is a way to do access the provisioner details or use a data source on the current provisioner. 

### Terraform Version
```
$ terraform --version
Terraform v0.11.14
+ provider.openstack v1.19.0
```

### Terraform Configuration Files

Caller 

```hcl
provider "openstack" {
  alias       = "project"
  auth_url    = "${var.openstack_auth_url}"
  tenant_name = "myproject"
}

module "instances-rh7-2d" {
  source = "..."

  providers = {
    openstack = "openstack.project"
  }

  network_name       = "tenant-net-rd"
  instances          = 3
  image              = "com.lgc.rhel7.base-0.4"
  flavor             = "2d.large"
  key_name           = "devops_ansible_key"
}
```

Module 

```hcl
data "openstack_compute_instance_v2" "current" {
    current = true
}
```

Using the data resource with no arguments appears to return the full list of projects visible to the user I'm authenticating as.

### References

https://github.com/hashicorp/terraform/issues/9221

**Comment by jtopjian** [comment]
> the openstack_compute_instance_v2 resource doesn't take a project/tenant argument. Instead it seems to only create the instance in the project authenticated to in the provider configuration.

This is correct. The OpenStack Compute API does not support project scoping per resource like the Networking API does.

The [`openstack_identity_auth_scope_v3`](https://www.terraform.io/docs/providers/openstack/d/identity_auth_scope_v3.html) data source will retrieve information about the current authenticated use (ie: the user configured in the provider). Does this help?

**Comment by jgeorgeson** [comment]
Wellllll that's exactly what I was looking for! With the amount of googling I did over the last two days I'm rather annoyed I didn't happen upon that myself. Thanks.

PS - I meant to put `data "openstack_identity_project_v3" "current"` in the example module code.
