### ISSUE TITLE
Slow VM creation on v0.10.2 (from 2 to 5+ mins)

### ISSUE THREAD

**Issue by VincenzoDo** [terraform-providers/terraform-provider-openstack#79]
Hello,

### Terraform Version
v0.10.2

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2
- block_device

### Terraform Configuration Files
```hcl
resource "openstack_networking_floatingip_v2" "float_ip" {
  region = "${var.region}"
  pool   = "${lookup(var.pub_net_id, var.region)}"
  count  = "${ var.nb_of_nodes }"
}

resource "openstack_compute_floatingip_associate_v2" "float_ip" {
  floating_ip = "${openstack_networking_floatingip_v2.float_ip.address}"
  #instance_id = "${openstack_compute_instance_v2.terravm.id}"
  instance_id = "${openstack_compute_instance_v2.terravm.id}"
}


resource "openstack_compute_instance_v2" "terravm" {
  name        = "${var.vmname}"
  count       = "${var.nb_of_nodes}"
  key_pair    = "${var.ssh_key_name}"
  region      = "${var.region}"
  flavor_name = "${var.flavor}"

  # image_id must be specified when destination_type=local
  image_id = "${ var.volume_enable==1 ? "" : lookup(var.image, var.region) }"

  # boot device on a volume i.e. will survive a computer node reboot
  block_device {
    uuid                  = "${lookup(var.image, var.region)}"
    source_type           = "image"
    volume_size           = 16                                               
    boot_index            = 0
    destination_type      = "${ var.volume_enable==1 ? "volume" : "local" }"
    delete_on_termination = true
  }

  # if custom ports are needed, see TODO.md
  security_groups = "${var.security_groups}"

  metadata {
    owner       = "${var.owner}"
    description = "${var.description}"
  }

  network {
    name = "${var.network}"
  }

  connection {
    # how terraform SSHs into the vm
    user    = "${var.user_login}"
    timeout = "1m"
    agent   = "${ var.ssh_agent_enable==1 ? true : false}"
  }

}

resource "null_resource" "remoteexecs" {

  depends_on = ["openstack_compute_instance_v2.terravm"]

  connection {
    # how terraform SSHs into the vm
    host    = "${element(openstack_networking_floatingip_v2.float_ip.*.address,count.index)}"
    user    = "${var.user_login}"
    timeout = "1m"
    agent   = "${ var.ssh_agent_enable==1 ? true : false}"
  }

  # Provisioning

  # First remove previous ssh host key (in case the VM IP is reused)
  provisioner "local-exec" {
    command = "ssh-keygen -R ${element(openstack_networking_floatingip_v2.float_ip.*.address,count.index)}"
  }
}
```

### Debug Output
v0.10.2 output: https://paste.ubuntu.com/25363077/
v0.9.x output: https://paste.ubuntu.com/25363115/

### Expected Behavior
VM creation is way faster ( almost 4 minutes) between version 0.9.x and 0.10.x, from what I can see this time is due to the block_device resource but I'm not 100% sure.

### Actual Behavior
VM gets created after 5 min on v 0.10
VM gets created after 1-2min on v0.9

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Openstack Mitaka, the recipe used is the same except for the floating_ip resource which is deprecated in v0.10.x. The infrastructure on which the VMs are deployed is the same and the time difference is almost the same at each creation.

Please let me know if you need additional info.

**Comment by jtopjian** [comment]
Hello,

The only possible issue I can think of is that the `null_resource` is being triggered before the floating IP is attached.

In your `null_resource`, try changing:

```hcl
depends_on = ["openstack_compute_instance_v2.terravm"]
```

to

```
depends_on = ["openstack_compute_floatingip_associate_v2. float_ip"]
```

**Comment by VincenzoDo** [comment]
Hello, 

unfortunately that's not the case. I'll do a few more test and update the issue if necessary

**Comment by fatmcgav** [comment]
@VincenzoDo The only other thing that might shed some light would be running a debug session, which will show the calls being made between Terraform and Openstack. 

`TF_LOG=debug OS_DEBUG=1 terraform apply`. 

Feel free to Gist or Pastebin the output if you want, but make sure to remove any sensitive data :)

**Comment by VincenzoDo** [comment]
Looks like the problem wasn't coming from terraform provider but from a corrupted image on one of the Openstack hosts. I'm closing the issue. Thank you anyway for the support !

**Comment by fatmcgav** [comment]
@VincenzoDo Cool, cheers for confirming :)
