### ISSUE TITLE
[winrm connection] calculate password with rsadecrypt 

### ISSUE THREAD

**Issue by lmayorga1980** [terraform-providers/terraform-provider-openstack#814]
Terraform `0.12.5`

I get the following error trying to calculate the password from an openstack instance

`Error: Invalid function argument: Invalid value for "path" parameter: argument must not be null.`

**code**

```
resource "openstack_compute_instance_v2" "sqlserver" {
  name              = "sqlserver"
  image_id          = "${var.image_id}"
  flavor_id         = "${var.flavor_id}"
  availability_zone = "${var.availability_zone}"
  key_pair          = "${openstack_compute_keypair_v2.generic_kp.name}"
  security_groups   = "${var.security_groups}"
  user_data         = "${file("files/bootstrap.ps1")}"
  
  network {
    name = "${var.network_name}"
  }

  connection  {
    type     = "winrm"
    agent    = false
    port     = "5986"
    user     = "Administrator"
    password = "${rsadecrypt(filebase64(self.admin_pass),file("cert/sqlserver.key"))}"
    insecure = true
    use_ntlm = false
    https    = true
    timeout  = "10m"
    host     = self.access_ip_v4
  }
}
```

**Comment by kayrus** [comment]
Unfortunately `openstack_compute_instance_v2` doesn't have the [os-server-password](https://docs.openstack.org/api-ref/compute/?expanded=show-server-password-detail) attribute support.

If you want to use an [`admin_pass`](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#admin_pass), then you have to set it yourself and it is possible to use it without a decryption.

**Comment by kayrus** [comment]
@jtopjian it is possible to introduce a new `admin_pass_encrypted` computed attribute, however there must be an extra option called `wait_for_admin_pass`. Because cloudbase-init for windows sets the passwords after the VM has been booted and cloud-init has been executed during the boot. So, before the boot, the password is not set in the metadata and it is empty. Probably it's worth create a new resource or data source?

**Comment by lmayorga1980** [comment]
I tried using the bootstrap.ps1 under user_data to set the password but wondering if admin_pass attribute will do the same.

**Comment by kayrus** [comment]
`admin_pass ` should do the same, but it really depends on the environment. Another way on setting the password is this:

```
user_data = <<EOF
#ps1_sysnative
net user Administrator ${var.admin_passwd}
EOF
```

**Comment by lmayorga1980** [comment]
Will try both and come back to the issue.

**Comment by kayrus** [comment]
remove the leading whitespaces, they're not removed automatically

**Comment by kayrus** [comment]
@lmayorga1980 did you resolve the issue?

**Comment by lmayorga1980** [comment]
@kayrus ,

I solved the issue by using the Administrator password configured in the `user_data` and use the same value in the `connection`. However, I think the requirement here should be that `connection` should retrieve the password from openstack initial boot image using the `key_file`

**Comment by kayrus** [comment]
@lmayorga1980 you can try to use the https://github.com/sapcc/nova-password as alternative.

**Comment by lmayorga1980** [comment]
So I have to place this CLI in my local machine and call it from terraform?

**Comment by kayrus** [comment]
Unfortunately there is no other solution yet.

**Comment by lmayorga1980** [comment]
I guess there can be another ticket that request this feature. Closing this issue.
