### ISSUE TITLE
openstack_networking_secgroup_v2 delete_default_rules not working

### ISSUE THREAD

**Issue by edevreede** [terraform-providers/terraform-provider-openstack#82]
Hi there,

We have this issue creating our environments with terraform as our security groups all have the default rules in them. The attribute delete_default_rules does not seem to work.

I added some debugging output to the code and found the initial create request on openstack does not return the default rules. However requesting the object right after does return them.

So I made a fix and a pull request, reference below.

### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
- openstack_networking_secgroup_v2

### Terraform Configuration Files
```hcl
resource "openstack_networking_secgroup_v2" "empty-group" {
  name                 = "empty-group"
  delete_default_rules = true
}
```

### Debug Output
https://gist.github.com/edevreede/1b1bc02a9e4f9996268bfac33f06cee2

### Panic Output
none

### Expected Behavior
Create a security group named empty-group containing no rules.

### Actual Behavior
The expected group is created, but contains the default rules.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
We recently moved from an older environment to the current hosted Openstack environment, which should be based on Mitaka release (by Mirantis).

### References
I made a patch and pull request https://github.com/terraform-providers/terraform-provider-openstack/pull/81 that fixes this issue.

**Comment by fatmcgav** [comment]
Fixed in #81
