### ISSUE TITLE
documentation code highlighting

### ISSUE THREAD

**Issue by jsm222** [terraform-providers/terraform-provider-openstack#829]
Thanks for merging https://github.com/terraform-providers/terraform-provider-openstack/pull/768 
There seems to be a problem with the markdown on the website though:

https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#importing-instance-with-multiple-network-interfaces-

as opposed to https://github.com/terraform-providers/terraform-provider-openstack/blob/master/website/docs/r/compute_instance_v2.html.markdown

which renders correctly

It could be the missing > here, but I'm just taking a wild guess.
```
flavor_id = "<flavor_id"
```

**Comment by ozerovandrei** [comment]
Fixed in #834
