### ISSUE TITLE
openstack plugin 1.21.0 issue

### ISSUE THREAD

**Issue by elizino6** [terraform-providers/terraform-provider-openstack#830]
Hello,
Yesterday you release a new openstack plugin version (1.21.0)
After download it I'm facing the following issue:

Error: parsing time ""2018-02-23T12:17:41"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"

I'm using terraform version:
Terraform v0.12.5

**Comment by kayrus** [comment]
@elizino6 which resource do you experience problems with? Please share the terraform configuration.

**Comment by kayrus** [comment]
Looks like you're using the https://www.terraform.io/docs/providers/openstack/d/keymanager_secret_v1.html data source.

[Date filters](https://www.terraform.io/docs/providers/openstack/d/keymanager_secret_v1.html#date-filters) documentation explains that the data must be in RFC3339 format. According to [terraform documentation](https://www.terraform.io/docs/configuration/functions/timestamp.html) there should be a `Z` at the end. 

Try to use `2018-02-23T12:17:41Z`, or with the filter combination `gt:2018-02-23T12:17:41Z`

**Comment by elizino6** [comment]
i'm facing it at this resource 

+ echo Terraform plan
+ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.ci-env.data.openstack_networking_network_v2.hrzagt1-net-scv2-floating-ip-dt: Refreshing state...
data.openstack_images_image_v2.base_image: Refreshing state...

Error: parsing time ""2018-02-23T12:17:41"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"

**Comment by elizino6** [comment]
and in the data.tf file i got:

data "openstack_images_image_v2" "base_image" {
  name = "${var.base_image_name}"
  most_recent = true
}

**Comment by elizino6** [comment]
Also some other colleagues  have the problem in the following  resource:

* module.ci-env.module.os-inventory.data.openstack_networking_network_v2.hrzagt1-net-scv2-floating-ip-dt: data.openstack_networking_network_v2.hrzagt1-net-scv2-floating-ip-dt: parsing time ""2018-02-23T12:17:41"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"
* module.ci-env.data.openstack_networking_network_v2.hrzagt1-net-scv2-floating-Artifactory-dev: 1 error(s) occurred:

* module.ci-env.data.openstack_networking_network_v2.hrzagt1-net-scv2-floating-Artifactory-dev: data.openstack_networking_network_v2.hrzagt1-net-scv2-floating-Artifactory-dev: parsing time ""2018-10-15T13:03:18"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"

**Comment by jtopjian** [comment]
I started seeing this error in Gophercloud yesterday with the networking resources, though it was while I was testing against an older release of OpenStack.

@elizino6 What OpenStack release is your environment running? Also, can you confirm that using the prior version of this provider does not have this issue?

**Comment by jtopjian** [comment]
I believe I've narrowed the issue down: https://github.com/gophercloud/gophercloud/issues/1670

It looks like this problem has always existed with some resources, but recent modifications to the "network" API made this more visible to more users.

**Comment by ozerovandrei** [comment]
@elizino6  @kayrus @jtopjian thank you for raising and fixing this issue.
I will vendor the new upstream Gophercloud commit and create a patch release of the provider.

**Comment by ozerovandrei** [comment]
@elizino6 you can use the new `1.21.1` version of the provider that was released on August 08: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/CHANGELOG.md#1211-august-08-2019
