### ISSUE TITLE
openstack_networking_network_v2 dns_domain makes TF runs not idempotent and breaks on multiple runs

### ISSUE THREAD

**Issue by dev00** [terraform-providers/terraform-provider-openstack#836]
When creating a network, the `dns_domain` flag will be set by Openstack, if neutron is configured accordingly. It's not meant to be set by a user. If the user explicitly sets this value, an error will occure, stating `Error: Error updating openstack_networking_network_v2 VPC_ID: Bad request with: [PUT https://vpc.eu-de.otc.t-systems.com/v2.0/networks/VPC_ID], error message: {"NeutronError":{"message":"dns_domain can not be set when update network.","type":"HTTPBadRequest","detail":""}}`

However, this will ALSO occure if the network was created and terraform is applied again, as terraform tries to change the default value to null again:
```
  # module.vpc.openstack_networking_network_v2.os_network_1 will be updated in-place
  ~ resource "openstack_networking_network_v2" "os_network_1" {
        admin_state_up          = true
        all_tags                = []
        availability_zone_hints = []
      - dns_domain              = "eu-de.compute.internal." -> null
```

### Terraform Version
```
Terraform v0.12.6
+ provider.local v1.3.0
+ provider.null v2.1.2
+ provider.openstack v1.21.1
```

### Affected Resource(s)
- openstack_networking_network_v2

### Terraform Configuration Files
```hcl
resource "openstack_networking_network_v2" "os_network_1" {
  name              = "${var.project}-network"
  admin_state_up    = true
 #  dns_domain        = "eu-de.compute.internal."
}
```

### Expected Behavior
Terraform should either check the value of said field _after_ creation and include it into the networks state, or provide an option to ignore the dns_domain setting. Removing it is not an option as Openstack admins may use terraform for network management, which are allowed to set `dns_domain`. Setting it to the Openstack default value will also result in breaking as Neutron seems to deny any request where dns_domain is stated.

### Actual Behavior
Terraform tries to overwrite the default value set by Openstack and breaks

### Steps to Reproduce
1. use `openstack_networking_network_v2` to create a network on an Openstack installation with dns extension enabled and do not set `dns_domain`
2. `terraform apply` once, check network settings via `openstack network show <net_name>`
3. run `terraform apply` again and see it breaking

### References
- Looks similar to #742

**Comment by kayrus** [comment]
According to the neutron code, it allows an update https://github.com/openstack/neutron/blob/4d8685da8050df79d9193f91cab572cfc6d67a47/neutron/extensions/dns.py#L230, therefore, I assume the `Computed: true` is enough.

**Comment by dev00** [comment]
@kayrus turns out you are right and the `dns_domain can not be set when update network.` is due to a specific implementation detail on my side (just tested it against a vanilla openstack).

As I understand you correctly, this will however result in terraform respecting the value set by Openstack unless explicitly stated otherwise in the resource? Awesome, thanks :)

**Comment by kayrus** [comment]
> As I understand you correctly, this will however result in terraform respecting the value set by Openstack unless explicitly stated otherwise in the resource?

Correct. This has to be approved by maintainers.
