### ISSUE TITLE
rediscover resources that are not in state by name

### ISSUE THREAD

**Issue by JanZerebecki** [terraform-providers/terraform-provider-openstack#863]
### Terraform Version
Terraform v0.11.11
+ provider.null v2.1.2
+ provider.openstack v1.22.0
+ provider.template v2.1.2

### Affected Resource(s)
All OpenStack resources with names.

### Terraform Configuration Files
```hcl
resource "openstack_networking_secgroup_v2" "testsecgroup" {
  name        = "test-terraform-secgroup"
  description = "security group for testing terraform"
}
```

### Expected Behavior
`terraform refresh` should find OpenStack resources that are not in its state by name from the OpenStack API. When they do exist in state but its id is not in the API, it should check by name as if it didn't exist in the state.

I'm not familiar enough with the finer details of terraforms design, so perhaps there is a better way.

It should also check if a name is used twice, to prevent getting confused when a resources is referenced by name. E.g. when specifying `security_groups` for an `openstack_compute_instance_v2` by name. Otherwise the API call to create the instance will fail.

### Actual Behavior
`terraform refresh` doesn't find the resource.
`terraform apply` thus creates it and now there are two with the same name.
Something like this can be used, but manually doing that should not be necessary: `terraform import openstack_networking_secgroup_v2.load_balancer 7d657459-bd59-479e-92a3-0ff547a5ac38`

### Steps to Reproduce
Describe a resource, `terraform apply`, wipe the state, `terraform refresh`, `terraform state list` doesn't show it anymore.

**Comment by kayrus** [comment]
@JanZerebecki if you want to manage the infrastructure, which was not created by terraform, you have to use `import` command. Another option is to use https://github.com/GoogleCloudPlatform/terraformer to generate the terraform configuration and the state automatically, but it supports a limited amount of OpenStack resources: https://github.com/GoogleCloudPlatform/terraformer#use-with-openstack

**Comment by JanZerebecki** [comment]
Thank you for the terraformer link.

In this case the infrastructure was generated by terraform. In one case the state was removed because the destroy was tried but actually failed. In another the connection got interrupted before terraform could know that it succeeded with creation, so it didn't record the state. I'm trying to find a way to clean up these resources.

More importantly at least I'd like if on the next run terraform doesn't trip over the resource names from its previous run.

**Comment by kayrus** [comment]
@JanZerebecki you always have to perform a backup of your terraform state. If the state is lost, or connection was interrupted, you can play with the `terraform untain` or `terraform import`. I know that it is not straightforward, but there is nothing better than this. `terraform refresh` is not what you need in this case.

**Comment by JanZerebecki** [comment]
What improvement in this regard is acceptable to this project?

**Comment by kayrus** [comment]
@JanZerebecki I guess the https://github.com/hashicorp/terraform/issues is a better place to discuss this issue.

**Comment by ozerovandrei** [comment]
I'm going to close this since this feature should be implemented in core.
