### ISSUE TITLE
How to user scheduler_hints/different_host

### ISSUE THREAD

**Issue by ppcololo** [terraform-providers/terraform-provider-openstack#864]
@ozerovandrei Could you describe how to use scheduler_hints/different_host?

I create VM's like this
```
resource "openstack_compute_instance_v2" "k8s_master" {
  name              = "${var.cluster_name}-k8s-master-${count.index+1}"
  count             = "${var.number_of_k8s_masters}"
  availability_zone = "${element(var.az_list, count.index)}"
  image_name        = "${var.image}"
  flavor_id         = "${var.flavor_k8s_master}"
  key_pair          = "${openstack_compute_keypair_v2.k8s.name}"

  network {
    name = "${var.network_name}"
  }

  scheduler_hints {
    different_host = [ count.index == 1 ? openstack_compute_instance_v2.k8s_master[0].id : (count.index == 2 ? openstack_compute_instance_v2.k8s_master[1].id : "")]
  }
}
```
and i want each VM on different host because it's master hosts for kubernetes, but always get error
```
Error: Cycle: module.compute.....
```

**Comment by ozerovandrei** [comment]
Hello @ppcololo 
Could you please provide a full error output?
It would be helpful if you also provided full manifests (with vars) so we could better test this.

**Comment by ppcololo** [comment]
it's a standard kubespray TF - https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/openstack/modules/compute/main.tf

I want my masters be on different hosts after creation. But I think it's impossible if I use count function while create them...

**Comment by kayrus** [comment]
@ppcololo it fails because it refers to itself. I'd recommend you to use the anti-affinity server group to achieve the same outcome: https://www.terraform.io/docs/providers/openstack/r/compute_servergroup_v2.html
https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#group

**Comment by ppcololo** [comment]
@kayrus thx for answer
but if I have only 3 servers and I can create 3 separate groups to place VM's on different hosts
and if one server will fail, will VM's migrate to another server if there different group?

**Comment by kayrus** [comment]
@ppcololo  You have to create one server group with the anti-affinity policy and create servers withing this group. That's it. Nova scheduler will make sure that the VMs are not running on the same hypervisor.

**Comment by ppcololo** [comment]
@kayrus thx a lot! will try

**Comment by ozerovandrei** [comment]
@ppcololo don't forget to check notes about different policies for a group: https://www.terraform.io/docs/providers/openstack/r/compute_servergroup_v2.html#policies-1
