### ISSUE TITLE
LBaaSv2: connection_limit always set for listener, resulting in errors for some provider

### ISSUE THREAD

**Issue by Crapworks** [terraform-providers/terraform-provider-openstack#87]
Hi there,

### Terraform Version
`Terraform v0.10.2`
`provider-openstack_v0.2.0_x4`

### Affected Resource(s)
Please list the resources as a list, for example:
- `openstack_lb_listener_v2`

### Terraform Configuration Files
```hcl
resource "openstack_lb_listener_v2" "listener" {
  protocol        = "HTTP"
  protocol_port   = 80
  loadbalancer_id = "${openstack_lb_loadbalancer_v2.loadbalancer.id}"
  admin_state_up  = "true"
}
```

The OpenStack provider I am currently using with Terraform doesn't allow to set the `connection_limit` attribute for the LBaaSv2 listener. For some reasons, even if I do not specify this property for my resource, Terraform ist setting this field in the API request:

```
2017/08/18 09:56:48 [DEBUG] OpenStack Request Body: {
  "listener": {
    "admin_state_up": true,
    "connection_limit": 0,
    "loadbalancer_id": "f904502b-a215-40db-9cec-060661d81f95",
    "protocol": "HTTP",
    "protocol_port": 80
  }
}
```

This results in an error:

```
2017/08/18 09:56:49 [DEBUG] OpenStack Response Body: {
  "NeutronError": {
    "detail": "",
    "message": "Rules on create_listener by *** disallowed by policy",
    "type": "PolicyNotAuthorized"
  }
}
```

Sending the request manually without the `connection_limit` attribute works fine. Since this is an optional parameter, I don't see why this is set even if the user doesn't specify it. I also don't know if 0 is a good default value, because the internal OpenStack default is -1, meaning no limit.

**Comment by fatmcgav** [comment]
@Crapworks cheers for reporting... 

I'm guessing the 'default' value of `0` is coming from here: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_lb_listener_v2.go#L125

@jtopjian Would it make sense to set a default value in the schema definition? Is `-1` even a valid int in Golang?

**Comment by Crapworks** [comment]
@fatmcgav 
Just to make this clear again: The solution for me here is *NO* default value from Terraform. The OpenStack API already takes care of a default value if the parameter is not provided. Setting the default in Terraform to -1 wouldn't solve my problem that the provider simply doesn't allow this parameter.

Cheers,
Christian

**Comment by fatmcgav** [comment]
@Crapworks Ah, yeh, my apologies... 

So yeh, 'not' providing that value will require a bit more work... 

@jtopjian Does this sound like another vendor-specific mod, or are these sort of policies fairly common-place?

**Comment by jtopjian** [comment]
It looks like Gophercloud is [doing the right thing](https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go#L102). If the value is `nil`, it won't be in the request body.

So this is another one of those tertiary type of values: 0, non-zero, and nil. So we need some way of setting the pointer to nil. 

According to the `neutron` command:

```
  --connection-limit CONNECTION_LIMIT
                        The maximum number of connections per second allowed
                        for the listener. Positive integer or -1 for unlimited
                        (default).
```

So -1 is a valid option and we don't want to use that as the trigger.

I think what we need to do is check if the value is `0`, and if it is, pass nil. Unfortunately this might be a breaking change, since Neutron is happily accepting a value of 0 (but for what, I'm not sure) so I want to investigate that a little bit more.

However, if it is safe to consider 0 a "nil" value, then the following patch should work:

```diff
--- a/openstack/resource_openstack_lb_listener_v2.go
+++ b/openstack/resource_openstack_lb_listener_v2.go
@@ -122,7 +122,6 @@ func resourceListenerV2Create(d *schema.ResourceData, meta interface{}) error {
        }

        adminStateUp := d.Get("admin_state_up").(bool)
-       connLimit := d.Get("connection_limit").(int)
        var sniContainerRefs []string
        if raw, ok := d.GetOk("sni_container_refs"); ok {
                for _, v := range raw.([]interface{}) {
@@ -137,12 +136,16 @@ func resourceListenerV2Create(d *schema.ResourceData, meta interface{}) error {
                Name:                   d.Get("name").(string),
                DefaultPoolID:          d.Get("default_pool_id").(string),
                Description:            d.Get("description").(string),
-               ConnLimit:              &connLimit,
                DefaultTlsContainerRef: d.Get("default_tls_container_ref").(string),
                SniContainerRefs:       sniContainerRefs,
                AdminStateUp:           &adminStateUp,
        }

+       v := d.Get("connection_limit").(int)
+       if v != 0 {
+               createOpts.ConnLimit = &v
+       }
+
```

If 0 is a valid value and should be passed to Neutron, then there are two options:

1. Use `-2` as a trigger to not pass `connection_limit`. 
2. Have a parameter like `dont_send_connection_limit`. But that's just weird.

Anyway, I will look into this in more detail and follow-up.

**Comment by jtopjian** [comment]
Duh. I forgot about `GetOk`.

@Crapworks I submitted a patch for this in #90. Would you be able to compile from source and verify this works for you? No big deal if you can't.

**Comment by Crapworks** [comment]
@jtopjian I compiled the openstack provider with your patch, and the listener could be created. Afterwards, I get the following error: https://gist.github.com/Crapworks/701e8141b5b1410e50ec918d5fbcdb8b

This has probably nothing to do with your patch, but with some other errors on the provider side. I'll have to investigate this further and then will get back to you. The patch seems to work though!

**Comment by Crapworks** [comment]
I am a bit confused, since I can't see anywhere in the DEBUG output the request to create a monitor (although it show "Attempting to create monitor". I remember slightly from some earlier releases that it was  important to add some manual "depends_on" in the loadbalancer resource. Is this still a thing?

**Comment by jtopjian** [comment]
@Crapworks You can use `OS_DEBUG=1` to see the OpenStack API calls that are being made. This might help point out where the problem is.

```shell
$ TF_LOG=DEBUG OS_DEBUG=1 terraform apply
```

I'll hold off on merging #90 until we're sure it didn't actually cause another bug.

**Comment by Crapworks** [comment]
@jtopjian 
my provider is currently trying to find out whats going on, since I can't delete the router in my tenant anymore (neither via UI nor via API). I will get back to you as soon as I can use my Tenant again.

**Comment by Crapworks** [comment]
@jtopjian The problems got fixed and I was testing it again, just with the loadbalancer and the listener, omitting the monitor, pool and members. The patch works fine for me after several apply/destroy runs!

I will try to create pools and members next. I guess I should create a new issue if there are problems since the original problem has been solved with the patch?
