### ISSUE TITLE
Provider produced inconsistent result after apply - produced an unexpected new value for was present, but now absent - when pushing 300~ S.G rules

### ISSUE THREAD

**Issue by dannielshalev** [terraform-providers/terraform-provider-openstack#879]
Terraform Wrongly Reporting Security Group Rule Exists and Failure, while it wasn't and actually successfully created the rule  

### Terraform Configuration Files:
```resource "openstack_networking_secgroup_rule_v2" "SEC-SERVICE-HADOOP-BE_rule_19" {
    direction         = "ingress"
    ethertype         = "IPv4"
    protocol          = "tcp"
    port_range_min    = "4181"
    port_range_max    = "4181"
    remote_ip_prefix  = "10.4.0.0/14"
    security_group_id = "eaddb8b5-8d26-43f5-b43a-2b5e72cc4c98"
    depends_on = ["openstack_networking_secgroup_v2.SEC-SERVICE-HADOOP-BE",
                  "openstack_networking_secgroup_rule_v2.SEC-SERVICE-HADOOP-BE_rule_18"]
}

resource "openstack_networking_secgroup_rule_v2" "SEC-SERVICE-EFG-MED_rule_31" {
    direction         = "ingress"
    ethertype         = "IPv4"
    protocol          = "tcp"
    port_range_min    = "9092"
    port_range_max    = "9092"
    remote_ip_prefix  = "10.4.0.0/14"
    security_group_id = openstack_networking_secgroup_v2.SEC-SERVICE-EFG-MED.id
    depends_on = ["openstack_networking_secgroup_v2.SEC-SERVICE-EFG-MED"]
}
```
Behavior
### Actual Behavior
Getting the following error:
ERROR1:

Error: Provider produced inconsistent result after apply

When applying changes to
openstack_networking_secgroup_rule_v2.SEC-SERVICE-HADOOP-BE_rule_19, provider
"openstack" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

ERROR2:

Error: Error creating openstack_networking_secgroup_rule_v2: Expected HTTP response code [] when accessing [POST https://kloud-stg.kenshoo.com:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is d75d1baf-0575-46f8-99a7-f345538698ba.", "type": "SecurityGroupRuleExists", "detail": ""}}

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
Error: Error creating openstack_networking_secgroup_rule_v2: Expected HTTP response code [] when accessing [POST https://kloud-stg.abc.com:9696/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is 6ef3f493-15b8-49ea-830f-1359b56b5abc.", "type": "SecurityGroupRuleExists", "detail": ""}}

  on ecom-bing.tf line 787, in resource "openstack_networking_secgroup_rule_v2" "SEC-SERVICE-EFG-MED_rule_31":
 787: resource "openstack_networking_secgroup_rule_v2" "SEC-SERVICE-EFG-MED_rule_31" {

### Expected behavior 

The terraform should pass - cause the security group rule was really created by terraform just wrongly reporting failure about existing Rule id that terraform itself created.
### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. create the configuration file above
2. `terraform init`
3. `terraform plan`
4. `terraform apply`

**Comment by kayrus** [comment]
@dannielshalev could you please provide an output of the commands below?

```
openstack security group rule list eaddb8b5-8d26-43f5-b43a-2b5e72cc4c98
openstack security group rule show d75d1baf-0575-46f8-99a7-f345538698ba
openstack security group rule show 6ef3f493-15b8-49ea-830f-1359b56b5abc
```

**Comment by PetrusHahol** [comment]
I faced the same problem. After long investigation I have found out that once terraform tries to create a bunch of SG rules in one time it makes some problem for openstack. Openstack answer 200 OK but does not create some security groups. After that, terraform checks current rules but nothing was create, because of that it fails. So, seems like it works for me with 2 WA's . 
1) You can depends_on your rules between each other
2) You can enable parallelism=1

**Comment by NadOby** [comment]
Just to note that:

>     1. You can depends_on your rules between each other
Is not working when rules are creating dynamically
```
variable "whitelist" {
  description = "IP nets to whitelist"
  default = {
    google_1  = "8.8.8.8./32"
    google_2  = "8.8.8.4./32"
  }
}
resource "openstack_networking_secgroup_rule_v2" "whitelist_rule" {
  for_each          = var.whitelist
  direction         = "ingress"
  ethertype         = "IPv4"
  port_range_min    = "80"
  port_range_max    = "80"
  protocol          = "tcp"
  region            = var.region
  remote_ip_prefix  = each.value
  security_group_id = "${openstack_networking_secgroup_v2.halo_internal_whitelist.id}"
}

```
>     2. You can enable parallelism=1
Is extremely annoying if you have any significant amount of resources

**Comment by giva01121** [comment]
I'm having the exact same issue, but the problem is that the parallelism is not helping me. 
```
Error: Error creating openstack_networking_secgroup_rule_v2: Expected HTTP response code [] when accessing [POST https://openstack.server/v2.0/security-group-rules], but got 409 instead
{"NeutronError": {"message": "Security group rule already exists. Rule id is a8739a12-a581-484e-95fa-e1c589a195d0.", "type": "SecurityGroupRuleExists", "detail": ""}}

```
So is this a bug for terraform or for the openstack module ?

**Comment by dannielshalev** [comment]
@PetrusHahol thanks for the suggestion, unfortunately, I tried both things without any luck.
@giva01121 - I think its terraform OpenStack provider issue.

**Comment by NadOby** [comment]
> I'm having the exact same issue, but the problem is that the parallelism is not helping me.
> 
> ```
> Error: Error creating openstack_networking_secgroup_rule_v2: Expected HTTP response code [] when accessing [POST https://openstack.server/v2.0/security-group-rules], but got 409 instead
> {"NeutronError": {"message": "Security group rule already exists. Rule id is a8739a12-a581-484e-95fa-e1c589a195d0.", "type": "SecurityGroupRuleExists", "detail": ""}}
> ```
> 
> So is this a bug for terraform or for the openstack module ?

This kind of error usually shows up after the unsuccessful application and the are hard to tall if due to the terrafrom or openstack plugin.
The problem is simple - the TF state is not consistent with the real status of some resources.
As a workaround delete those resources manually.

**Comment by PetrusHahol** [comment]
I've debugged the provider and found out that neutron API makes dirty read/write into database.  
 
[This](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_secgroup_rule_v2.go#L162) method uses async calls to create security group rule. It all time returns object of created security rule. Right after it tries to check if there is such security rule created in openstack, and sometimes it fails with 404 Not Found. That is the reason of inconsistency.  

I've wrote a little script which shows the problem using usual cURL requests. 
I have reproduced the issue but I have contrail behind of neutron API and I don't have any openstack to check if there is the same problem with native neutron module. 

Can somebod check the script with neutron?  @dannielshalev 
```
#!/usr/bin/env bash
set -eo pipefail

### specfy here your own X_AUTH_TOKEN and NEUTRON_URL
export X_AUTH_TOKEN=""
export NEUTRON_URL="https://neutron.url.eu:9696/v2.0/"

function createAndCheckSgRule() {

  SGRuleId=$(curl --silent --location --request POST ${NEUTRON_URL}'security-group-rules' \
    --header 'X-Auth-Token: '${X_AUTH_TOKEN} \
    --header 'Accept: application/json' \
    --header 'Content-Type: application/json' \
    --data-raw '{
   "security_group_rule":{
      "direction":"ingress",
      "port_range_min":"0",
      "ethertype":"IPv4",
      "port_range_max":"25000",
      "protocol":"tcp",
      "remote_ip_prefix":"192.'"$2"'.0.0/24",
      "security_group_id":"'"$1"'"
   }
}' | jq -r .security_group_rule.id)

  responseCode=$(curl -s -o /dev/null -w "%{http_code}" --silent --location --request GET ${NEUTRON_URL}'security-group-rules/'${SGRuleId} \
    --header 'X-Auth-Token: '${X_AUTH_TOKEN} \
    --header 'Accept: application/json' \
    --header 'Content-Type: application/json')

  if [[ ${responseCode} == '404' ]]
  then
    echo "Security rule with id ${SGRuleId} was created but does not exist"
  else
    echo "Security Group created successfully with id ${SGRuleId}."
  fi
}

########################################################################
export SG=$(curl --silent --location --request POST ${NEUTRON_URL}'security-groups' \
  --header 'X-Auth-Token: '${X_AUTH_TOKEN} \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data-raw '{
   "security_group":{
      "name":"Test resource",
      "description":"Test resource"
   }
}' | jq -r .security_group.id)

echo "Security Group created with id:"
echo "$SG"
echo "--------------------------------"

# Security Rules Creation
number=5
pids=""
for ((i = 0; i < number; i++)); do
  createAndCheckSgRule "${SG}" "${i}" &
  pids="$pids $!"
done

wait $pids

unset X_AUTH_TOKEN
unset NEUTRON_URL
unset SG

echo "------Execution finished.------"
######################################################
```

it creates 5 security rules (number can be increased). In succeed scenario you will have only "Security Group created successfully with id ${id}" messages. Otherwise you will see "Security rule with id ${id} was created but does not exist".

If you will not face this issue using native neutron, then the problem is with Contrail.

**Comment by PetrusHahol** [comment]
[There is](https://github.com/Juniper/contrail-controller/blob/32cf7fa1c888e229d37027a9d805d6d40cf2bb28/src/config/vnc_openstack/vnc_openstack/neutron_plugin_db.py#L443) already implemented WA which takes locks. 
---
The work around has been propagated to all release branches as I can see. 
I don't have this fix and you probably as well.

**Comment by flagmen** [comment]
> I've debugged the provider and found out that neutron API makes dirty read/write into database.
> 
> [This](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_networking_secgroup_rule_v2.go#L162) method has been calling as async to create security group rule. It all time returns object of created security rule. Right after it tries to check if there is such security rule created in openstack, and sometimes it fails with 404 Not Found. That is the reason of inconsistency.
> 
> I've wrote a little script which shows the problem using usual cURL requests.
> I have reproduced the issue but I have contrail behind of neutron API and I don't have any openstack to check if there is the same problem with native neutron module.
> 
> Can somebody check the script with neutron? @dannielshalev
> 
> ```
> #!/usr/bin/env bash
> set -eo pipefail
> 
> ### specfy here your own X_AUTH_TOKEN and NEUTRON_URL
> export X_AUTH_TOKEN=""
> export NEUTRON_URL="https://neutron.url.eu:9696/v2.0/"
> 
> function createAndCheckSgRule() {
> 
>   SGRuleId=$(curl --silent --location --request POST ${NEUTRON_URL}'security-group-rules' \
>     --header 'X-Auth-Token: '${X_AUTH_TOKEN} \
>     --header 'Accept: application/json' \
>     --header 'Content-Type: application/json' \
>     --data-raw '{
>    "security_group_rule":{
>       "direction":"ingress",
>       "port_range_min":"0",
>       "ethertype":"IPv4",
>       "port_range_max":"25000",
>       "protocol":"tcp",
>       "remote_ip_prefix":"192.'"$2"'.0.0/24",
>       "security_group_id":"'"$1"'"
>    }
> }' | jq -r .security_group_rule.id)
> 
>   responseCode=$(curl -s -o /dev/null -w "%{http_code}" --silent --location --request GET ${NEUTRON_URL}'security-group-rules/'${SGRuleId} \
>     --header 'X-Auth-Token: '${X_AUTH_TOKEN} \
>     --header 'Accept: application/json' \
>     --header 'Content-Type: application/json')
> 
>   if [[ ${responseCode} == '404' ]]
>   then
>     echo "Security rule with id ${SGRuleId} was created but does not exist"
>   else
>     echo "Security Group created successfully with id ${SGRuleId}."
>   fi
> }
> 
> ########################################################################
> export SG=$(curl --silent --location --request POST ${NEUTRON_URL}'security-groups' \
>   --header 'X-Auth-Token: '${X_AUTH_TOKEN} \
>   --header 'Accept: application/json' \
>   --header 'Content-Type: application/json' \
>   --data-raw '{
>    "security_group":{
>       "name":"Test resource",
>       "description":"Test resource"
>    }
> }' | jq -r .security_group.id)
> 
> echo "Security Group created with id:"
> echo "$SG"
> echo "--------------------------------"
> 
> # Security Rules Creation
> number=5
> pids=""
> for ((i = 0; i < number; i++)); do
>   createAndCheckSgRule "${SG}" "${i}" &
>   pids="$pids $!"
> done
> 
> wait $pids
> 
> unset X_AUTH_TOKEN
> unset NEUTRON_URL
> unset SG
> 
> echo "------Execution finished.------"
> ######################################################
> ```
> 
> it creates 5 security rules (number can be increased). In succeed scenario you will have only "Security Group created successfully with id ${id}" messages. Otherwise you will see "Security rule with id ${id} was created but does not exist".
> 
> If you will not face this issue using native neutron, then the problem is with Contrail.

```
Security Group created with id:
c63adbfb-e1eb-4d51-9574-71dd81859dbf
--------------------------------
Security Group created successfully with id 33913db6-ebda-48c4-919e-ad24b1895740.
Security Group created successfully with id 23b7929f-683a-4784-8158-5534a58835ca.
Security Group created successfully with id 015f1e65-b58f-4604-b4a3-dedde29c9716.
Security Group created successfully with id 5e62baf6-2aee-482a-9648-5cba11f4c1f5.
Security Group created successfully with id 90f28fb7-0ce4-4741-a676-c96dece6554e.
Security Group created successfully with id 4b545ba7-652d-43b8-8cd5-cca7d94cfe45.
Security Group created successfully with id 2a2141ee-3d18-4a7a-bbd1-ce1b084e8057.
Security Group created successfully with id 818046d0-edde-472b-8ee8-955415e4b941.
Security Group created successfully with id 039969ab-70e5-461f-afa2-433c6f4f2b44.
Security Group created successfully with id 7ee19780-6d7c-414c-a0b2-fb8b3fc2b498.
Security Group created successfully with id 075e4680-472d-4742-9089-db62c6c15ec2.
Security Group created successfully with id 704909b0-9883-4e3a-a67e-b82c92ccc079.
Security Group created successfully with id c311b98a-7041-4691-89ed-e07462b8807a.
Security Group created successfully with id 78da16df-8639-48a0-91b0-553d62b1b041.
Security Group created successfully with id 88d11e84-5bfb-42f2-b109-f05e606a974d.
Security Group created successfully with id 42fb30ba-3638-4a8d-848d-d8876ed14e3c.
Security Group created successfully with id 278dee76-42a5-456b-b408-28491613357e.
Security Group created successfully with id c68d38fc-9d3a-4165-8920-fe66dfe1a228.
Security Group created successfully with id eed0778c-7d57-441e-b834-ba0edc0e8492.
Security Group created successfully with id 5b0571a6-feb2-4ae3-bf23-f28e7a205757.
------Execution finished.------

```
I`ve checked your script with native neutron and it works fine for me.
It means that the problem is related to contrail

**Comment by kayrus** [comment]
@PetrusHahol looks like this issue is related to #952
