### ISSUE TITLE
Identity V3: Group Resource

### ISSUE THREAD

**Issue by LmV4corbeau** [terraform-providers/terraform-provider-openstack#895]
Hi, people,

thank you so much for the great work.

Would it be possible to create a resource for Openstack Identity Groups to create, update and delete groups?

### Terraform Version
Terraform v0.12.9
+ provider.openstack v1.23.0

### Affected Resource(s)
openstack_identity_group_v3

**Comment by ozerovandrei** [comment]
It's possible and upstream Gophercloud library already provides all needed handlers for it: https://github.com/gophercloud/gophercloud/tree/master/openstack/identity/v3/groups

**Comment by ozerovandrei** [comment]
Implemented in #1028
