### ISSUE TITLE
Error: error setting default for "insecure": a bool is required

### ISSUE THREAD

**Issue by SerenaLi279** [terraform-providers/terraform-provider-openstack#924]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.
### Issue
I upgrade terraform from v0.11.14(+ provider.openstack v1.21.1) to v0.12.13, upgrade successfully, terraform init pass, but terraform apply failed, then I change provider.openstack v1.21.1 to provider.openstack v1.24.0 the same issue.

### Terraform Version
Terraform v0.12.13
+ provider.openstack v1.24.0

### Terraform Configuration Files
```hcl
module "vlan-net-01-v4-port01" {
  source = "./modules/vlanport/serena/net-01-v4-port01"
  net-01_net_uuid    = "b3e05dd1-bbf3-4e2b-8c18-07bacd91fdf0"
  net-01_v4_sub_uuid = "1d4b6d34-80b8-4f43-b517-00bfd77a5dae"
}
```
./modules/vlanport/serena/net-01-v4-port01/main.tf
```hcl
variable "net-01_v4_sub_uuid" {
}

variable "net-01_net_uuid" {
}

resource "openstack_networking_port_v2" "net-01-v4-port01" {
  name           = "serena-net-01-v4-port01"
  network_id     = var.net-01_net_uuid
  admin_state_up = "true"

  fixed_ip {
    subnet_id  = var.net-01_v4_sub_uuid
    ip_address = "172.17.1.11"
  }

  fixed_ip {
    subnet_id  = var.net-01_v4_sub_uuid
    ip_address = "172.17.1.12"
  }

  fixed_ip {
    subnet_id  = var.net-01_v4_sub_uuid
    ip_address = "172.17.1.13"
  }
}
```

### Debug Output
```hcl
2019/11/13 02:23:21 [DEBUG] Starting graph walk: walkValidate
2019/11/13 02:23:21 [TRACE] dag/walk: updating graph
2019/11/13 02:23:21 [TRACE] dag/walk: 2019-11-13T02:23:21.389Z [INFO]  plugin: configuring client automatic mTLS
2019-11-13T02:23:21.431Z [DEBUG] plugin: starting plugin: path=/root/CSF-CLCM/terraform/openstack/resources/terraform-provider-openstack_v1.24.0_x4 args=[/root/CSF-CLCM/terraform/openstack/resources/terraform-provider-openstack_v1.24.0_x4]
2019-11-13T02:23:21.432Z [DEBUG] plugin: plugin started: path=/root/CSF-CLCM/terraform/openstack/resources/terraform-provider-openstack_v1.24.0_x4 pid=2970
2019-11-13T02:23:21.432Z [DEBUG] plugin: waiting for RPC address: path=/root/CSF-CLCM/terraform/openstack/resources/terraform-provider-openstack_v1.24.0_x4
2019-11-13T02:23:21.449Z [INFO]  plugin.terraform-provider-openstack_v1.24.0_x4: configuring server automatic mTLS: timestamp=2019-11-13T02:23:21.448Z
2019-11-13T02:23:21.490Z [DEBUG] plugin.terraform-provider-openstack_v1.24.0_x4: plugin address: address=/tmp/plugin828168296 network=unix timestamp=2019-11-13T02:23:21.490Z
2019-11-13T02:23:21.490Z [DEBUG] plugin: using plugin: version=5
2019/11/13 02:23:21 [TRACE] BuiltinEvalContext: Initialized "openstack" provider for provider.openstack
2019/11/13 02:23:21 [TRACE] <root>: eval: terraform.EvalNoop
2019/11/13 02:23:21 [TRACE] <root>: eval: *terraform.EvalOpFilter
2019/11/13 02:23:21 [TRACE] <root>: eval: *terraform.EvalSequence
2019/11/13 02:23:21 [TRACE] <root>: eval: *terraform.EvalGetProvider
2019/11/13 02:23:21 [TRACE] <root>: eval: *terraform.EvalValidateProvider
2019/11/13 02:23:21 [TRACE] buildProviderConfig for provider.openstack: no configuration at all
2019/11/13 02:23:21 [TRACE] GRPCProvider: GetSchema
2019/11/13 02:23:21 [WARN] <root>: eval: *terraform.EvalValidateProvider, non-fatal err: error setting default for "insecure": a bool is required
2019/11/13 02:23:21 [ERROR] <root>: eval: *terraform.EvalSequence, err: error setting default for "insecure": a bool is required
2019/11/13 02:23:21 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: error setting default for "insecure": a bool is required
2019/11/13 02:23:21 [ERROR] <root>: eval: *terraform.EvalSequence, err: error setting default for "insecure": a bool is required

Error: error setting default for "insecure": a bool is required


2019-11-13T02:23:21.588Z [DEBUG] plugin: plugin process exited: path=/root/CSF-CLCM/terraform/openstack/resources/terraform-provider-openstack_v1.24.0_x4 pid=2970
2019-11-13T02:23:21.588Z [DEBUG] plugin: plugin exited
```

### Expected Behavior
no error

### Actual Behavior
Error: error setting default for "insecure": a bool is required

### Steps to Reproduce
I upgrade terraform from v0.11.14(+ provider.openstack v1.21.1) to v0.12.13, upgrade successfully, terraform init pass, but terraform apply failed, then I change provider.openstack v1.21.1 to provider.openstack v1.24.0 the same issue.
1. upgrade terraform
current version Terraform v0.11.14((+ provider.openstack v1.21.1)
```hcl
terraform init
terraform 0.12checklist
```
download and use terraform v0.12.13, then run cmd to upgrade without error:
```hcl
terraform init
find . -name '*.tf' -printf "%h\n" | xargs -n1 terraform 0.12upgrade -yes
```
2. run terraform apply encounter error
```hcl
rm -rf .terraform/
terraform init
terraform apply
```
3. change provider.openstack v1.21.1 to provider.openstack v1.24.0 the same issue
```hcl
rm -rf .terraform/
terraform init
terraform apply
```

**Comment by SerenaLi279** [comment]
@jtopjian 
I am trying to upgrade terraform from v0.11.14 to v0.12.13.
Could you please help to check this issue, and tell us how to fix it?

**Comment by ozerovandrei** [comment]
@SerenaLi279 
Hello.
Could you please describe how do you perform `provider` block configuration?
https://www.terraform.io/docs/providers/openstack/#configuration-reference

Do you have separate `provider` block in on of your HCL manifests or do you use some other ways to configure it (environment variables, conf.yaml, etc.)?

**Comment by SerenaLi279** [comment]
@ozerovandrei
I use a file to configure with following content: e.g. file keystone.rc, and source it before run terraform cmd
```hcl
#!/bin/bash

export OS_TENANT_NAME='a591_CLCM'
export OS_PROJECT_NAME='a591_CLCM'
export OS_USERNAME='xxx'
export OS_INSECURE='True'
export OS_USER_DOMAIN_NAME='Default'
export OS_CACERT='/opt/clcm/a591.pem'
export OS_IDENTITY_API_VERSION='3'
export OS_AUTH_URL='https://xxx:13000/v3'
export OS_REGION_NAME=''
export OS_PROJECT_DOMAIN_NAME='Default'
export OS_PASSWORD='xxx'
```

**Comment by ozerovandrei** [comment]
I guess that we need to make changes to "insecure" flag that should be done in https://github.com/terraform-providers/terraform-provider-openstack/pull/494

**Comment by SerenaLi279** [comment]
@ozerovandrei 
I also found that this https://github.com/terraform-providers/terraform-provider-openstack/pull/494, so I do not know why I encounter this issue. 
so could you please us to fix it or some work around?

**Comment by kayrus** [comment]
I guess that the `True` bool value is not parsed correctly. it should be `true`

**Comment by SerenaLi279** [comment]
@kayrus 
You mean this is a bug?

**Comment by kayrus** [comment]
@SerenaLi279 don't know yet. Can you try with the `true`?

**Comment by SerenaLi279** [comment]
@kayrus 
I don't know how to set it with the true.
I use a file to configure with following content: e.g. file keystone.rc, and source it before run terraform cmd(it works well when terraform v0.11.14 and before)
```hcl
#!/bin/bash

export OS_TENANT_NAME='a591_CLCM'
export OS_PROJECT_NAME='a591_CLCM'
export OS_USERNAME='xxx'
export OS_INSECURE='True'
export OS_USER_DOMAIN_NAME='Default'
export OS_CACERT='/opt/clcm/a591.pem'
export OS_IDENTITY_API_VERSION='3'
export OS_AUTH_URL='https://xxx:13000/v3'
export OS_REGION_NAME=''
export OS_PROJECT_DOMAIN_NAME='Default'
export OS_PASSWORD='xxx'
```

**Comment by kayrus** [comment]
@SerenaLi279 can you just unset the `OS_INSECURE` env variable and try again?

**Comment by SerenaLi279** [comment]
@kayrus 
thanks a lot, it works well when change export OS_INSECURE='True' to export OS_INSECURE='true
thanks again~

**Comment by kayrus** [comment]
@SerenaLi279 just an advice, use the `OS_INSECURE` **only** when you use a dev env and don't have a CA cert. Therefore I strongly recommend to unset the `OS_INSECURE` env variable.

**Comment by SerenaLi279** [comment]
@kayrus 
You mean not set OS_INSECURE or export OS_INSECURE='false', so I change it to 'false' and check it also works well.

**Comment by kayrus** [comment]
`unset OS_INSECURE` and remove the `export OS_INSECURE='True'` from the `keystone.rc` file

**Comment by SerenaLi279** [comment]
@kayrus 
Thanks a lot

**Comment by SerenaLi279** [comment]
Hi @kayrus 
I also encounter '**a bool is required**' for another two attribute 'no_gateway' and 'enable_dhcp' when using openstack_networking_subnet_v2
"**T**rue" works well before terraform upgraded to v0.12.13.  So maybe this is a common issue
```hcl
resource "openstack_networking_subnet_v2" "private_net1_ps1" {
  name       = "ps1"
  network_id = openstack_networking_network_v2.private_net1.id
  cidr       = "172.17.1.0/24"
  ip_version = "4"
  no_gateway = "True"
  enable_dhcp = "True"
}
```

**Comment by ozerovandrei** [comment]
@SerenaLi279 you need to use "true" instead of "True":
https://www.terraform.io/docs/configuration/expressions.html#types-and-values

**Comment by ozerovandrei** [comment]
I guess that this issue could be closed now.
