### ISSUE TITLE
Is it possible to assign a certain floating ip to an instance?

### ISSUE THREAD

**Issue by hoover67** [terraform-providers/terraform-provider-openstack#927]
Dear all,

sorry that this isn't really an issue, but it's unclear to me how to assign a certain floating ip to an instance. 

I have 8 VMs I'm creating for a training class and right now they will get assigned random floating ips from the pool when tf creates the resources. What I'd like to do is to have tf assign 8 consecutive floating IPs to the instances according to their name ws01, ws02, ws03 and so on (those should get the IPs  .201, .202, 203). 

Is something like this possible or would I need to create network ports first with fixed IPs first? the floatingip_v2 instance only knows about the "pool" argument so I'm a bit unclear if something like this is at all possible.

Thanks, Uwe

**Comment by ozerovandrei** [comment]
Hello @hoover67 

You can try to use the [openstack_networking_floatingip_v2](https://www.terraform.io/docs/providers/openstack/d/networking_floatingip_v2.html) resource with the configured `address` argument.
It depends on your cloud whether you can configure this address or not.

After that you will need to attach the created floating IP to an instance. You can try to use `openstack_networking_floatingip_associate_v2` + `openstack_networking_port_v2 ` and then use this particular port with you instance or you can try to use `openstack_compute_floatingip_associate_v2 `.
