### ISSUE TITLE
Manila acceptance tests are failing

### ISSUE THREAD

**Issue by kayrus** [terraform-providers/terraform-provider-openstack#931]
### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_sharedfilesystem_sharenetwork_v2

### Debug Output

> FAIL: TestAccSFSV2ShareNetwork_basic (31.94s)
> testing.go:630: Error destroying resource! WARNING: Dangling resources 
>    may exist. The full state and error is shown below.
>
>    Error: errors during apply: Error deleting OpenStack Neutron Subnet: Bad request with: [DELETE http://192.168.0.15:9696/v2.0/subnets/6ed7384b-f3e2-4ad2-8431-9dfa98cc4006], error message: {"NeutronError": {"message": "Invalid input for operation: Failed to create port on network 7266395f-bf99-4bd5-aac8-bb8156ab49c9, because fixed_ips included invalid subnet ff722cc0-eb3f-4dda-9404-49ef81c2f8af.", "type": "InvalidInput", "detail": ""}}

https://logs.openlabtesting.org/logs/98/898/9c978d46b56c0892ca6b19fa02a09b98764b6c35/check/terraform-provider-openstack-acceptance-test/ec953ec/

**Comment by kayrus** [comment]
@wangxiyuan, @huangtianhua, have you changed something? Same tests tests worked fine yesterday.

**Comment by Shonei** [comment]
I had the same test fail in #928 . I have included what I believe is the fix in that Pull requests as it was a one character change.

**Comment by kayrus** [comment]
I'll try to cherry pick your fix. I wonder why it did work before...

**Comment by Shonei** [comment]
Not sure. The fix is in `openstack/resource_openstack_sharedfilesystem_sharenetwork_v2_test.go`. It must be something done recently as when I checked the other pull requests were failing for different reasons.

**Comment by wangxiyuan** [comment]
@kayus, No, openlab did nothing.

**Comment by kayrus** [comment]
@wangxiyuan sorry for bothering. Looks like the https://github.com/terraform-providers/terraform-provider-openstack/pull/928/commits/bb8fd1572b0253dc409bfd244bc61b8331117612 command fixed tests. Closing.
