### ISSUE TITLE
Error with os-tenant-networks

### ISSUE THREAD

**Issue by tnguyen14** [terraform-providers/terraform-provider-openstack#95]
I think a recent change in v0.2.0 caused a weird error for me.

I was able to do `terraform plan` and `terraform apply` to bring up a VM on openstack successfully. I then tried to do `terraform destroy`, and got this error:

```
openstack_compute_instance_v2.instance: Refreshing state... (ID: 732f11df-e122-4918-9554-42eff4de533e)
openstack_compute_floatingip_v2.ip: Refreshing state... (ID: 833)
Error refreshing state: 1 error(s) occurred:

* module.fe_master.module.compute.openstack_compute_instance_v2.instance: 1 error(s) occurred:

* module.fe_master.module.compute.openstack_compute_instance_v2.instance: openstack_compute_instance_v2.instance: Error trying to get network information from the Nova API: An error occured while querying the Nova API for network information: Expected HTTP response code [200 204] when accessing [GET https://openstack.url/v2.1/ec64afd6f5e547bb8b1a503cc08e2c7f/os-tenant-networks], but got 403 instead
{"forbidden": {"message": "Policy doesn't allow os_compute_api:os-tenant-networks to be performed.", "code": 403}}
```

Then when I do `terraform plan` again, I see the same error.

I checked with our cloud infrastructure team and they said that they do not allow access on `os_compute_api:os-tenant-networks` because they don't want me to delete tenant networks.

Is this a bug? I just want to delete the compute instance and floating IP, but not the network.

I think this might be due to https://github.com/terraform-providers/terraform-provider-openstack/commit/52adfae4febe4dba1cde5652fd382d9b2e5a69e5, but I'm not sure.

### Terraform Version
`v0.10.1`

### Affected Resource(s)
Please list the resources as a list, for example:
- `openstack_compute_instance_v1.instance`

**Comment by tnguyen14** [comment]
When I pin the provider version to `0.1.0`, I am able to destroy it successfully.

**Comment by jtopjian** [comment]
@tnguyen14 Yes, that would have been the commit that caused the error you're seeing.

For some reason, Terraform is unable to create a network client. Can you provide the output of the following command in a Github gist:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

Please make sure to remove or censor any sensitive information.

Thanks!

**Comment by tnguyen14** [comment]
Do you want me to do that with the `0.2.1` version?

**Comment by jtopjian** [comment]
Yes, with the failing version.

**Comment by tnguyen14** [comment]
When trying to do `terraform apply` again, I'm now getting this following error followed by "TERRAFORM CRASH"

```
2017-08-30T18:54:14.476-0400 [ERROR] plugin.terraform-provider-openstack_v0.2.1_x4: error parsing json from plugin: error="json: cannot unmarshal string into Go value of type map[string]interface {}"
```

I'm not sure what would cause it. Am heading out of the office for now, will try again tomorrow. If you have any suggestion, please let me know.

**Comment by jtopjian** [comment]
In order for us to troubleshoot, we'll need to see the debug logs - even for a crash.

**Comment by tnguyen14** [comment]
@jtopjian Here's the log output of
```
OS_DEBUG=1 TF_LOG=DEBUG terraform plan -destroy
```

https://gist.github.com/tnguyen14/1d159b54560eee13dca39af50ec3f340#file-plan-log

Is that helpful?

**Comment by jtopjian** [comment]
@tnguyen14 Yes, thanks :)

In the debug logs you can see this:

```
2017/09/05 15:55:38 [DEBUG] Unable to obtain a network client
```

Which is being triggered [here](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/compute_instance_v2_networking.go#L165). For some reason, Terraform is not able to connect to the Networking/Neutron service. Are you able to use any of the `openstack_networking_*` resources?

As a temporary workaround, and also as a last resort, you can specify _both_ the network uuid and name in your instance:

```
network {
  uuid = "some-uuid"
  name = "some-network"
}
```

This workaround was put into place to assist in scenarios like the one you're running into.

**Comment by tnguyen14** [comment]
I am able to to do `terraform plan` and `terraform apply` fine.

Once I run `terraform plan -destroy` once, I get the error

```
Error trying to get network information from the Nova API: An error occured while querying the Nova API for network information: Expected HTTP response code [200 204] when accessing [GET https://openstack.company.com:8774/v2.1/b6cf271c3e084365ad70ad3b0776c9ec/os-tenant-networks], but got 403 instead
{"forbidden": {"message": "Policy doesn't allow os_compute_api:os-tenant-networks to be performed.", "code": 403}}
```
and any subsequent `terraform plan` gives that error as well.

**Comment by jtopjian** [comment]
@tnguyen14 It might be best to figure out why you aren't able to connect to the OpenStack network service.

are you able to create any of the `openstack_networking_*` resources without error?

**Comment by tnguyen14** [comment]
@jtopjian Yes, I believe so. That is how I was able to do `terraform plan` and `terraform apply` and successfully created the resource at first.

**Comment by jtopjian** [comment]
From your logs I see that you created two resources:

* openstack_compute_floatingip_v2
* openstack_compute_instance_v2

Both of these are compute (nova) based services.

Can you try creating a `openstack_networking_floatingip_v2` resource and provide the output of:

```shell
$ OS_DEBUG TF_LOG=DEBUG terraform apply
```

I'd like to see the full apply cycle - something in those logs might provide insight as to why the compute instance isn't working.

**Comment by tnguyen14** [comment]
I get this error trying to do that

```
* openstack_networking_floatingip_v2.floatip_1: Error creating OpenStack network client: No suitable endpoint could be found in the service catalog.
2017/09/07 12:09:59 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
```

**Comment by jtopjian** [comment]
OK, in a way this is good. It means that there's a general problem connecting to the network service and this isn't just a problem with the `openstack_compute_instance_v2` resource.

Now we just have to figure out why you can't connect to your network service. That's probably a question for your OpenStack admins. You can start poking around by doing:

```shell
$ openstack catalog list
```

and seeing if there's a catalog entry for Neutron / Networking.

**Comment by tnguyen14** [comment]
There is no entry for Networking. I believe the admin disabled access to Networking. 

Since my resources are only related to compute resources, why should `terraform destroy` try to connect to the Networking API?

**Comment by jtopjian** [comment]
That's actually a really good question. There's only one place where a connection to the network service should be made and that's during Create.

I'm going to have to dig into this a little more. Give me a day or so and I'll get back to you.

**Comment by tnguyen14** [comment]
Thanks a lot for your support so far @jtopjian.

I'm thinking of pinning the terraform-provider-openstack plugin to version below 0.2 in order to avoid this issue temporarily.

**Comment by tnguyen14** [comment]
@jtopjian do you have any update on this issue?

**Comment by jtopjian** [comment]
@tnguyen14 Sorry for the delay.

I haven't been able to reproduce this problem. I've disabled access to my own `os-tenant-networks` in order to trigger an error when something tries to access that API. I'm able to reproduce this problem when _creating_, but not when doing a `plan -destroy`.

I'm using the following configuration as a test:

```hcl
resource "openstack_compute_floatingip_v2" "fip" {
  pool = "public"
}

resource "openstack_compute_instance_v2" "instance_1" {
  name = "instance_1"
  security_groups = ["default"]
  network {
    name = "private"
    uuid = "4d3676c0-e5df-4c69-94f9-36b8e8feaefd"
  }
}

resource "openstack_compute_floatingip_associate_v2" "fip" {
  instance_id = "${openstack_compute_instance_v2.instance_1.id}"
  floating_ip = "${openstack_compute_floatingip_v2.fip.address}"
}
```

which I think resembles what is in the debug logs you provided. Can you confirm?

Also, a few other questions:

1. Can you reproduce this constantly? If you destroy your environment and rebuild it, you're able to trigger this error each time you run `terraform plan -destroy`?
2. Is it possible there is a rogue Terraform binary or plugin floating around? I didn't see this in the logs, but just want to make sure.

**Comment by tnguyen14** [comment]
@jtopjian My sincere apologies for the super delayed response.

I had to pin the openstack provider version at `0.1.0` in order to proceed with bringing up the infrastructure. Just got some time to circle back to this now.

I used the same configuration as yours (except for the `network` part), pin the provider back to `0.2.2` and continues to see the behavior as I was seeing before.

I was able to `terraform plan` and `terraform apply`. However, after the resources are created, running `terraform plan -destroy` gives me the same message.

```
:; terraform plan -destroy
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

openstack_compute_instance_v2.instance_1: Refreshing state... (ID: 69af7dde-7d16-4169-85c1-0751e944a9c9)
openstack_compute_floatingip_v2.fip: Refreshing state... (ID: 2895)
Error refreshing state: 1 error(s) occurred:

* openstack_compute_instance_v2.instance_1: 1 error(s) occurred:

* openstack_compute_instance_v2.instance_1: openstack_compute_instance_v2.instance_1: Error trying to get network information from the Nova API: An error occured while querying the Nova API for network information: Expected HTTP response code [200 204] when accessing [GET https://openstack.url:8774/v2.1/b6cf271c3e084365ad70ad3b0776c9ec/os-tenant-networks], but got 403 instead
{"forbidden": {"message": "Policy doesn't allow os_compute_api:os-tenant-networks to be performed.", "code": 403}}
```

This is happening consistently, each time I run `terraform plan -destroy`. I am also unable to run `terraform destroy`.

 I am not aware of any binary or plugin floating around either.

Please let me know if there's something I could provide to help debugging this further.

My sincere apologies for being late on the response.

**Comment by khdegraaf** [comment]
Just as an FYI on this issue, the Huawei/OTC (and other Huawei/Openstack cloud providers) are running on an older version of OpenStack, and have a number of apis disabled (including os-tenant-networks).  I plan to make sure our fork of the terraform-provider-openstack handles this (it causes a few problems), and when done, see if I can't port any improvements into the official terraform-provider-openstack.  But it is likely going to be a month or two before I am likely to work on this.

**Comment by jtopjian** [comment]
@tnguyen14 

> My sincere apologies for the super delayed response.

It's no problem at all 😄 

> This is happening consistently, each time I run terraform plan -destroy. I am also unable to run terraform destroy.

I am absolutely floored by this. I'll have to think about how else we can debug this issue. It almost feels like something internal to the cloud you're using is triggering that API to be called.

In the meantime, let's do a quick review...

1. Can you create an instance with _no_ networks defined? When you don't specify a network, OpenStack should launch the instance on the "default" network automatically (meaning, if there is only one network available to you, that's the default).

2. Can you create an instance that has _both_ a network uuid and name specified?

```hc
network {
  uuid = "some-uuid"
  name = "some-network"
}
```

In either of these situations, does `terraform plan -destroy` trigger the error?

@khdegraaf 

>  But it is likely going to be a month or two before I am likely to work on this.

That sounds great. No pressure or expectation, but if you come across any fixes for special environments, definitely send us a patch :)

**Comment by jtopjian** [comment]
@tnguyen14 Quick question: does upgrading to the latest Terraform core (10.7) help at all?

**Comment by tnguyen14** [comment]
@jtopjian upgrading to 10.7 gives me the same results.

The example I'm using does not declare a network property, so I'm guessing it's already using the "default" network?

In order to test an example with a specific network, do I have to create that network first somehow?

**Comment by jtopjian** [comment]
> The example I'm using does not declare a network property, so I'm guessing it's already using the "default" network?

That's correct.

If you launch an instance that way (not specifying a network block) and then do `terraform show`, do you see any network information listed?

> In order to test an example with a specific network, do I have to create that network first somehow?

If the above exercise works (if you see a network UUID and name listed), then you can turn around and add that information to the instance in the form of a network block. We're kind of bootstrapping network discovery at this point.

Let me know how that goes :)

**Comment by tnguyen14** [comment]
@jtopjian I know this is months behind, but testing with the network name (UUID is empty for me) still gives me the same error. So is the case with not declaring a network.

**Comment by tnguyen14** [comment]
@jtopjian do you have any thought on what else I could do to debug/ figure out a fix here?

**Comment by jtopjian** [comment]
@tnguyen14 I really apologize.

I'm still quite baffled by this issue.

Let's try a different approach:

Can you make note of the different ways you can and can't create an instance using the `openstack` command-line tool?

```shell
$ openstack --debug server create ...
$ openstack --debug server create ... --nic net-id=<uuid>
```

In the debug output, you'll see a POST with the body being sent. Can you compare this to when you run Terraform with `OS_DEBUG=1`?

The intent here is to compare successful ways in which you can create instances on the command-line but not with Terraform. Hopefully this might provide a lead.

**Comment by tnguyen14** [comment]
@jtopjian the problem I seem to see is with destroying a box. What command should I try to do that?

**Comment by tnguyen14** [comment]
@jtopjian interestingly enough, I was able to run that `openstack server delete` command successfully.

**Comment by tnguyen14** [comment]
@jtopjian could it mean that the problem lies in how the provider translate into openstack?

**Comment by jtopjian** [comment]
@tnguyen14 I apologize for the delay.

I'm quite sure this issue is local to the OpenStack environment you're using - there is some kind of local modification being done since this issue is not apparent on any of the clouds we test on. Unfortunately I haven't had a chance to review everything over to see if I can spot where the issue is.

**Comment by tnguyen14** [comment]
@jtopjian no worries about delay. I agree that it is probably a local setting. Just trying to figure out what it might be. What I'm not sure on is why `0.1.0` works, but `0.2.0` broke it.

**Comment by jtopjian** [comment]
> Just trying to figure out what it might be. What I'm not sure on is why 0.1.0 works, but 0.2.0 broke it.

There were significant network changes made between 0.1.0 and 0.2.0.
