### ISSUE TITLE
Enhance retry behavior of openstack_lb_member_v2 & openstack_lb_listener_v2 resources

### ISSUE THREAD

**Issue by sbueringer** [terraform-providers/terraform-provider-openstack#950]
### Terraform Version
- terraform 0.12.8
- terraform provider openstack 0.25.0

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_lb_member_v2
- openstack_lb_listener_v2

### Actual Behavior

Terraform usually creates a lb_member (we have the same behavior with lb listeners) like this:
* Create lb member:
  * Request: POST `https://<openstack-api>/v2.0/lba
as/pools/ec496f24-f4a3-458e-9677-cbbaab95dfdb/members`
  * Response: 200
* Wait for state to become [Active]:
  * Request: GET `https://<openstack-api>/v2.0/lbaa
s/loadbalancers/574d894d-a3c7-404d-83b7-c173fe249494/statuses`
  * Response: 200
  * until provisioning_status == "ACTIVE"

From time to time we have the following behavior. 

* Create lb member:
  * Request: POST `https://<openstack-api>/v2.0/lba
as/pools/ec496f24-f4a3-458e-9677-cbbaab95dfdb/members`
  * Response: 500
* Retry lb member:
  * Request: POST `https://<openstack-api>/v2.0/lba
as/pools/ec496f24-f4a3-458e-9677-cbbaab95dfdb/members`
  * Response: 409
  * Response Body: 
     ```json
        {                                  
           "NeutronError": {
             "detail": "",
             "message": "Member with address 10.6.0.10 and protocol_port 30001 already present in pool ec496f24-f4a3b",                                                                        
             "type": "MemberExists"
           }
        }
     ```
* [repeat until timeout] Retry lb member

Our problem is that even though the first create call returns 500 the lb member has been created successfully in OpenStack

### Expected Behavior
What should have happened?

It would be very nice if a handling could be implemented to detect if the lb member (or listener) already exists when retrying and receiving 409er errors (with NeutronErrors like "MemberExists")

### Related

To mitigate the issue on our side I implemented a quick hack here: https://github.com/c445/terraform-provider-openstack/commit/aac140caa62944fb956f9e4ccfc3d54090559f04

I'm not sure what the correct solution for this problem would be.

**Comment by kayrus** [comment]
@sbueringer which endpoint do you use? neutron lbaas v2 or octavia? Do you have an access to openstack logs?

**Comment by sbueringer** [comment]
Hi
I'm using neutron lbaasv2. We're using VMWare Integrated Openstack and I don't really have access to the logs. But for me it's basically the question if the provider should retry in case of errors like this or not. For us it's okay for now that we patched it in our fork and we will move away from terraform to provision loadbalancers sooner or later.

So I can close this issue except if it's a problem for somebody else or it's an issue in general which you want to address.

**Comment by kayrus** [comment]
@sbueringer in your case neutron lbaas v2 API has an issue, when it returns 500 and does add a member into the pool. It is not effective to add a hook for every openstack bug. It is better to fix the root cause.

**Comment by sbueringer** [comment]
@kayrus It's okay for me if it won't get fixed upstream. I just though I propose the idea to be more stable against failures like this. I'm perfectly fine with patching our terraform openstack provider. 
It's just not realistic for us to get these fixes upstreamd into VIO and NSX-V.

So let's close this issue here?

**Comment by kayrus** [comment]
In case, when 500 error is returned, API should not apply any changes, this is definitely a bug. neutron lbaas v2 is outdated, everybody moves to octavia.

**Comment by sbueringer** [comment]
Okay got it. Yeah I know... Unfortunately VMWare is kind of slow with supporting Octavia :(

But sounds reasonable to close this issue if no changes should be applied in this case
