### ISSUE TITLE
openstack_lb_listener_v2 resource lacks support for insert-header parameter

### ISSUE THREAD

**Issue by pmisiak** [terraform-providers/terraform-provider-openstack#954]
Hi,

openstack_lb_listener_v2 resource lacks support for insert-header parameter which is supported by Octavia in OpenStack Stein.

OpenStack client output:

$ openstack loadbalancer listener create
usage: openstack loadbalancer listener create [-h]
                                              [-f {json,shell,table,value,yaml}]
                                              [-c COLUMN]
                                              [--max-width <integer>]
                                              [--fit-width] [--print-empty]
                                              [--noindent] [--prefix PREFIX]
                                              [--name <name>]
                                              [--description <description>]
                                              --protocol
                                              {TCP,HTTP,HTTPS,TERMINATED_HTTPS,UDP}
                                              [--connection-limit <limit>]
                                              [--default-pool <pool>]
                                              [--default-tls-container-ref <container_ref>]
                                              [--sni-container-refs [<container_ref> [<container_ref> ...]]]
                                              [--insert-headers <header=value,...>]
                                              --protocol-port <port>
                                              [--timeout-client-data <timeout>]
                                              [--timeout-member-connect <timeout>]
                                              [--timeout-member-data <timeout>]
                                              [--timeout-tcp-inspect <timeout>]
                                              [--enable | --disable]
                                              [--client-ca-tls-container-ref <container_ref>]
                                              [--client-authentication {NONE,OPTIONAL,MANDATORY}]
                                              [--client-crl-container-ref <client_crl_container_ref>]
                                              [--allowed-cidr [<allowed_cidr>]]
                                              <loadbalancer>
openstack loadbalancer listener create: error: too few arguments

OpenStack client show on running listener with insert-headers configured:

$ openstack loadbalancer listener show 432567d6-5cd8-4ddf-8e02-ac80b5477f06
+-----------------------------+------------------------------------------------------------------------------------+
| Field                       | Value                                                                              |
+-----------------------------+------------------------------------------------------------------------------------+
| admin_state_up              | True                                                                               |
| connection_limit            | -1                                                                                 |
| created_at                  | 2019-11-29T13:27:34                                                                |
| default_pool_id             | 908f765f-ead0-411d-8b8a-4587d801ae79                                               |
| default_tls_container_ref   | https://XXXXXXXXXXXXXXXXXXXXXXX:9311/v1/secrets/XXXXXXXXXXXXXXXXXXXXXXXXXXXXX |
| description                 |                                                                                    |
| id                          | 432567d6-5cd8-4ddf-8e02-ac80b5477f06                                               |
| insert_headers              | X-Forwarded-For=true                                                               |
|                             | X-Forwarded-Proto=true                                                             |
| l7policies                  |                                                                                    |
| loadbalancers               | c0fc677e-bb78-4fba-aa5d-09629a9fce10                                               |
| name                        |                                                                                    |
| operating_status            | ONLINE                                                                             |
| project_id                  | cefb973ad2414c18820ae361ce1dc6e3                                                   |
| protocol                    | TERMINATED_HTTPS                                                                   |
| protocol_port               | 443                                                                                |
| provisioning_status         | ACTIVE                                                                             |
| sni_container_refs          | []                                                                                 |
| timeout_client_data         | 50000                                                                              |
| timeout_member_connect      | 5000                                                                               |
| timeout_member_data         | 50000                                                                              |
| timeout_tcp_inspect         | 0                                                                                  |
| updated_at                  | 2019-12-24T15:31:06                                                                |
| client_ca_tls_container_ref | None                                                                               |
| client_authentication       | NONE                                                                               |
| client_crl_container_ref    | None                                                                               |
| allowed_cidrs               |                                                                                    |
+-----------------------------+------------------------------------------------------------------------------------+

This is needed for example to add X-Forwarded-For header in HTTP request so that a backend server will have a client real source IP address.

**Comment by ozerovandrei** [comment]
I see that this is already implemented in the upstream library so adding this won't be a problem: https://github.com/gophercloud/gophercloud/blob/master/openstack/loadbalancer/v2/listeners/requests.go#L133

**Comment by ozerovandrei** [comment]
It was implemented in #959 and will be available in `1.26.0` release.
