### ISSUE TITLE
The security group can only be applied to one of nics when VM is deployed with multiple nics

### ISSUE THREAD

**Issue by yuyangbj** [terraform-providers/terraform-provider-openstack#96]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
0.9.11
### Affected Resource(s)
- openstack_compute_instance_v2
- openstack_networking_port_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "openstack" {
  insecure = "true"
  user_name = "admin"
  tenant_id = "f85b5e0bf424417fb0ffb1089f50e88b"
  password = "openstack"
  auth_url = "https://10.111.161.15:5000/v3"
  domain_name = "default"
}

resource "openstack_networking_secgroup_v2" "ncp_port_secgroup" {
  name = "my_test_security_group"
  description = "The security group for k8s api network"
}

resource "openstack_networking_secgroup_rule_v2" "ingress_tcp_secgroup_rule" {
  direction = "ingress"
  ethertype = "IPv4"
  protocol  = "tcp"
  port_range_min = 1
  port_range_max = 65535
  remote_ip_prefix = "0.0.0.0/0"
  security_group_id = "${openstack_networking_secgroup_v2.ncp_port_secgroup.id}"
}

resource "openstack_networking_port_v2" "bastion_api_port" {
  name = "my_test_port"
  network_id = "eb99653a-5634-4aa5-882a-b5b62792ff72"
  admin_state_up = "true"
}

resource "openstack_compute_instance_v2" "bastion-host" {
  name = "my_test_host"
  image_id = "a216505f-6c95-4340-9ee4-7ec20a11e6a4"
  flavor_id = "3"
  config_drive = true
  security_groups = ["k8s-securitygroup"]
  user_data = "${file("bootscript.sh")}"
  network {
    uuid = "a64ee23e-5ab4-45aa-98fb-45fb5cda9183"
  }
  network {
    port = "${openstack_networking_port_v2.bastion_api_port.id}"
  }
  depends_on = ["openstack_networking_secgroup_v2.ncp_port_secgroup"]
}
```
 
### Expected Behavior
The security group I applied to VM should be applied to every nic

### Actual Behavior
I checked the open stack resource created by terraform, the security group is only applied to one of the nic.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by jtopjian** [comment]
@yuyangbj Thanks for submitting this issue.

I think this is normal OpenStack behavior, although it can be confusing. The concept of a "port" is something that can be entirely decoupled from an instance. If you apply a security group to a port, the rules of that SG will only be applied to the port.

If you apply a SG to an instance, it _should_ apply all rules to all nics, but since you are defining an instance's network with a port, this rule might not apply.

One thing to try is to define your instance's second network like:

```network {
  uiud = "eb99653a-5634-4aa5-882a-b5b62792ff72"
}
```

and see if the rules are applied to all NICs.

**Comment by yuyangbj** [comment]
@jtopjian thanks for your response, you are right, it is not a problem and I'll close it. see the doc, the bottom part on this page: https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html?
