### ISSUE TITLE
[Discuss] should we remove ubuntu-trusty nodeset?

### ISSUE THREAD

**Issue by bzhaoopenstack** [terraform-providers/terraform-provider-openstack#960]
Hi Team,

I'm a maintainer from openlab.

ubuntu-trusty is too old, and the test node is for openstack mitaka which already 5 years. So I think it's better to raise the discusstion to make clear that whether we still need ubuntu-trusty test node.

Thanks

**Comment by bzhaoopenstack** [comment]
And if we are agree, I will post a PR the remove the mitaka related test job first. ;-)  . Waiting for team's feedback. Thanks

**Comment by ozerovandrei** [comment]
@bzhaoopenstack Hello.
I think that it's better to remove it since Trusty is EOL and also because Gophercloud already dropped it.

**Comment by bzhaoopenstack** [comment]
@ozerovandrei  Thanks for your advice and feedback. I will remove Trusty related in terraform-provider-openstack. Thank you
