### ISSUE TITLE
Mismatch reason: attribute mismatch: image_id

### ISSUE THREAD

**Issue by tianomonteiro** [terraform-providers/terraform-provider-openstack#990]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform Version: 0.11.11
Openstack 1.26.0 Plugin

### Affected Resource(s)
Please list the resources as a list, for example:

Resource ID: openstack_blockstorage_volume_v3.newBootvolume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

resource "openstack_blockstorage_volume_v3" "newBootvolume" {
  name                 = "${var.instance_name}-${var.disk_name}"
  size                 = "${var.disk_size}"
  volume_type          = "${var.disk_volume_type}"
  enable_online_resize = "true"
  image_id             = "${var.snapshot_bootdisk_uuid == "" ? var.image_id : ""}"
  availability_zone    = "${var.availability_zone}"

  metadata {
    ibmStackID        = "${var.ibm_stack_id}"
    isVolumeSnapshot  = "false"
  }

  timeouts {
    create = "60m"
    delete = "60m"
  }
  source_vol_id = "${var.snapshot_bootdisk_uuid}"
}

# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. 



In addition, running Terraform with the `OS_DEBUG=1` environment variable set will print additional information specific to the OpenStack provider which will be helpful for troubleshooting.

Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.


[terraform-error.txt](https://github.com/terraform-providers/terraform-provider-openstack/files/4405619/terraform-error.txt)


### Expected Behavior
What should have happened?

- Create a VM using external blockstorage boot disk using openstack_blockstorage_volume_v3 (With ImageId)
- Change the openstack_blockstorage_volume_v3 to use source_vol_id.
- Terraform need to delete the vm using openstack_blockstorage_volume_v3 with image id and recreate using the source_vol_id snapshot.

### Actual Behavior
What actually happened?

* openstack_blockstorage_volume_v3.newBootvolume: openstack_blockstorage_volume_v3.newBootvolume: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
Please include the following information in your report:
Terraform Version: 0.11.11
Resource ID: openstack_blockstorage_volume_v3.newBootvolume
Mismatch reason: attribute mismatch: image_id

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Is there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? A custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by kayrus** [comment]
@tianomonteiro could you please send a terraform script with defined values? At the moment it is unclear how to reproduce an issue.

**Comment by tianomonteiro** [comment]
[terraform.txt](https://github.com/terraform-providers/terraform-provider-openstack/files/4409108/terraform.txt)

- Try create a VM using the openstack_blockstorage_volume_v3 with image_id.
- Create a snapshot from this openstack_blockstorage_volume_v3.
- After, change the snapshot_bootdisk_uuid variable with this snapshot id.
- Terraform need recreate the snapshot_bootdisk_uuid and openstack_compute_instance_v2 using this snapshot id.

**Comment by tianomonteiro** [comment]
@kayrus did you understand my issue? Do you need more information about the issue?

**Comment by kayrus** [comment]
@tianomonteiro openstack cannot create VMs from a volume snapshot. You have explicitly convert a snapshot to a volume, then create a VM. See more details here: https://docs.openstack.org/api-ref/compute/?expanded=create-server-detail#create-server -> `block_device_mapping_v2`

Try to define `snapshot_id` instead of `source_vol_id`.

**Comment by tianomonteiro** [comment]
I changed but i got the same error:

Error applying plan:1 error(s) occurred:
* openstack_blockstorage_volume_v3.newBootvolume: openstack_blockstorage_volume_v3.newBootvolume: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
Please include the following information in your report:
    Terraform Version: 0.11.11
    Resource ID: openstack_blockstorage_volume_v3.newBootvolume
    Mismatch reason: attribute mismatch: image_id
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0},

**Comment by kayrus** [comment]
@tianomonteiro can you use terraform 0.12 and use `nil` instead of an empty string? See more details about this bug here: https://github.com/hashicorp/terraform-plugin-sdk/issues/282

**Comment by tianomonteiro** [comment]
Sorry is not a snapshot from volume is a copy from boot volume using openstack_blockstorage_volume_v3.
Look, i am creating a new volume openstack_blockstorage_volume_v3 from this copy and after including this volume in a new VM using block_device.
The step by step:
1 Create a new volume from image ID.
2 Create a VM using this volume in a block_device block.
3 Create a volume "copy" using openstack_blockstorage_volume_v3 from the VM Boot Volume (1 Step) (Using another terraform template, and get the volume ID from output).
4 Change the source_vol_id variable in the openstack_blockstorage_volume_v3 with the volume copy ID from step 3.

Result: Terraform need to recreate the openstack_blockstorage_volume_v3 and the openstack_compute_instance_v2 using the block_device restore from openstack_blockstorage_volume_v3. 
I shared my terraform template in this post.

**Comment by tianomonteiro** [comment]
I can not use this terraform 0.12 because i am using Cloud Automation Manager that use 0.11 version. I can try upgrade CAM to use this another terraform version... If i use terraform 0.12 this solution will work?

**Comment by kayrus** [comment]
@tianomonteiro what if you just omit the image_id definition, don't set it to an empty string?

**Comment by tianomonteiro** [comment]
@kayrus i need the image_id to create the first disk to use at the Virtual Machine. When i create a copy from this disk and change virtual machine the disk informations i need to change the image_id to blank or null.
I tried to use terraform 0.12 and worked with null value.
Thank you.
